### ISSUE TITLE
Unable to comment on PR - this issue is to notify team that PR  #997 is ready for re-review

### ISSUE THREAD

**Issue by paustint** [rollbar/rollbar.js#1000]
@waltjones - RE: PR #997

There appears to be a github bug that only impacts this repo, but I am unable to comment or re-request your review on the PR.

I have made the requested changes and the PR is ready for your review again.  Thanks for the detailed feedback! 

![image](https://user-images.githubusercontent.com/5461649/158507608-fdba7187-6c41-4cf0-90fc-87cff4ee89cc.png)

**Comment by waltjones** [comment]
Approved and merged. Thank you!

**Comment by waltjones** [comment]
Thank you! Approved.
