### ISSUE TITLE
Add support for Error cause field

### ISSUE THREAD

**Issue by twschiller** [rollbar/rollbar.js#1010]
- Node and modern browsers [support an optional "cause" field](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Error#rethrowing_an_error_with_a_cause)
- For debugging re-thrown errors, it would be great if rollbar.js would support the nested errors and properly include the causes in the payload/stack trace

**Comment by cyrusradfar** [comment]
@twschiller Can't make promises, atm, butI  have been following the development of the Cause standard that's floating around. 

Is this the proposal that you want us to support: https://github.com/tc39/proposal-error-cause

**Comment by twschiller** [comment]
Thanks for the quick response @cyrusradfar. Yes, that link is for the stage 1 proposal

- IIRC: made it into the language: https://tc39.es/ecma262/multipage/fundamental-objects.html#sec-installerrorcause
- Archived Stage 4 proposal: https://github.com/tc39/proposal-error-cause
- Finished proposal tracking: https://github.com/tc39/proposals/blob/main/finished-proposals.md

**Comment by fregante** [comment]
@cyrusradfar I'd expect the `.cause` chain to be displayed similarly to this:

<img width="809" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/160231759-b7eec939-d3b9-4329-98d7-b07be425518d.png">

**Comment by waltjones** [comment]
Released in 2.25.0. https://github.com/rollbar/rollbar.js/releases/tag/v2.25.0
