### ISSUE TITLE
rollbar snippet newest version results in Access Denied from CDN?

### ISSUE THREAD

**Issue by jgb** [rollbar/rollbar.js#1013]
Hello,

I've just updated our rollbar snippet js to the latest version, which links to https://cdn.rollbar.com/rollbarjs/refs/tags/v2.24.1/rollbar.min.js which results in an Access Denied error given by the cdn.

Could this be fixed since it breaks rollbar?

Thanks!

jgb

**Comment by cyrusradfar** [comment]
@jgb we fixed the underlying issue. Please try again and thank you for reporting!
