### ISSUE TITLE
Please add this to some CDN

### ISSUE THREAD

**Issue by gligoran** [rollbar/rollbar.js#103]
Having this in a CDN should enable much easier integration in the start and then updating later on. You seem to update the JS library quite often, so making it easier for the users might also help with your granulation of versions that are used.

A lot of libraries I use in my project are available on [cdnjs.com](https://cdnjs.com/), so that could be a possibility.

**Comment by brianr** [comment]
Hi @gligoran -- thanks for the request! I think this may just be a docs problem. rollbar.js is currently hosted on Cloudfront, which is Amazon's CDN. The current version is served up from https://d37gvrvc0wt4s1.cloudfront.net/js/v1.3/rollbar.umd.min.js . Is that what you need?

**Comment by gligoran** [comment]
That's exactly it, @brianr! Thank you. I did find that you already put [version 1.4.1](
https://d37gvrvc0wt4s1.cloudfront.net/js/v1.4.1/rollbar.min.js) up there, which is great. It'll be a lot easier to upgrade now when I get the Rollbar notification that a newer version JS library is out.
