### ISSUE TITLE
Logging errors to rollbar from service worker script in chrome extension with manifest v3 does not work

### ISSUE THREAD

**Issue by tan-linx** [rollbar/rollbar.js#1040]
Logging errors to rollbar from the service worker script within a chrome extension does not work. 
Does anyone have the same issues regarding building a chrome extension with manifest v3 and has found a solution?

We investigated this issue but didn't get further. In manifest v3, instead of background pages, service workers are used which don't have access to the DOM. But it seems like rollbar still depends on the window global #141. The UMD version of Rollbar didn't fix this issue. Therefore it might also be related to updated security configurations?

**Comment by agentfuture** [comment]
As I understand for now is that rollbarjs uses `XMLHttpRequest` method which is not allowed in service worker scripts as of chrome manifest version 3. It should use new fetch API.

https://github.com/rollbar/rollbar.js/blob/c2c5310df90cdefcb8cfe8142377a4ee3987796b/dist/rollbar.js#L3452

**Comment by waltjones** [comment]
Thank you for these reports. We're working on this and aiming to have a release by Nov 30.

**Comment by jccr** [comment]
@waltjones That's great to hear, also ran into this blocker with our MV3 chrome extension.

In the meantime, you may be able to workaround this by using [apple502j/xhr-shim](https://github.com/apple502j/xhr-shim#:~:text=use%20it%20inside%20service%20workers) to "polyfill" XHR back into your service worker.

**Comment by waltjones** [comment]
This has been released now in v2.26.0.
