### ISSUE TITLE
Incorrect type when unsetting a person

### ISSUE THREAD

**Issue by srph** [rollbar/rollbar.js#1058]
Hi, I'm using `rollbar@^2.25.2`, and upon trying to unset a user like so:

```tsx
const payload = { person: { id: null } }
rollbar.configure({ payload })
```

I'm getting this type error:

```
Type '{ person: { id: null; }; }' is not assignable to type 'Payload'.
  The types of 'person.id' are incompatible between these types.
    Type 'null' is not assignable to type 'string | number'.ts(2322)
```

The docs instruct otherwise:

![image](https://user-images.githubusercontent.com/5093058/204989779-d1e87fa3-edad-49ac-b40a-a556a3720080.png)

Let me know if there's anything I may have missed. Thanks!

**Comment by waltjones** [comment]
Fix is released in v2.26.1. Thank you for the report.
