### ISSUE TITLE
Arrow function does not work in IE11

### ISSUE THREAD

**Issue by thinceller** [rollbar/rollbar.js#1064]
I understand that [rollbar.js is supported in IE8+](https://docs.rollbar.com/docs/javascript), but v2.26.0 includes some arrow functions.
https://github.com/rollbar/rollbar.js/blob/v2.26.0/src/browser/transport/fetch.js#L10-L32

In fact, our production code including v2.26.0 rollbar.js does not work in IE11.

**Comment by waltjones** [comment]
@thinceller thank you for the report. This will go in the next release.

**Comment by waltjones** [comment]
Fix is released in v2.26.1. Thank you again for the report.
