### ISSUE TITLE
Add code example for Chrome extensions manifest v3

### ISSUE THREAD

**Issue by tinacious** [rollbar/rollbar.js#1068]
[The current example](https://github.com/rollbar/rollbar.js/tree/master/examples/browser_extension) is not compatible with manifest 3.

[The manifest v3 migration guide](https://developer.chrome.com/docs/extensions/mv3/mv3-migration/#content-security-policy) specifies the following constraints:

> In addition, Manifest V3 disallows certain CSP modifications for extension_pages that were permitted in Manifest V2. The script-src, object-src, and worker-src directives may only have the following values:
>
> - self
> - none
> - Any localhost source, (http://localhost, http://127.0.0.1, or any port on those domains)

The current example uses manifest v2 and CSP value that is not allowed ([reference](https://github.com/rollbar/rollbar.js/blob/master/examples/browser_extension/manifest.json#L6)).

The Chrome Web Store is no longer accepting new extensions using manifest v2 so it is not possible to use Rollbar currently.

Do you have a recommendation for integrating Rollbar into a manifest v3 Chrome extension?

Thank you!

**Comment by waltjones** [comment]
@tinacious Thank you for the report.

The current version of Rolbar.js does support v3. I'll update the example, and link here.

**Comment by waltjones** [comment]
In addition to the new example in the linked PR, this doc has also been updated to be more informative. https://docs.rollbar.com/docs/using-rollbarjs-in-a-chrome-extension
