### ISSUE TITLE
Store events to send later if the network isn't available

### ISSUE THREAD

**Issue by brianr** [rollbar/rollbar.js#107]
(This is mostly relevant for mobile apps using embedded javascript.)

This feature means roughly: detect when the XHR post in `_processPayload` fails because the network is unavailable, and keep payloads on the queue to be processed later. Periodically retry.

Would pair nicely with #79, but isn't dependent on it.

**Comment by jonahx** [comment]
Fwiw, I've been searching for airbrake alternatives because they lack this feature.  Pretty surprised to see something I consider core to error reporting missing from the clients of the two biggest error tracking SaS companies.

**Comment by brianr** [comment]
@jonahx Thanks for the upvote on this :)

Question--is your situation that you have a web app where clients frequently get disconnected? A mobile app using a webview? Something else?

**Comment by jonahx** [comment]
Yeah, it's a web app often used on mobile ipads, where disconnects are not uncommon.  So I'd missing a ton of errors, and perhaps the most important ones, without this feature.  But my use case aside, XHR requests fail from time to time, even on home connections.  I was originally using a home-rolled email error reporter, 40 lines of code, and it had a retry feature.  I was using just storing the errors in memory, but replacing that with local storage would be trivial.  Just saying, you could guys could probably add this in a few hours to a day of work.

**Comment by code-constructor** [comment]
+1

**Comment by pimterry** [comment]
I've had a run at fixing this: see #186.

**Comment by coryvirok** [comment]
Closing since @pimterry PR was merged.
