### ISSUE TITLE
Electron application error grouping on Windows

### ISSUE THREAD

**Issue by DonMcNamara** [rollbar/rollbar.js#1072]
I have an electron application and the grouping is not working. It seems like each Windows user is getting a different error grouping. My guess is that this is being caused by the username in the paths of the stack.

I've noticed the paths are in several places in the raw event data. They are in the:
  `body.trace_chain[].frames[].filename` 
  `body.trace_chain[].frames[].runtimePosition.filename`
  `notifier.diagnostic.raw_error.stack` 

What part of the raw event data is used for grouping purposes?

Is there a better way to fix the issue of grouping on Electron on Windows where the username (and therefore path) is frequently different?

Note, this doesn't seem to be a problem on MacOS because all the paths for the electron app start under a common Application directory.

Here is a sample stack from an electron app in Windows:
```
Error: testing an error at click (C:\Users\user2_000\AppData\Local\Programs\mabl-dev\resources\app.asar\build\electron\main.js:2:146729) at MenuItem.click (node:electron/js2c/browser_init:73:1908) at EventEmitter.a._executeCommand (node:electron/js2c/browser_init:81:2453)
```

Update: I just sent this request to the support contact as well. I will update here if I get a solution.

**Comment by waltjones** [comment]
`body.trace_chain[].frames[].filename` is used in grouping.
`body.trace_chain[].frames[].runtimePosition.filename` _may_ be used in grouping, and if not, may be used in the future.
`notifier.diagnostic.raw_error.stack` is not used in grouping.

Short term:

a. You may be able to add a grouping rule based on the path and using a regex matching function. I'm not sure this will work and haven't tested this kind of use case. https://docs.rollbar.com/docs/custom-grouping

b. You may find it easier to add a transform function in your Rollbar.js config. In this case, you'd iterate the stack frames and replace or remove the usernames from the paths. https://docs.rollbar.com/docs/javascript#transforming-the-payload

Long term:

1. I'll pass this on to the grouping team and a rule may be added for this case, but I don't know what the schedule for that would be.

2. Rollbar.js supports default and custom rewrite patterns for stack frame filenames for React Native only. It would be a helpful improvement to support this in general for all Rollbar.js integrations. This could be included in an upcoming Rollbar.js release, but I don't have a schedule for that either. https://docs.rollbar.com/docs/source-maps#react-native

**Comment by DonAtMabl** [comment]
Thanks for the help! Right now I'm trying to solve this by setting the `server.root` to the user-specific portion of the path. If that doesn't work I will likely try the transform or maybe just set the fingerprint client-side using only the error message data.

**Comment by DonMcNamara** [comment]
Thanks for the help! Right now I'm trying to solve this by setting the server.root to the user-specific portion of the path. If that doesn't work I will likely try the transform or maybe just set the fingerprint client-side using only the error message data.
