### ISSUE TITLE
"Script error", even though the actual error was detected

### ISSUE THREAD

**Issue by dandv** [rollbar/rollbar.js#110]
Due to a [bug in Clicky](https://clicky.com/forums/?id=18249), I get a "Script error" when users click on SVGs.

However, the same error has been resolved correctly to "Uncaught TypeError: href.match is not a function".

I've attached a screencast.

![script error instead of actual error regression](https://cloud.githubusercontent.com/assets/33569/8745466/07550e3e-2c35-11e5-9c44-2e0322a2e7df.gif)

**Comment by coryvirok** [comment]
It could be that the same error was reported by more than 1 browser. Older browsers don't provide much information and some have issues with correctly reporting the full stack due to CORS issues.

Can you link me to your project so I can take a closer look?

**Comment by brianr** [comment]
Thanks @dandv for reporting this.

This should be fixed now (we fixed it on our end; no update required by you). The title won't change for existing active items, but you can resolve them and when they are seen next, they'll be reopened with the correct title.

I'm going to close this to clean things up, but please reopen if you find it isn't actually fixed.
