### ISSUE TITLE
Does rollbar.js support Deno?

### ISSUE THREAD

**Issue by tian-sheng-low** [rollbar/rollbar.js#1104]
[Deno](https://deno.com/runtime) is a new JavaScript V8 runtime other than NodeJS and it is compatible with most of the npm packages.
My team is trying to use rollbar.js with Deno, but rollbar.js seems to be failing silently without creating and sending the item to Rollbar.

```ts
import Rollbar from 'rollbar'

const rb = new Rollbar(...)
rb.error("test error")
```

We have even tried to use the rollbar API to create the item (https://docs.rollbar.com/reference/create-item) and it worked.
So, we are guessing maybe there is something between the compatibility of rollbar.js with Deno.

Any helps will be highly appreciated.

**Comment by waltjones** [comment]
I'll take a look at this and update here with what I find.

**Comment by tian-sheng-low** [comment]
@waltjones 
Hi, thanks for your response.
I have done some debugging and found that the issue only occurs for Deno v1.33.4 and later.
Seems to me like a http protocol issue.

I leave a comment there with some insight.
https://github.com/denoland/deno/issues/16923#issuecomment-1564190596

**Comment by tian-sheng-low** [comment]
@waltjones 
With the recent release of Deno v1.34.1, the issue has since been fixed.
You may kindly close this issue now.
Thanks for your support.

**Comment by rollbar-bborsits** [comment]
I'm glad your issue got fixed by now. Thanks, @tian-sheng-low for the confirmation.
