### ISSUE TITLE
Unable to run webdriver tests on page with rollbar JS 

### ISSUE THREAD

**Issue by ilangv** [rollbar/rollbar.js#111]
Hi,

We have integrated rollbar to our product site. While running webdriver tests, we see this exception:

Caused by: org.openqa.selenium.remote.ErrorHandler$UnknownServerException: Permission denied to access property '_wrapped'

There was a similar issue in bugsnag which was resolved with this change: https://github.com/bugsnag/bugsnag-js/commit/0478bf54778e534a2bf53dd129927b468e82447b

**Comment by coryvirok** [comment]
Thanks @ilangv. This is most likely fixed by https://github.com/rollbar/rollbar.js/pull/117 

Is this is still an issue for you?

**Comment by ilangv** [comment]
Thanks @coryvirok . The fix works well. 
Closing.
