### ISSUE TITLE
Listing items

### ISSUE THREAD

**Issue by mondalaci** [rollbar/rollbar.js#1116]
Can this library be used to list items as in https://docs.rollbar.com/reference/list-all-items ?

If not, the documentation should clarify that it's only for logging.

**Comment by mudetroit** [comment]
No, rollbar.js is not intended to be able to list all items. Like all of Rollbar’s SDKs it is used to report items into the Rollbar system. We will review the description of the package to make sure that is clear. Thanks for your feedback
