### ISSUE TITLE
Error with Rollbar Integration on Cloudflare Workers: "addEventListener(): useCapture must be false."

### ISSUE THREAD

**Issue by danielplan** [rollbar/rollbar.js#1129]
**Issue Description:**

I'm encountering an issue when using Rollbar with Astro 4 on the Cloudflare Workers JavaScript runtime. The error message I'm seeing is:

```
"addEventListener(): useCapture must be false."
```

**What I did**

I have integrated the Rollbar initialization script on the page level of Astro, to automatically catch errors in the SSR runtime.
```
import Rollbar from 'rollbar';
var rollbar = new Rollbar({
    accessToken: '<Access Token>',
    captureUncaught: true,
    captureUnhandledRejections: true,
    payload: {
        code_version: '1.0.0',
    },
});
```
 Once i am trying to run this with wrangler, this error pops up.
![image](https://github.com/rollbar/rollbar.js/assets/35629612/c56392ad-d46c-4b17-a5e0-d6ffdc7d67b8)

**Questions**
1. Am I doing something wrong with the Rollbar integration in Astro 4 on Cloudflare JavaScript Runtime?
2. Is it even possible to capture SSR errors with Rollbar in Astro/Vite-based Frameworks?

**Comment by ignacio-nacho-barbano** [comment]
I'm having the exact same issue https://github.com/ignacio-nacho-barbano/typescale-garden/tree/cloud-client-deploy

**Comment by brianr** [comment]
This is likely coming from the auto-instrumentation for the telemetry feature. Does the issue still take place if you disable autoInstrument, as follows:

```
import Rollbar from 'rollbar';
var rollbar = new Rollbar({
    accessToken: '<Access Token>',
    captureUncaught: true,
    captureUnhandledRejections: true,
    payload: {
        code_version: '1.0.0',
    },
    // added line:
    autoInstrument: false,
});
```

**Comment by MikeSpock** [comment]
That is exactly right, thank you so much! Shall all my github issues resolve this well and this fast! 🤗
