### ISSUE TITLE
Documentation for webpack example is a bit misleading 

### ISSUE THREAD

**Issue by Taytay** [rollbar/rollbar.js#114]
Hooray for using Webpack now, and for providing an example! Thanks!

The documentation for webpack says I can do this: 
```
var rollbarConfig = {
  accessToken: 'POST_CLIENT_ACCESS_TOKEN',
  captureUncaught: true,
  payload: {
    environment: 'development',
  }
};

var Rollbar = require('./rollbar.umd.nojson.min.js");
Rollbar.init(rollbarConfig);

```
Which is true.
However, the local `Rollbar` variable does not appear to be the same as the global Rollbar variable upon which I can call `configure` and other Rollbar methods. So, I ended up doing something like this instead:

```
var _rollbar = require('./rollbar.umd.nojson.min.js");
_rollbar.init(rollbarConfig);

// Now I've got a global Rollbar I can use as follows:
Rollbar.configure...
```

**Comment by coryvirok** [comment]
Thanks @Taytay. I updated the example here: https://github.com/rollbar/rollbar.js/commit/971859f3186cca215e175109045f16b07613d619
