### ISSUE TITLE
Error tossed by IE's compatibilty mode

### ISSUE THREAD

**Issue by justSteve** [rollbar/rollbar.js#115]
I have a class of js events where I want multiple actions to occur alongside the rollbar call so I've fashioned a class as is pasted below. Current generation IE is happy with this but in compat mode will toss a: *SCRIPT438: Object doesn't support property or method 'info'* on the line with *Rollbar.info(logObj);* Any thoughts one how to appease IE <10 here?

    if (LOGGING === null || typeof LOGGING === 'undefined')
       var LOGGING = {}; // object to holds all references and methods.

    var L = LOGGING; // create shortcut alias

    L.clientLogger = function () {

    var errorLevel = 'error';
    var infoLevel = 'log';

    var log = function (logLevel, id, obj) {

        var logObj = {};
        logObj[id] = obj;

        switch (logLevel) {
            case errorLevel:
                Rollbar.error(logObj);
                if (typeof $zopim !== 'undefined') {
                    $zopim && $zopim(function () {
                        $zopim.livechat.addTags(id);
                        $zopim.livechat.bubble.setTitle('Get Help Here!');
                    });
                }
                break;
            case infoLevel:
                Rollbar.info(logObj);
                if (typeof $zopim !== 'undefined') {
                    $zopim(function () {
                        $zopim.livechat.addTags(id);
                    });
                }
                break;
        }
    };
    var error = function (id, obj) {
        log(errorLevel, id, obj);
    };

    var info = function (id, obj) {
        log(infoLevel, id, obj);
    };
    return {
        errorLevel: errorLevel,
        infoLevel: infoLevel,
        log: log,
        error: error,
        info: info
      };
    }();

**Comment by coryvirok** [comment]
Hi Steve,

I just tested in IE 9 and it seems to work. I went to a page with rollbar.js installed and then in the develop console I did:

```js
// Pasted in the above code

var x = L.clientLogger;
x.info(3, {hello: 'world'});
```

I see the log in Rollbar with the id and object. Do you have a gist that reproduces the issue? Also, how are you loading rollbar.js?

**Comment by justSteve** [comment]
Thanks for the reply Cory - we can close this. The problem is not at Rollbar but rather how IE <10 is unable to umm... work. I've reproduced the same behavior without any Rollbar references. --appreciate the time.
