### ISSUE TITLE
Is the request to https://api.rollbar.com/api/1/item/ synchronous?

### ISSUE THREAD

**Issue by marcinpl87** [rollbar/rollbar.js#122]
I have rollbar JS code in <head> of my website, this code is before all other JS scripts.
But time to time it sends request:
Remote Address:37.58.71.74:443
Request URL:https://api.rollbar.com/api/1/item/
Request Method:POST
Status Code:429 Too Many Requests
with the response:
{"err": 1, "message": "Over free plan monthly limit. Project id 16132 access token c38d35ca16bb4f749496465e5f932464."}
But that blocks all other requests, so my page is not working.

I know that I should concider changing monthly plan, but before I do that - how to change this request to asynchronous request to not block other server requests on my webpage?

**Comment by brianr** [comment]
Hi @marcinpl87 - that request should be happening asynchronously already. Are you sure it's blocking other requests from being made?

**Comment by marcinpl87** [comment]
you're right. It's happening asynchronously. My bad... closing this.
