### ISSUE TITLE
Allow the person to be sent with each error

### ISSUE THREAD

**Issue by Koblaid** [rollbar/rollbar.js#123]
I'd like to set the person to be sent along with the error in Rollbar.error() instead of in Rollbar.configure().

Is this already possible? I've tried 

```
Rollbar.error(exception, { person: { id: 111 } })
```
and
```
Rollbar.error(exception, { payload: person: { id: 111 } }})
```
but with no success.

**Comment by brianr** [comment]
Definitely possible! Try this:

```
Rollbar.scope({person: {id: 111}}).error(exception);
```

You can set other payload-level options the same way.
