### ISSUE TITLE
Remove submodule for TraceKit

### ISSUE THREAD

**Issue by Crisfole** [rollbar/rollbar.js#132]
A client with [Demeteorizer](https://github.com/onmodulus/demeteorizer/) is having trouble. The submodule is being installed as an npm dependency, which isn't legal since it's upper case.

**Comment by lehresman** [comment]
We replaced TraceKit with error-stack-parser in v1.3.0, but it looks like the submodule is still present.  Should be easy to remove with no consequence, but I wanted to confirm with @coryvirok and @rokob first.

Any reason not to remove these lines?
https://github.com/rollbar/rollbar.js/blob/e9748666563b9d02cc110d2907cf3103b2b48506/.gitmodules#L1-L3

I do not see any other references to TraceKit in the repo.
