### ISSUE TITLE
v1.6.0 Snippet contains Broken Path (404)

### ISSUE THREAD

**Issue by EnigmaSolved** [rollbar/rollbar.js#133]
The newest snippet ( https://github.com/rollbar/rollbar.js/blob/master/dist/rollbar.snippet.js ) contains a path that results in a `404`:
https://d37gvrvc0wt4s1.cloudfront.net/js/v1.6/rollbar.min.js

I discovered this because I was wanting to upgrade to the newer version to fix some wonky Rollbar errors (eg, regarding IE 8, and some other errors that have only show since upgrading to 1.5.0).

**Comment by coryvirok** [comment]
Hi @EnigmaSolved.

I'm deploying a fix now. Sorry about that.

**Comment by coryvirok** [comment]
Fix is deployed, (https://rollbar.com/js/v1.6/rollbar.min.js) and the CDN cache is being invalidated now (https://d37gvrvc0wt4s1.cloudfront.net/js/v1.6/rollbar.min.js). It should be finished in the next 10 mins.

**Comment by EnigmaSolved** [comment]
Great! Many thanks! :)

**Comment by coryvirok** [comment]
I just verified that the CDN is serving the new code.

**Comment by EnigmaSolved** [comment]
Awesome! Yeah, I meant to indicate that I'd checked that and everything looks good now. Thanks for the fast fix!
