### ISSUE TITLE
Is hostWhiteList actually working?

### ISSUE THREAD

**Issue by davidmatas** [rollbar/rollbar.js#136]
Hi! 

I don't see any examples in docs and I wanted to know if `hostWhiteList` option can be used and how it does. Does it take in account the fact that `body.trace.frames` has not url format when sourcemap is enabled?

**Comment by Crisfole** [comment]
`hostWhiteList` gets applied on the client, long before source maps are applied.  The option works nicely and takes an array of strings, each of which gets compiled as a Regexp and then compared against the domain portion of each filename in the stack trace.  If any of them contain one of the white listed domains the item gets sent. If none of them are in the white list it doesn't get sent. (Presumably those items come from an extension, or is purely from plugin code).

**Comment by davidmatas** [comment]
So, I guess it is something you can also make with `checkIgnore` option, or they differ in some way?

**Comment by Crisfole** [comment]
This is just a shortcut for `checkIgnore`, correct.

**Comment by davidmatas** [comment]
And can also be defined together? I mean first applying a hostWhiteList filter, then ignoring something from your own white list.

**Comment by piotrd** [comment]
Source code to the rescue!
`checkIgnore` is called in line 752 (https://github.com/rollbar/rollbar.js/blob/master/dist/rollbar.js#L752), and then, in line 762 (https://github.com/rollbar/rollbar.js/blob/master/dist/rollbar.js#L762) `hostWhiteList` is checked. This happens in the same method (`_enqueuePayload `), which enqueues events for sending to Rollbar, which in short means that you can 'define' both methods and both will be taken into account.

**Comment by davidmatas** [comment]
Great, thanks!
