### ISSUE TITLE
Publish 1.6 on NPM

### ISSUE THREAD

**Issue by dozoisch** [rollbar/rollbar.js#139]
Hey guys :)

I really enjoy the new NPM package, but it seems like 1.6 releases haven't been published to npm!

![image](https://cloud.githubusercontent.com/assets/4422516/10093658/879b6208-6323-11e5-9760-03b5cf910e7c.png)

**Comment by coryvirok** [comment]
Thanks for reporting this! I'll get the latest version up ASAP.

**Comment by coryvirok** [comment]
Published!

**Comment by dozoisch** [comment]
@coryvirok same with 1.7 :)

**Comment by coryvirok** [comment]
Thanks for the reminder! 😊
