### ISSUE TITLE
Getting TypeError: undefined is not an object (evaluating 'n.length') in all browsers

### ISSUE THREAD

**Issue by ri-nat** [rollbar/rollbar.js#140]
Line: `rollbar.min.js:534` (1.6, latest)
This error is appears in browser console after loading any page of my application when I'm using rollbar.

Is this my mistake (configuration problem, another script error, something else...) or rollbar issue?

**Comment by Crisfole** [comment]
Hi Rinat,  Any chance you can send a link to one of your pages that demonstrates the error, or perhaps paste in a stack trace?

**Comment by ri-nat** [comment]
Hi, Crisfole!

I've discovered that this was a problem in jQuery plugin. Stack trace in Safari is so poor... Closing it. Thanks!
