### ISSUE TITLE
Document the effects of async

### ISSUE THREAD

**Issue by lookfirst** [rollbar/rollbar.js#144]
So... does {async: true} mean that if something else on the page errors out before the rollbar.min.js is loaded that it won't get reported?

**Comment by brianr** [comment]
Good question. If you're using our standard snippet and putting it at the top of your `<head>`, then any JS errors *should* be reported, even if they happen before rollbar.min.js loads, as long as the page is open long enough for rollbar.min.js to load and the ajax request to api.rollbar.com to be made.

Are you seeing other behavior?

**Comment by lookfirst** [comment]
I haven't upgraded yet. Just want to be sure of what is happening before I do so.

**Comment by brianr** [comment]
Closing as I think this is answered; please re-open if not. Thanks!
