### ISSUE TITLE
Code licence?

### ISSUE THREAD

**Issue by Odaeus** [rollbar/rollbar.js#145]
Hi,

I can't seem to find a LICENSE file or copyright equivalent in this repository. It would be great to know if you wish to retain the copyright or put it under an open source licence?

**Comment by brianr** [comment]
Hi @Odaeus - thanks for pointing this out; the license file does seem to be missing. It's intended to be under the MIT/similar license like our other client libraries. We'll get this added.

**Comment by coryvirok** [comment]
Thanks again - added https://github.com/rollbar/rollbar.js/commit/6a0639681e6e66e84d2846db4b233da70f503399
