### ISSUE TITLE
Is there a reason for the bower package to have 4.1 MB?

### ISSUE THREAD

**Issue by jirihelmich** [rollbar/rollbar.js#149]
It should, IMHO, be as small as possible to enable quick build on integration servers and different automated environments. 4.1MB is just huge. Unarchived jquery bower package has 800 kB, for instance.

**Comment by lparry** [comment]
I was just looking into why it's so big myself. in the `release` directory it seems to include every release ever. Not sure if this is an oversight or intentional, but it doesn't seem right to me

**Comment by corps** [comment]
Is this issue outdated?  I just took a peak at the bower install directory for rollbar.js, and the total size was 1.1mb, it seems that the release directory is no longer included.  It's possible to reduce this size a bit further, but the gains will be diminished, and would only involve removing optionally useful things (like various loader versions of the build, src/ directory).

One other possibility that might be more generally useful would be to introduce a separately packaged "rollbarjs-ci" that only packages the bare minimums to execute in the common environments (say, removing the src/, snippets, documentation, etc), but it's not clear if the extra complexity is warranted.  Let me know you guys thoughts.

**Comment by brianr** [comment]
@corps Looking at [bower.json](https://github.com/rollbar/rollbar.js/blob/master/bower.json), it looks like we may really only need to have one file in it, `dist/rollbar.umd.js`. If that's correct, then it seems we could make the package nice and small - down to ~80kb.

**Comment by corps** [comment]
Sure thing.  We should also consider announcing such a change as breaking, however, since any bower consumer who was relying on the presence of source maps, or other specific files, would suddenly break.

**Comment by brianr** [comment]
Hm, good point.

@lparry and @jirihelmich , how does the current package size work for you? Are we still unusually huge or are we into the normal zone? Would removing the `src/` folder and the other files in `dist/` break anything for you?

**Comment by jirihelmich** [comment]
We use just rollbar.min.js from dist folder of that package to reference it into our application.
