### ISSUE TITLE
TypeError: Cannot read property 'belongsToShim' of null

### ISSUE THREAD

**Issue by freeall** [rollbar/rollbar.js#155]
I get this error in the new version, around here https://github.com/rollbar/rollbar.js/blob/ca5d438bc62e8e41c0455d4060923d06b2344a68/dist/rollbar.nojson.js#L155

I think you should change this line to `else if (window.onerror && !window.onerror.belongsToShim) {`

**Comment by jondeandres** [comment]
@freeall you are right, we'll release a new version today.

thanks for the report.

**Comment by freeall** [comment]
Cool, thanks!

**Comment by jondeandres** [comment]
@freeall we've release v1.7.5. We hope this works fine for you.

Thanks for everything.

**Comment by freeall** [comment]
:+1:
