### ISSUE TITLE
window.onerror should use exception stacktrace when available

### ISSUE THREAD

**Issue by oadam** [rollbar/rollbar.js#158]
According to this [stackoverflow answer](http://stackoverflow.com/a/19171250/436792), both firefox and chrome provide the original `Error` object as a 5th argument to the `window.onerror` handler. The exception stacktrace can be extracted when the argument is present.

I checked rollbar.js code and I am under the impression that this info is not used at the moment.

**Comment by oadam** [comment]
Oops.
The doc on https://rollbar.com/docs/source-maps/ seems to says that uncaught error handled by rollbar do include stacktraces in newest browsers.
If so, please feel free to close this

**Comment by oadam** [comment]
Ok after rereading the code I see that the fifth argument is correctly processes.
Cheers !

**Comment by brianr** [comment]
Thanks for looking out, @oadam :) Yep, rollbar.js does gather the fifth arg, and it makes debugging javascript errors so so much easier.

**Comment by antoinerousseau** [comment]
could it be that this doesn't work in Chrome versions 47 and older? I'm getting a lot of `TypeError: 'undefined' is not a function` without stacktrace but can't determine their origin... the only recurrent thing is that they happen on Windows 7 and in Chrome 32, 36 and 47...
