### ISSUE TITLE
source_map_enabled doesn't work

### ISSUE THREAD

**Issue by vvscode** [rollbar/rollbar.js#167]
I've initialized Rollbar with config
```
{
  accessToken: 'xxx',
  captureUncaught: true,
  payload: {
    environment: 'production',
    client: {
      javascript: {
        source_map_enabled: true,
        code_version: "some version string, such as a version number or git sha",
        // Optionally have Rollbar guess which frames the error was thrown from
        // when the browser does not provide line and column numbers.
        guess_uncaught_frames: true
      }
    }
}
```

And got client with next options
![result settings](https://www.dropbox.com/s/j401yz8bczgn0pk/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-12-21%2011.59.36.jpg?dl=1)

But at rollbar panel I still get trace without sourcemaps

PS Also please describe where I can find code for this part of functionality, cause I even can't debug to find what's wrong.

Thx in advance

**Comment by coryvirok** [comment]
Hi @vvscode,

Source mapping works by using the `code_version` in the occurrence and matching that to the version of a source map file and running the source mapping process. Source maps can either be uploaded using our API or if the JS file in a frame of a JS stack trace has a `sourceMappingURL` specified, we will download it.

I'd recommend you try uploading a source map for your project with the git SHA of the source file. Then, use that same git SHA in your Rollbar config, (in place of "some version string, such as a version number or git sha".)

You've probably already read through this, but here are the instructions for getting this set up:
https://rollbar.com/docs/source-maps/

You can see a list of all of the source maps that have been uploaded, (or downloaded) for your project in your settings page, here: https://rollbar.com/:account/:project/settings/source_maps/

If you email support@rollbar.com we can help you debug this.

**Comment by charles-rumley** [comment]
I noticed Rollbar truncates `code_version` to 7 characters when storing error occurences. A source map is uploaded with version (Full Git SHA) `cad136d7e16ebdf6edc31722f47dd5dfe291ffaf`, and client-side Rollbar configuration contains `client.javascript.code_version=cad136d7e16ebdf6edc31722f47dd5dfe291ffaf`but viewing an error occurrence in the Rollbar console shows `client.javascript.code_version=cad136d`.

**Comment by Crisfole** [comment]
@charles-rumley: the code version isn't truncated! We just truncate it for display purposes. If you click `Raw JSON` on the bottom of an occurrence page you'll see that the data is still intact.

**Comment by charles-rumley** [comment]
Good call, I didn't notice that. What purpose does truncating it for display serve?

**Comment by dlsteuer** [comment]
@charles-rumley we truncate if it's recognized as a git sha1 hash, similar to how you can reference a git commit for it's short hash.

**Comment by wildskyf** [comment]
Hi @dlsteuer 

I just generate source map for my rails map, and I have known that I need to specify the code_version attribute after I read the docs. And you suggested that it is better to use git sha as the value of code_version.

Should I need to update code_version with git sha as long as I update any js file in my project? Or I just need to update code_version when I update the config file?

**Comment by wildskyf** [comment]
(this question is not just about rollbar.js, but I can't find a repo called rollbar/ama, maybe you could create one?)

**Comment by rivkahstandig3636** [comment]
Hi @wildskyf, you can always email us at support@rollbar.com. I'm not sure I understand what you're asking. The code_version of the source map files you upload needs to match the code_version in your JS config.
