### ISSUE TITLE
UMD '.error' does not exist.

### ISSUE THREAD

**Issue by mderrick** [rollbar/rollbar.js#169]
I think there may be an issue with the UMD build (or I'm just misusing it).

Following the [Webpack example](https://github.com/rollbar/rollbar.js/tree/master/examples/webpack) I can do:

```javascript
import Rollbar from 'rollbar-browser';
Rollbar.init({}); // init exists
Rollbar.error(); // error does not
```

I can however do `window.Rollbar.error()` but I would really prefer to use the exported object. Am I missing something out or is this expected?

Thanks

**Comment by coryvirok** [comment]
Hi @mderrick,

The `init()` method will return the Rollbar instance when included this way.

Try this:

```js
import rollbar from 'rollbar-browser';
const Rollbar = rollbar.init({});
Rollbar.error('Hello world');
```

**Comment by mderrick** [comment]
Ah! My bad. I didn't read the example thoroughly enough. Thank you!
