### ISSUE TITLE
Reason for fetching error-stack-parser from git?

### ISSUE THREAD

**Issue by tume** [rollbar/rollbar.js#170]
We don't have git installed in our servers where we are doing our app building and would like to keep it that way.

Is there any specific reasoning behind depending on master version on error-stack-parser instead of specific version that could be fetched from npmjs?

**Comment by coryvirok** [comment]
Funny that you mention this. error-stack-parser just removed their polyfills which was the reason for the fork. 

https://github.com/rollbar/error-stack-parser/commit/3e75313177fe6f619436a48d701886ab85dea995#commitcomment-15231423

I'll get this tested and merged today.

**Comment by coryvirok** [comment]
Done - https://github.com/rollbar/rollbar.js/blob/master/CHANGELOG.md
