### ISSUE TITLE
Possible regression between 1.7 and 1.8 about Notifier.configure

### ISSUE THREAD

**Issue by dozoisch** [rollbar/rollbar.js#172]
Hello guys!

I'm using rollbar using the UMD build the following way

```js
// my core rollbar folder
let RB;
if (__NODE_ENV__ !== 'production') {
  require('rollbar-browser/dist/rollbar.umd.nojson').init({
    accessToken: ACCESS_TOKEN,
    captureUncaught: true,
    uncaughtErrorLevel: 'critical',
    payload: {
      environment: __NODE_ENV__,
      version: __VERSION__,
      client: {
        javascript: {
          source_map_enabled: !!__BUILD_TOKEN__,
          code_version: __BUILD_TOKEN__,
          guess_uncaught_frames: true,
        },
      },
    },
  });
  RB = window.Rollbar;
  console.log(`[Rollbar] error logging enabled! env: ${__NODE_ENV__}`); // eslint-disable-line no-console
}  else { /* ... */ }

export default RB;
```

So Im setting a couple of payload variable right away.

And then, in one of my store actions I would do the following 

```js
    rollbar.configure({ payload: { person: { id: payload.authUser } } });
````
To set the userId in the payload.

With 1.8, all my items are now version-less. 
I've logged in the Notifier 

```js
NotifierPrototype.configure = _wrapNotifierFn(function(options) {
  // TODO(cory): only allow non-payload keys that we understand

  // Make a copy of the options object for this notifier
  var newOptionsCopy = extend(true, {}, options);
  console.log('ROLLBAR/before:', this.options, new);
  extend(false, this.options, newOptionsCopy);
  console.log('ROLLBAR/after:', this.options)
  this.global(newOptionsCopy);
});
```

And the `extend` is in deep overriding (false means shallow not deep).

I'm wondering if that was the intended behavior? And if yes, what would be the recommended way of adding a value the payload option dynamically ? 

I could make my own configure function that makes sure to merge my default config with the one provided by the action, or I could retrieve the current "payload" config and merge it.

**Comment by Crisfole** [comment]
Hey there! Thanks for pointing this out. We have a fix in place for this in the latest version of rollbarjs!
