### ISSUE TITLE
Some parts of  _rollbarConfig ignored in bower example?

### ISSUE THREAD

**Issue by InstanceOfMichael** [rollbar/rollbar.js#173]
```
<head>
  <script>
    _rollbarConfig = {
      accessToken: "ACCESS_TOKEN",
      captureUncaught: true,
      payload: {
         environment: "test"
      }
    };
  </script>
</head>
```

It seems that ``_rollbarConfig.payload.environment`` and any variation of ``_rollbarConfig.*.(person|user)`` are ignored in the bower example and must be manually set via ``Rollbar.config()``

**Comment by dlsteuer** [comment]
I added some additional configuration options to the bower example in #202
