### ISSUE TITLE
Readme rollbar code is outdated

### ISSUE THREAD

**Issue by albertyw** [rollbar/rollbar.js#177]
The minified rollbar.js in the readme (https://github.com/rollbar/rollbar.js/blame/master/README.md#L24) doesn't match the code in the dist directory (https://github.com/rollbar/rollbar.js/blob/master/dist/rollbar.min.js)

**Comment by Crisfole** [comment]
Hi @albertyw Rollbar.js is different from the snippet. The snippet dynamically loads rollbar.js for you. They're not intended to be identical.

Are you having trouble getting started with Rollbar?

**Comment by coryvirok** [comment]
Closing this but if you have anymore questions, @albertyw please let us know!
