### ISSUE TITLE
Global reporting does not work?

### ISSUE THREAD

**Issue by netzaffin** [rollbar/rollbar.js#181]
Hi,

I'm very fine with rollbar, but I stumbled upon one issue. I made a mistake in my app, so in some circumstances a required JS file is not loaded (<script src="..."></script> does not exists in the DOM). Of cause, something will fail:

Console says: _Error: [ng:areq] Argument 'CreateCtrl' is not a function, got undefined_

I'm not sure why, but this is not send to my rollbar account (while many other errors are sent). Is there anything I can do? Rollbar is defined in the head, all other scripts at the end of page...

Kind regards,
Patrick

**Comment by brianr** [comment]
Hi @netzaffin - that looks like an Angular.js error coming from the Angular.js exception handler. To send those errors to Rollbar, you'll need to add a little more instrumentation. Fortunately ng-rollbar can take care of this for you: https://github.com/tandibar/ng-rollbar

Take a look there; I *think* that will do what you need. If not, please reopen this issue. Thanks!
