### ISSUE TITLE
Disable Rollbar.js when adblock/ghostery

### ISSUE THREAD

**Issue by fform** [rollbar/rollbar.js#182]
I get a lot of errors from libs though my site when users adblock or browser extension is ripping out javascript. 

Is there an option to just not send events from those users? Does anyone have a solution for this scenario? I get that I could more safely call these libs but this site is at a stage where it's not worth implementing a bunch of re-writing when I could just flip a flag to ignore clients who are intentionally modifying their stack.

**Comment by piotrd** [comment]
One option is a function called `checkIgnore` (https://rollbar.com/docs/filter-or-ignore-errors-from-bots/), which would allow you to ignore certain errors from being sent to Rollbar. Detect if adblocker is active and if so, return `true` from it.

**Comment by Crisfole** [comment]
Hey @fform, @piotrd is right, `checkIgnore` would do the trick. You could also try simply disabling the error reporting when you notice a missing script:

    rollbar.configure({enabled: false});
