### ISSUE TITLE
error report does not include the custom object when it is an array

### ISSUE THREAD

**Issue by mattdrees** [rollbar/rollbar.js#188]
When sending an object, like this:
```js
Rollbar.error("trying to send an object", {"one": 1, "two": 2, "three": 3});
```
the `body` sent in the report contains the object:
```
"body": {
  "message": {
    "body": "trying to send an object", 
    "extra": {
      "three": 3, 
      "two": 2, 
      "one": 1
    }
  }
}
```

However, when sending an array, like this:
```js
Rollbar.error("trying to send an array", [1,2,3]);
```
the `body` sent in the report doesn't contain the array; rather it is silently ignored:
```
"body": {
  "message": {
    "body": "trying to send an array"
  }
}
```

I think this is due to `_getLogArgs` failing to account for when `argT` is 'array'.

**Comment by coryvirok** [comment]
@mattdrees this should be fixed in the latest rollbar.js release. If you are still seeing this please re-open this issue.

**Comment by mattdrees** [comment]
thanks @coryvirok , @corps!
