### ISSUE TITLE
Rollbar.configure is not a function

### ISSUE THREAD

**Issue by gfarrell** [rollbar/rollbar.js#189]
`Rollbar.configure` causes "is not a function" errors. I'm getting it as:

```
import Rollbar from "rollbar-browser";
```

`Rollbar.init()` has always worked for us.

**Comment by Crisfole** [comment]
Hey there, any chance you have a rollbar item to go with it? (A uuid would serve as a link i could use to look at it, but would be secure to post here). I'm wondering if it's a specific browser. I just heard about something similar in the support queue, but it was only for IE9. Trying to track down the issue.

**Comment by gfarrell** [comment]
Well, the occurrence # is 12680914812 if that helps.

This was on latest Chrome.

**Comment by tinovyatkin** [comment]
Similar error with IE10
![bs_win8_ie_10 0](https://cloud.githubusercontent.com/assets/5350898/17953440/4fd7ce9e-6a41-11e6-981c-21a5eeb6620a.jpg)

**Comment by jahed** [comment]
Might have misunderstood the problem here but `Rollbar.configure` is only available on the initialised Rollbar instance.

i.e.

```js
import RollbarFactory from 'rollbar-browser'
RollbarFactory.configure(config) // Doesn't work

const Rollbar = RollbarFactory.init(config)
Rollbar.configure(config) // Works
```

I don't think this is an issue. Though it's probably worth being clear on what `rollbar-browser` exports by default in the docs.

**Comment by coryvirok** [comment]
Going to close this one since this is working the way we intend.

**Comment by lmj0011** [comment]
https://github.com/rollbar/rollbar.js/issues/189#issuecomment-244551622

this ended up helping me get rollbar working on the client for adonuxt.js

I agree the docs should mention this
