### ISSUE TITLE
Is it possible to disable cookie for rollbar.com?

### ISSUE THREAD

**Issue by Zhomart** [rollbar/rollbar.js#197]
I don't want my web page that has rollbar.js on it to store cookies from other resources, including rollbar.com. Is it possible to disable or get around it?

**Comment by coryvirok** [comment]
Hi Zhomart,

We shouldn't be setting cookies via the rollbar.js endpoint. Can you point me to a publicly accessible page where I can see this happening?

Thanks

**Comment by Zhomart** [comment]
Hello @coryvirok ,

You're right, I tried on my page manually reporting to rollbar using `Rollbar.info` and chrome doesn't show any cookies from rollbar.com.

I got this report other person who claims it stores cookies from rollbar.com because their security personnel told him. And I thought that chrome doesn't show cookies from other resources.

I've looked at response headers and there is no set-cookie header from rollbar.com. And then I thought there is special cases when rollbar.com sets cookies on ajax API requests from rollbar.js to store ids,  tokens, session ids or something else.

I'll close this issue as it's more related to rollbar.com api than rollbar.js.

By any change, do you know when api.rollbar.com could send set-cookie headers?

**Comment by coryvirok** [comment]
api.rollbar.com shouldn't ever be setting cookies and rollbar.js should only be communicating with api.rollbar.com. I'll look into your question a bit more and if you get anymore info please feel free to update this ticket or send an email to support@rollbar.com and link this issue.
