### ISSUE TITLE
Authentication required

### ISSUE THREAD

**Issue by cyril-sf** [rollbar/rollbar.js#198]
We're running Rollbar 1.7.1 in production and one of our clients saw this modal.

![screen shot 2016-04-20 at 1 01 21 pm](https://cloud.githubusercontent.com/assets/743977/14688536/eb234b06-06f7-11e6-80da-870148cd29ab.png)

Why is this happening?

**Comment by thangdinh** [comment]
If it is one client, could we ask them to clear the chrome? 
https://productforums.google.com/forum/#!topic/chrome/8AvoE5yotUs

**Comment by coryvirok** [comment]
Hi @cyril-sf,

Yikes! That should definitely *not* be happening. We are looking into it.

**Comment by cyril-sf** [comment]
We don't do any error handling in case Rollbar doesn't initialize/configure properly. I looked (too?) quickly at the doc and didn't see anything there.

Could we do something to detect such a problem and to prevent us from calling `Rollbar.warn` or `Rollbar.error` in that case?

**Comment by Crisfole** [comment]
We just received notice from your co-worker through support@rollbar.com that this was a universal problem (not just on Rollbar enabled sites) for that client. Thanks for letting us know. If it turns out to be a Rollbar issue please get back to us!
