### ISSUE TITLE
rollbar module fails to load when using Domino js

### ISSUE THREAD

**Issue by lukebayes** [rollbar/rollbar.js#204]
The console-polyfill library does not work properly according to spec as it always attempts to write to the read-only "console" property on window.

I have put together a pull request for them, but in the interim, you might want to fork from the PR branch and inline the fix.

  https://github.com/paulmillr/console-polyfill/pull/25

**Comment by rokob** [comment]
The mentioned PR for console-polyfill has been merged upstream, looks like we just need to ensure that we are using an up to date version of said library.

**Comment by lehresman** [comment]
Thanks @lukebayes.  I've submitted a PR that updates the rollbar.js dependency for console-polyfill to a version that includes your fix.
