### ISSUE TITLE
Object.create introduced in version 1.8 doesn't work on ie8

### ISSUE THREAD

**Issue by ctrager** [rollbar/rollbar.js#205]
Object.create not supported in IE8.  Was not in rollbar.js 1.7, but is in rollbar.js 1.8
![screen shot 2016-06-03 at 5 24 14 am](https://cloud.githubusercontent.com/assets/61188/15776267/34a529ea-294c-11e6-970d-0026d7d506a9.png)

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create

**Comment by robtarr** [comment]
Is there any movement on this? I just picked up a project that is loading v1.9 via https://rubygems.org/gems/rollbar/versions/2.14.0, and it is causing errors in IE8 as well.

Is there fix for this?
