### ISSUE TITLE
Reengagement emails from Ivan bounce

### ISSUE THREAD

**Issue by dandv** [rollbar/rollbar.js#212]
Hey guys,

I've replied to two re-engagement emails from ivan@rollbar.com but they both bounced.

**Comment by brianr** [comment]
Huh, that's no good. Thanks @dandv for the heads-up. You can try me at brian@rollbar.com

**Comment by dandv** [comment]
My bad - Gmail was automatically selecting a different From address when replying, which no longer works. All's good!
