### ISSUE TITLE
Beacon API

### ISSUE THREAD

**Issue by tinovyatkin** [rollbar/rollbar.js#213]
Why don't you use navigator.sendBeacon for reporting? Supported by Edge, Firefox and Chrome its way bigger user coverage that XDomainRequest that you do have implemented, and reliability (specially on unload use cases) is much higher than XHR.
Will you accept Pull Request for it? I can do it, I think...

**Comment by tinovyatkin** [comment]
Just submitter pull request #214 to close this if you will consider.

**Comment by tinovyatkin** [comment]
Just closed my pull request as it handled HTTP headers incorrectly and I found a way to use benefits of navigator.sendBeacon (such as messages delivery on unload and native queuing) using following code:
https://gist.github.com/tinovyatkin/04af5dd71496aa9367cb034de1b3eb16

**Comment by brianr** [comment]
OK, thanks @tinovyatkin for keeping us in the loop! We have a task we're tracking internally for this and hope to get to it in the near future.

**Comment by coryvirok** [comment]
@tinovyatkin looks like this has fallen through the cracks for us. Sorry about that. If you are still interested, we would love a PR.
