### ISSUE TITLE
Support Regex in ignoredMessages

### ISSUE THREAD

**Issue by jahed** [rollbar/rollbar.js#216]
It would be nice if ignoredMessages supported regular expressions so we don't have to be so specific in the messages we ignore.

If this feature does already exist, it's worth updating the docs on it: https://rollbar.com/docs/notifier/rollbar.js/

**Comment by Crisfole** [comment]
Last I checked ignoredMessages was a strict match. For anything more complex you can use the checkIgnore function documented here: https://rollbar.com/docs/notifier/rollbar.js/configuration/#notifier

**Comment by andrewchilds** [comment]
According to https://github.com/rollbar/rollbar.js/blob/b04781118f5882095aaa2d5ef3b3cf068fe4372e/src/notifier.js#L509-L517, ignoredMessage strings get parsed as a regex and have for a while.

```js
len = ignoredMessages.length;
for (i = 0; i < len; i++) {
  rIgnoredMessage = new RegExp(ignoredMessages[i], 'gi');
  messageIsIgnored = rIgnoredMessage.test(exceptionMessage);

  if (messageIsIgnored) {
    break;
  }
}
```

I also just verified I could use a regex for ignoredMessages using v1.9.1:

```js
Rollbar.options.ignoredMessages = ['test[0-9]{3}']

// Logged:
window.onerror("test", window.location.href)
window.onerror("test12", window.location.href)

// Ignored:
window.onerror("test123", window.location.href)
window.onerror("test12345", window.location.href)
```
