### ISSUE TITLE
user_ip = $remote_ip is being replaced with 10.61.151.100 in many cases

### ISSUE THREAD

**Issue by rarkins** [rollbar/rollbar.js#219]
I just discovered that dozens of Rollbar.js occurrences every day are being attributed to 10.61.151.100 in the Rollbar UI. These are happening at all times of day and across a variety of devices, browsers, and operating system versions. i.e. extremely unlikely that it's the same user. This IP address has been reported with a significant percentage of errors since the day I deployed Rollbar.js.

Interestingly, if you google for `site:rollbar.com 10.61.151.100` you will find a lot on the Rollbar demo account.

My best guess is that this is *not* caused by the Rollbar.js library but instead is a server-side bug that's rewriting `$remote_ip` incorrectly and is somehow defaulting to `10.61.151.100`, or maybe that's a CDN/proxy in front of your API backend that's not setting `X-Forwarded-*` headers properly?

Cc @brianr @coryvirok

**Comment by brianr** [comment]
Hi @rarkins - this is an issue on our side. We're working on a fix.

**Comment by brianr** [comment]
This should be fixed now (for all but a few laggard clients with an old DNS entry cached).
