### ISSUE TITLE
Rollbar doesn't handle `throw "error"` well

### ISSUE THREAD

**Issue by iafonov** [rollbar/rollbar.js#220]
Rollbar breaks when it tries to process `throw "String error"`. It tries to get stack trace - hovewer error is not wrapped into object.

[Codepen](http://codepen.io/anon/pen/ZpBrBr) - please add `accessToken` in configuration

<img width="737" alt="screenshot 2016-09-21 13 40 20" src="https://cloud.githubusercontent.com/assets/32007/18707952/0926478e-8001-11e6-8a52-620e651da6bc.png">

Expected: rollbar reports error (even without stracktrace)

**Comment by jondeandres** [comment]
@iafonov did you try `throw new Error('String error')`?

**Comment by iafonov** [comment]
Yes it works fine with wrapped errors. We need it to support `throw "test"` constructions too, it looks like perfectly legal js error that should be reported. (I understand that stack trace would not be available)

**Comment by brianr** [comment]
Thanks @iafonov - agreed, we should at least handle `throw "test"` in a reasonable way. We'll get this on our todo list. Also very open to a PR that fixes this.

**Comment by coryvirok** [comment]
Hrm, this used to work.

**Comment by iafonov** [comment]
Any updates?

> Also very open to a PR that fixes this

We are kind of paying for using rollbar :wink:

**Comment by coryvirok** [comment]
Yes. I'm going to get a new release out today!

**Comment by coryvirok** [comment]
Should be fixed in v1.9.2 - https://github.com/rollbar/rollbar.js/issues/220

**Comment by brianr** [comment]
@iafonov Have you had a chance to verify this in the latest version?

I'm going to close this out but please reopen if it's not fixed.
