### ISSUE TITLE
How can i use with React + Webpack?

### ISSUE THREAD

**Issue by BrunoQuaresma** [rollbar/rollbar.js#221]
It is possible integrate Rollbar with React + Webpack?

**Comment by rivkahstandig3636** [comment]
It should be; what issues are you having?

**Comment by hakunin** [comment]
Here is a reference on how to do it:
https://github.com/rollbar/rollbar.js/tree/master/examples/webpack

But its outdated, here is what I am doing:
```
  var rollbarConfig = {
    accessToken: YOUR_TOKEN,
    captureUncaught: true,
    //...
  };

  var Rollbar = require('rollbar-browser');
  Rollbar.init(rollbarConfig);
```

**Comment by josephsiefers** [comment]
I'm having trouble capturing React errors. Statements like the following are working:
`Rollbar.error('Problem calling foo()', e);`
`window.onerror("TestRollbarError: testing window.onerror", window.location.href)`

However, I see errors like the following in my console that are not appearing in Rollbar:
![image](https://cloud.githubusercontent.com/assets/1895065/24581222/6be2d9fc-16e5-11e7-916e-828788f8d8f1.png)
