### ISSUE TITLE
extractIp logic is broken

### ISSUE THREAD

**Issue by modosc** [rollbar/rollbar.js#227]
all of our exceptions show `request.user_ip` to be a non-routable address - this is because external connections bounce through several layers of AWS infrastructure. we can get the correct client ip address with [request-ip](https://www.npmjs.com/package/request-ip) though - would you be open to a pr which uses this module to replace `extractIp()`? alternately would it be possible to make the ip address attribute configurable (`request-ip` places its calculated result in `req.clientIp`)? happy to do either.

**Comment by lehresman** [comment]
I believe this has been filed under the wrong notifier.  This seems to be related to the node notifier.  Closing this issue, but moved it here:  https://github.com/rollbar/node_rollbar/issues/104

**Comment by modosc** [comment]
sorry about that, thanks!
