### ISSUE TITLE
Support for isomorphic react applications

### ISSUE THREAD

**Issue by MacsDickinson** [rollbar/rollbar.js#228]
There are currently two javascript clients for rollbar, [node_rollbar](https://github.com/rollbar/node_rollbar/) and [rollbar.js](https://github.com/rollbar/rollbar.js).

Neither of these libraries work for an isomorphic react application, node_rollbar has a [CORS issue](https://github.com/rollbar/node_rollbar/issues/93) when used on the client and rollbar.js understandably throws an error as window is not defined when run on the server.

Is there a suggested implementation for isomorphic react applications?

**Comment by rokob** [comment]
I am working on making this library actually work on both the server and in the browser. In doing so, I will make sure we have a documented way to use it in an isomorphic application. The tracking issue for this work is: https://github.com/rollbar/rollbar.js/issues/248

**Comment by Aryk** [comment]
Thanks for working on this @rokob. Just curious, what's the current best approach to using rollbar in isomorphic applications until the PR is approved and merged?

**Comment by jonikorpi** [comment]
The new version seems to be out now and looking at the docs/examples I honestly have no idea how to use it with something like create-react-app or next.js.

I'll add the way I used the _old_ rollbar-browser library here, for reference. I'm guessing it's at least vaguely similar to how others have used it. 

What should replace this code when using the new version?

```
if (typeof window !== "undefined" && !window.Rollbar) {
  window.Rollbar = require("rollbar-browser");
  window.Rollbar.init({
    accessToken: "…",
    captureUncaught: true,
    captureUnhandledRejections: true,
    payload: {
      environment: env,
    },
  });
}
```

**Comment by rokob** [comment]
```
if (typeof window !== "undefined" && !window.rollbar) {
  window.rollbar = require("rollbar");
  window.Rollbar = new window.rollbar({
    accessToken: "…",
    captureUncaught: true,
    captureUnhandledRejections: true,
    payload: {
      environment: env,
    },
  });
}
```

**Comment by Aryk** [comment]
Great, thanks!
