### ISSUE TITLE
Rollbar reports break CSP

### ISSUE THREAD

**Issue by toddjcrane** [rollbar/rollbar.js#230]
On line 1, column 27491 of your rollbar.min.js hosted on cloudfront, you use an eval() tag. In order to allow this, one must allow 'unsafe-eval' in Content-Security-Policy rendering it effectively useless. 

The advantages of CSP are well documented as are the security risks of not using it. 

Do you have another rollbar.js version without this and/or can you refactor your code to not use this, or at least have an option for those of that have CSP enabled?

**Comment by brianr** [comment]
Hi @toddjcrane - we sure do. You'll want to use the 'nojson' distribution. In your `_rollbarConfig`, just set:

```
_rollbarConfig = {
  accessToken: "your token...",
  rollbarJsUrl: 'https://d37gvrvc0wt4s1.cloudfront.net/js/v1.9/rollbar.nojson.min.js',
  // ... other params as before...
}
```
