### ISSUE TITLE
add possibility to filter issues came from foreign scripts

### ISSUE THREAD

**Issue by eshikerya** [rollbar/rollbar.js#234]
Last few month I'm hunting for flooding occurrences related to foreign scripts, like:
* Intercom IE/EDGE issue (about 3000 occurrences for last 5 days)
* Mecach console.clear issue(had 12000 occurrences today, reports starts showing with 3 hours delay)
etc...

I mean - error in such scripts flooding our account and for now I see only one possibility: is block IP address from where it came.
I'd like to have an option to provide list/mask of trusted domains where scripts could be loaded and tracker client will watch for errors. In case global error catcher intercept an issue in script loaded from somewhere else - ignore it

**Comment by coryvirok** [comment]
Check out the `hostWhiteList` configuration option. It will enable you to ignore errors which come from scripts on hosts you have not whitelisted.

**Comment by eshikerya** [comment]
it doesn't actually work as far the source/stack of the error have script from whitelisted domain but issue goes from the script loaded from 3rd party domain.
lets say domain **white.com** is whitelisted, **black.com** is not, of course. the script of 3rd party is loaded from **black.com** and I don't want to track errors from this domain. But, script from **white.com** calling function defined in script loaded from **black.com** and it throwing the error, lets say the stack would be:
```Error: Unexpected call to method or property access.
1 File http://black.com/3rd.party.js line 3183 col 21 in Anonymous function
2 File https://white.com/libs.js line 76 col 328 in n.event.dispatch
3 File https://white.com/libs.js line 70 col 126 in r.handle
4 File https://white.com/libs.js line 999 col 496 in e._wrapped
```
it would work in case whole error stack will be in 3rd party script, AFAIK

**Comment by stclairdaniel** [comment]
It sounds like we need to implement a hostBlackList configuration option. I'll pass that feature request along to the rest of my team and keep you updated going forward.

**Comment by eshikerya** [comment]
@stclairdaniel thanx a lot!

**Comment by syrnick** [comment]
+1 for the request. Host blacklist would work for me. 

Also, consider adding "reportFilterFn" that takes and error/report obj and returns false (ignore) or true (report).

**Comment by eshikerya** [comment]
+1 yep, it would be useful

**Comment by brianr** [comment]
@syrnick Sounds like `checkIgnore` might be the `reportFilterFn` you're looking for. Have you seen that? See https://rollbar.com/docs/notifier/rollbar.js/configuration/

**Comment by syrnick** [comment]
Nope. That's exactly what I've been looking for!! (could add that to the https://github.com/rollbar/rollbar.js/#ignoring-specific-exception-messages section ).

In that light, I don't even think you need a host blacklist...
