### ISSUE TITLE
Rollbar multiple configure

### ISSUE THREAD

**Issue by arbesfeld** [rollbar/rollbar.js#235]
Can I call `Rollbar.configure` multiple times in my app? I have a snippet of code that wants to add extra metadata without clobbering the existing config.

**Comment by brianr** [comment]
Yes, you sure can! Each subsequent call will update the configuration with whatever params are provided.

**Comment by arbesfeld** [comment]
thanks! perhaps the docs are wrong here? https://rollbar.com/docs/notifier/rollbar.js/api/

**Comment by brianr** [comment]
Ah, yeah that could be more clear. "Update" is probably a more accurate term than "overwrite". Thanks!
