### ISSUE TITLE
Missing build dependencies

### ISSUE THREAD

**Issue by lehresman** [rollbar/rollbar.js#238]
While trying to build this package locally with `npm install -D`, I keep getting:
```UNMET PEER DEPENDENCY webpack-dev-server@1.x```

This is fixed by adding `webpack-dev-server` to the dev dependencies in `packages.json`.

Also, running "make" revealed that `grunt-parallel` is expected, but is not installed:
```>> Local Npm module "grunt-parallel" not found. Is it installed?```

**Comment by ezarowny** [comment]
What version of node are you building with?

**Comment by lehresman** [comment]
6.6.0

**Comment by ezarowny** [comment]
Thanks man. Looks good now!
