### ISSUE TITLE
Karma tests fail on macOS Sierra due to PhantomJS 1.9

### ISSUE THREAD

**Issue by lehresman** [rollbar/rollbar.js#240]
PhantomJS 1.9 seems to not work on macOS Sierra.
https://github.com/karma-runner/karma-phantomjs-launcher/issues/138

I have confirmed that upgrading the dev dependency to 2.1 fixes the problem and karma tests run properly.  

```
diff --git a/package.json b/package.json
index c56f92d..726d391 100644
--- a/package.json
+++ b/package.json
@@ -63,7 +63,7 @@
     "mocha": "^1.21.5",
     "mootools": "^1.5.1",
     "node-libs-browser": "^0.5.2",
-    "phantomjs": "^1.9.18",
+    "phantomjs": "^2.1.0",
     "request": "^2.62.0",
     "requirejs": "^2.1.20",
     "script-loader": "0.6.1",
```

**Comment by ezarowny** [comment]
Ah, very cool. I just ran into this myself. I'll give it a shot. Thanks!

**Comment by ezarowny** [comment]
Phantom is, uh, a little confused: `PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 3 of 3 SUCCESS (0.015 secs / 0.012 secs)` 😄 

The tests all pass with version though. Thanks!
