### ISSUE TITLE
Update/add to webpack example

### ISSUE THREAD

**Issue by hakunin** [rollbar/rollbar.js#241]
Hey guys,
I don't see an example that just requires the package, instead it says to download it.
https://github.com/rollbar/rollbar.js/tree/master/examples/webpack

```
  var rollbarConfig = {
    accessToken: YOUR_TOKEN,
    captureUncaught: true,
    //...
  };

  var Rollbar = require('rollbar-browser');
  Rollbar.init(rollbarConfig);
```

**Comment by rokob** [comment]
See examples directory
