### ISSUE TITLE
Allow script host filtering as a configuration option

### ISSUE THREAD

**Issue by cfurrow** [rollbar/rollbar.js#25]
As a convenience, it would be nice to supply a list of partial host strings that would feed into the Rollbar.js library, and only report errors from scripts that come from this whitelisted set of hosts.

Example:

``` javascript
Rollbar.global({ allowedScriptHosts: ["coolgifs.geocities.com"] });
```

**Comment by piotrd** [comment]
@coryvirok is `hostWhitelist` documented anywhere? I found the option in the code (https://github.com/rollbar/rollbar.js/blob/master/dist/rollbar.js#L647), but it seems to be undocumented...

**Comment by coryvirok** [comment]
Ya, it's missing from the docs. :/ We will add it in soon. Thanks for bringing this up!

**Comment by Crisfole** [comment]
@coryvirok https://github.com/rollbar/rollbar.js/pull/138

Not sure if I phrased it perfectly, but it's a start.
