### ISSUE TITLE
[Feature] Add a convenience method similar to wrap for callbacks

### ISSUE THREAD

**Issue by rokob** [rollbar/rollbar.js#262]
For network requests, which result in a call to a handler of the form `function(err, response)`, it would be nice to have a rollbar wrapper method that is used in that place which looks like

```js
function wrapNetworkRequest(handler) {
    return function(err, response) {
        if (err) {
            rollbar.error(err);
        }
        return handler(err, response);
    }
}
```

**Comment by coryvirok** [comment]
Good idea. This is sort of like what the jQuery plugin does.
