### ISSUE TITLE
Safari still sends  (unknown): Script error.

### ISSUE THREAD

**Issue by gerwinbrunner** [rollbar/rollbar.js#263]
Hi I have a js [file hosted](https://open-cdn.s3.eu-central-1.amazonaws.com/dhlsnippet.prod.1.0.11.js) on a Amazon S3 bucket.

The cors settings are in place (and are correct I think):
```
<CORSConfiguration>
	<CORSRule>
		<AllowedOrigin>*</AllowedOrigin>
		<AllowedMethod>GET</AllowedMethod>
		<AllowedMethod>HEAD</AllowedMethod>
		<MaxAgeSeconds>3000</MaxAgeSeconds>
        <AllowedHeader>*</AllowedHeader>
	</CORSRule>
</CORSConfiguration>
```

Also the script is loaded with the crossorigin setting:
```
<script crossorigin="anonymous" src="http://open-cdn.s3.eu-central-1.amazonaws.com/dhlsnippet.prod.1.0.11.js?v"></script>    
```

With chrome and firefox I get the correct logging, but with Safari I still get the ' (unknown): Script error.' error.

Do you have any hint what the reason for this could be and how to solve it?

Cheers,
Gerwin

**Comment by rivkahstandig3636** [comment]
Hi Gerwin, I'm not quite sure exactly what is causing this issue specifically in Safari, but to avoid having to see an unhelpful error, have you checked out our docs on [reducing noisy JS errors](https://rollbar.com/docs/reduce-noisy-javascript-errors/)? You may find them helpful.

**Comment by gerwinbrunner** [comment]
This is not about strange errors that I want to filter.
I'm actually testing the  Rollbar integration by throwing an error intentionally.
`throw new Error('Just testing....');`

For Chrome and Firefox I get the correct error stack in Rollbar.
```
Error: Just testing....
File "../src/js/shippingChooser.js" line 72 col 11 in e
throw new Error('Just testing....');
File "../src/js/index.js" line 66 col 8 in He
sc = new ShippingChooser(chooserSelector, openMap, () => showDhlCheckoutOptions(config) );
File http://localhost:10001/ line 58 col 11 in [anonymous]
File http://localhost:10001/ line 51 col 67 in loadAsync/<
```

But for Safari I just get
```
(unknown): Script error.
1
File "(unknown)" line (unknown) in [anonymous]
```

**Comment by coryvirok** [comment]
Hi @gerwinbrunner,

You may be running into Safari's CORS configuration for local files. Check this post out to see if it applies and how to work around it. 

http://stackoverflow.com/questions/26947291/cors-request-working-with-safari

**Comment by coryvirok** [comment]
@gerwinbrunner is this still an issue? If so, please reopen and we'll take another look.

**Comment by renanlecaro** [comment]
@gerwinbrunner i'm facing the same problem,  i have tons of "scrip error" reports that are fairly useless as is and they all come from safari. Did you find a way to get more detailed reports ?

**Comment by gregblass** [comment]
Got this today. Was bewildered. Still am!

**Comment by latel** [comment]
any progress here?
