### ISSUE TITLE
Uncaught TypeError: Illegal invocation error when rollbar is configured with verbose: true

### ISSUE THREAD

**Issue by ryaa** [rollbar/rollbar.js#270]
The problem occurs with ng-rollbar version 1.9.2 (latest at the moment) however I think that this is related to rollbar lib.

When rollbar is configured with verbose true and the code invokes error method Uncaught TypeError: Illegal invocation error occurs. Changing verbose: to false fixes the problem

More details can be found here https://github.com/tandibar/ng-rollbar/issues/31

**Comment by rokob** [comment]
This is likely an issue with the console not being provided by the way ng-rollbar sets up the environment. In any event, this is related to an old version of this library and is more an issue with ng-rollbar than this.
