### ISSUE TITLE
NoConflict mode for rollbar

### ISSUE THREAD

**Issue by navamgupta** [rollbar/rollbar.js#271]
Hey Guys,

We are evaluating if we can use rollbar for keeping track of js errors coming from our scripts on 3rd party sites, which means we need to bundle an instance of rollbar with our scripts (access token etc included). 
Now if the 3rd party does not use rollbar we do not have any issue but if they do use their own instance of rollbar. Is it possible for us to load our instance without conflicting with the 3rd party one?

**Comment by brianr** [comment]
@navamgupta Yes, I think this is possible. You'll want to set `globalAlias` in your `_rollbarConfig`, so that the Rollbar instance you create doesn't conflict with any others on the page. And you may also want to not initialize the uncaught error handler (and instead only make calls to your rollbar instance directly) to avoid catching errors from other parts of the page you are embedded on.

Putting that together, your _rollbarConfig would look like:

```
_rollbarConfig = {
  accessToken: "your token",
  globalAlias: "mycompanyRollbar",  // this will make rollbar available as window.mycompanyRollbar instead of window.Rollbar
  captureUncaught: false,
  captureUnhandledRejections: false,
  payload: {
    environment: "production"
  }
}
```

and then instrument your scripts like this:

```
try {
  mycode();
} catch (e) {
  mycompanyRollbar.error(e);
}
```

or by using `wrap()`:

```
mycode = mycompanyRollbar.wrap(mycode);
```

cc @rokob

**Comment by navamgupta** [comment]
@brianr Thanks for the response, I will test it out shortly.
Out of curiosity does rollbar support filtering the errors at the dashboard level where we can provide a regex and only see errors which match the regex. I am thinking a regex to filter by file name/path.

**Comment by brianr** [comment]
@navamgupta Yes, on the Items page, there are options to search against the filenames in the stack trace. See the "Stack Trace" section in the [search docs](https://rollbar.com/docs/search-items/).

You probably want `file:mydomain.com` (at least one file with your domain), `allfiles:mydomain.com` (all files match your domain), or `nofiles:mydomain.com` (no files match your domain).

**Comment by navamgupta** [comment]
@brianr  search worked like you suggested.
So I guess my last question is can i set it up as a permanent filter so that my rollbar app does everything based off the filtered events.

**Comment by brianr** [comment]
@navamgupta No, there is not currently a way to set the file filters as a permanent filter (aside from bookmarking the URL, I suppose).

Another approach would be to prevent those errors from being sent to the Rollbar API in the first place. That is probably as simple as adding `hostWhiteList: ['yourdomain.com']` to your _rollbarConfig; or you can also use `checkIgnore` for full control. [Here's a blog post](https://rollbar.com/blog/reduce-noise-logging-javascript-exceptions/) with more details.

**Comment by coryvirok** [comment]
Hi @navamgupta,

Here's a full sample of how to embed rollbar.js in a library.

[Archive.zip](https://github.com/rollbar/rollbar.js/files/1062734/Archive.zip)

**Comment by navamgupta** [comment]
Hey @coryvirok ,

Thanks for putting that together I did spend some time understanding the proposed solution. However there are two things which make it slightly limiting - 
1. The fact that we have to explicitly wrap things in try catch and then send the error over is something we would like to avoid and instead rely more on the auto capture functionality.
2. It looks like (and I could be super wrong here) but It wont work if we simply include <script> tags (thinking vanilla JS solution) without relying on any specific bundling or library.

Ideally I think we should be able to run two instances of rollbar running simultaneously ( one will be no Conflicted) with both of them auto capturing all the errors on the page and not overwrite each other. 

Let me know what you think. 

Thanks,
Navam

**Comment by coryvirok** [comment]
> 1. The fact that we have to explicitly wrap things in try catch and then send the error over is something we would like to avoid and instead rely more on the auto capture functionality. (For both the page and the included js bundle)

You don't have to explicitly wrap anything in try/catch. In the example, both of the Rollbar instances are hooking into the unhandled exception hook which means that both will receive all of the unhandled errors that happen on the page and in any JS included on the page.

> 2. It looks like (and I could be super wrong here) but It wont work if we simply include <script> tags (thinking vanilla JS solution) without relying on any specific bundling or library.

The way we have it configured right now, this is somewhat true. If you wanted to just include Rollbar via a script tag and you wanted it to not conflict with any other instances of Rollbar, you would create a JS file which initialized and configured an instance of Rollbar. You would then include that file via a script tag. This is how the example I sent you works. 

I think it might be useful to get on a phone call to explain all of this in person. The example I sent does what you're looking for. I think I just need to explain it a bit better. Email me and we can set up a call. cory at rollbar.

**Comment by coryvirok** [comment]
@navamgupta - Here is an example of how to write a transform method to modify the payload before it's sent to Rollbar:

From https://github.com/rollbar/rollbar.js#context-1
```js
// For example:
// Set a custom fingerprint
var transformer = function(payload) {
  payload.data.fingerprint = 'my custom fingerprint';
};

Rollbar.configure({transform: transformer});
// OR
var _rollbarConfig = {
  // ...
  transform: transformer
};
```

And here's an example of how to get the filenames from the stack trace: https://github.com/rollbar/rollbar.js/blob/master/examples/test.html#L10
