### ISSUE TITLE
API's to create new applications?

### ISSUE THREAD

**Issue by navamgupta** [rollbar/rollbar.js#272]
Hey Guys,
We were just curious if rollbar provides some API's that provides the ability to create new applications via code (mostly automation).
The kind of world we @Chegg are moving towards is going to be multiple components with their own monitoring and were curious if we can reduce some overhead and automate the creation of new application per component. 

Thanks,
Navam

**Comment by brianr** [comment]
@navamgupta There are APIs to create accounts, projects, teams, users, and such - check out:

- the Provisioning tutorial: https://rollbar.com/docs/api/provisioning/
- the docs for creating projects: https://rollbar.com/docs/api/projects/

Is that what you're looking for?
