### ISSUE TITLE
404 when following example

### ISSUE THREAD

**Issue by ajcantu** [rollbar/rollbar.js#275]
I get a 404 when trying to grab: https://raw.githubusercontent.com/rollbar/rollbar.js/master/dist/rollbar.umd.nojson.min.js

As suggested here:
https://github.com/rollbar/rollbar.js/tree/master/examples/webpack

**Comment by brianr** [comment]
Thanks @ajcantu! I believe the `nojson` versions are gone (and no longer needed); the correct url is https://raw.githubusercontent.com/rollbar/rollbar.js/master/dist/rollbar.umd.min.js . 

@rokob can you comment?

**Comment by rokob** [comment]
The nojson versions were intended as a work around for the fallback JSON parsing done using eval which violates CSP. Instead of that, we are now using a fallback JSON parser which does not use eval so the main umd library no longer violates CSP.

The examples need to be updated.

**Comment by rokob** [comment]
The documentation in the README is current. Use with Webpack looks something like:

```js
var rollbar = require('rollbar');

var Rollbar = new rollbar({accessToken: '...', ...});

Rollbar.log('hello world');
```

**Comment by ajcantu** [comment]
thanks, @rokob !
