### ISSUE TITLE
npm can no longer install rollbar 2.0 when git is unavailable

### ISSUE THREAD

**Issue by hairyhenderson** [rollbar/rollbar.js#277]
Before rollbar 2.0.0, `npm` could install the module with no problem in a stripped-down Alpine-based Docker container. However, now that there's a dependency on a module in GitHub, this fails:

```console
$  docker run -it node:6-alpine ash
/ # npm --loglevel error install rollbar@2.0.0
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:rollbar/console-polyfill.git /root/.npm/_git-remotes/git-github-com-rollbar-console-polyfill-git-eab6ff9d2b7597fc2f259baa18100556bdb94dbe-77dcd1e0: undefined
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:rollbar/console-polyfill.git /root/.npm/_git-remotes/git-github-com-rollbar-console-polyfill-git-eab6ff9d2b7597fc2f259baa18100556bdb94dbe-77dcd1e0: undefined
npm ERR! Linux 4.9.27-moby
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "--loglevel" "error" "install" "rollbar@2.0.0"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ENOGIT

npm ERR! not found: git
npm ERR! 
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log
```

The offending module is `console-polyfill` at https://github.com/rollbar/rollbar.js/blob/master/package.json#L12

**Comment by rokob** [comment]
Now that our commit has been merged upstream into console-polyfill, we can stop pointing to our fork and start pointing back upstream. That will fix this. N.B. this changed in 1.9.4 but is still relevant.

**Comment by hairyhenderson** [comment]
I suppose this depends on https://github.com/paulmillr/console-polyfill/issues/27

**Comment by joshhsoj1902** [comment]
@rokob https://github.com/paulmillr/console-polyfill/issues/27 has been resolved and there is a new version of `console-polyfill` available on NPM: https://www.npmjs.com/package/console-polyfill 🎉

**Comment by hairyhenderson** [comment]
I've submitted #306 to bump the `console-polyfill` version.

**Comment by coryvirok** [comment]
w00t! @rokob can you merge and get this into the next release?
