### ISSUE TITLE
Build not found

### ISSUE THREAD

**Issue by rogovdm** [rollbar/rollbar.js#278]
[URL](https://raw.githubusercontent.com/rollbar/rollbar.js/master/dist/rollbar.umd.nojson.min.js)

But [this page](https://github.com/rollbar/rollbar.js/tree/master/examples/webpack) claims it should be valid.

**Comment by rokob** [comment]
See https://github.com/rollbar/rollbar.js/issues/275 I will remove that example

**Comment by rogovdm** [comment]
Will rollbar will send errors automatically or we need to do this manually in a webpack setup?

**Comment by rokob** [comment]
If you set the configuration option to capture unhandled exceptions and/or rejections then errors reported via the onerror handler on the window will be caught automatically.
