### ISSUE TITLE
Rollbar is not initialized error when calling from other places

### ISSUE THREAD

**Issue by ronenteva** [rollbar/rollbar.js#279]
Trying to upgrade from node_rollbar, but keep getting an error when calling from other places.
### app.js
```
var Rollbar = require('rollbar');
var rollbar = new Rollbar({
  accessToken: 'POST_SERVER_ITEM_ACCESS_TOKEN',
  handleUncaughtExceptions: true,
  handleUnhandledRejections: true
});
var routes = require('./routes/index');
```
### index.js
```
var rollbar = require('rollbar');
rollbar.info('hello');
```

> Rollbar is not initialized

**Comment by rokob** [comment]
`new Rollbar` creates a new instance, there is no reference to it in a different file unless you explicitly pass one.

See the following, near the end of this section:
https://github.com/rollbar/rollbar.js#user-content-upgrading-from-node_rollbar

**Comment by ronenteva** [comment]
The example in that page under "Using Express" shows creating a new instance, is that not the right way?

**Comment by johnelliott** [comment]
@ronenteva One way to do what @rokob is saying is if you export the `rollbar` you initialize from app.js and import that exported instance into index.js.
