### ISSUE TITLE
handle logging args identically on server and client

### ISSUE THREAD

**Issue by modosc** [rollbar/rollbar.js#282]
first, thanks for the work on this!

unfortunately it's still not possible to use this in a universal app without being _really_ careful with what you're doing.

for instance, i often use a patten like this inside of a react component:
```
Rollbar.error("Some useful context message", e, { some: custom, data: here })
```

this works fine on the client but not on the server side. 

is there a reason that the [server version of _createItem](https://github.com/rollbar/rollbar.js/blob/master/src/server/rollbar.js#L344)  doesn't use the same logic as the [client](https://github.com/rollbar/rollbar.js/blob/master/src/browser/rollbar.js#L217)? 

if it's not intentional i could get a pr together to try and unify, just wanted to make sure i wasn't missing something.

**Comment by modosc** [comment]
i'm actually working on this now.

**Comment by modosc** [comment]
will you be able to roll a new release soon from `master`?

**Comment by coryvirok** [comment]
Thanks for the work on this, @modosc! Can you open a PR so we can review?

**Comment by brianr** [comment]
@coryvirok I think that was PR #299

**Comment by modosc** [comment]
yeah, pretty sure this is [merged already](https://github.com/rollbar/rollbar.js/commit/f67efaefd4c3f7a686f649e534acfc21a3ec2e7d)?

**Comment by coryvirok** [comment]
Woo! Closing.
