### ISSUE TITLE
Still sending even tho enabled: false

### ISSUE THREAD

**Issue by KrunchMuffin** [rollbar/rollbar.js#284]
I just updated to 2.0.1 and on dev it is still sending the error even tho I have it disabled.

![image](https://cloud.githubusercontent.com/assets/1037197/26368454/ab70851c-3fbf-11e7-835a-61bb2ed0aa42.png)

**Comment by modosc** [comment]
#280 - it's fixed but not released yet.

**Comment by rokob** [comment]
Fixed in 2.0.2
