### ISSUE TITLE
Rollbar not catching browser errors from throw

### ISSUE THREAD

**Issue by eschaefer** [rollbar/rollbar.js#289]
To re-create:
- Go to http://stage-mywings.redbull.com.
- Open console, type `throw new Error('test')`, hit enter.
- Type `window.Rollbar.lastError`, hit enter.
- See nothing. 

Is this intentional? Am I missing a config flag that needs to be enabled? Thanks!

**Comment by brianr** [comment]
Hi @eschaefer - two things here I think:

- That test won't work in the Chrome console, since the console has its own exception handler. You can call window.onerror directly though: `window.onerror("hello");`
- The `lastError` property appears to have been removed in 2.x. @rokob do you know if that was intentional?

**Comment by rokob** [comment]
`lastError` was not intentionally removed, but it also wasn't documented so it got lost in the changes. I can add it back.

**Comment by eschaefer** [comment]
@brianr I was noticing that Rollbar wasn't logging errors thrown using `throw new Error(message)` from one of our javascript bundles, so I tried to make a reduced test case. Totally forgot that the Chrome console isn't the right place for that. 

To clarify, we have a bunch of API calls that rely on Promises, and if they fail/reject, then we `throw`. Those errors aren't caught in Rollbar, so we added an extra line with `Rollbar.error(error)` for now. Was just curious about why other errors are caught generically, but `throw new Error()` isn't. Thanks for your patience!

**Comment by coryvirok** [comment]
@eschaefer have you enabled `captureUnhandledRejections`?

Rollbar docs here: https://rollbar.com/docs/notifier/rollbar.js/#rollbarhandleunhandledrejection

More info here: 
http://2ality.com/2016/03/promise-rejections-vs-exceptions.html

**Comment by coryvirok** [comment]
@eschaefer any update? I don't want to leave you hanging. ;)

**Comment by rokob** [comment]
The way exceptions work inside most Promise implementations is to get turned into Promise rejections. To have Rollbar catch these and report them, we provide the configuration option `captureUnhandledRejections`, setting this to `true` should fix this issue. I will add back lastError to the Rollbar instance.

**Comment by Udaykumar8010** [comment]
Hi Team,
 I am getting rollbar error in console.
while debugging i found belwo code is reponsible for same.

window.Rollbar.error(err)

can some one please explain you of this method?

**Comment by rollbar-bborsits** [comment]
Hey @Udaykumar8010, [This doc](https://docs.rollbar.com/docs/javascript) will guide you through the first steps. I assume your problem is that you shouldn't use `window` when you call rollbar, but just call it like this: `Rollbar.error(err)`. Let me know if this doesn't help.
