### ISSUE TITLE
server-side code errors out when given a message and an error

### ISSUE THREAD

**Issue by modosc** [rollbar/rollbar.js#298]
on the client `Rollbar.error("a message", e)` will silently drop the message if `e` is an error. 

on the server this doesn't happen which results in this error:
```
API error: Invalid format. data.body must have either a 'trace', 'trace_chain', 'message' or 'crash_report' property, (but not more than one).
```

i can make a pr to fix this on the server, but i'm curious if the client side behavior is really the desired behavior?

**Comment by modosc** [comment]
pr: #299

**Comment by modosc** [comment]
ping?

**Comment by davidgwking** [comment]
I'm also encountering this issue. Thanks for the fix, @modosc. Looking forward to response from the team at rollbar.

**Comment by coryvirok** [comment]
Thanks for surfacing this. I added a suggestion for how to do this in the PR.

**Comment by sarkistlt** [comment]
Hi, any updates here? still have this issue

**Comment by rokob** [comment]
I'll get this out today

**Comment by sarkistlt** [comment]
ok, cool
