### ISSUE TITLE
2 environment

### ISSUE THREAD

**Issue by phuzarski** [rollbar/rollbar.js#301]
I added rollbar to my ReactApp + Webpack. 

Have some trouble how make it possible to distinguish the production and staging environment?

My rollbar.js looks like:

`const rollbar = require('./rollbar.umd.min.js')`

> const rollbarConfig = {
>   accessToken: process.env.ROLLBAR_ACCESS_TOKEN,
>   captureUncaught: true,
>   captureUnhandledRejections: true,
>   payload: {
>     environment: 'production',
>   },
> };

So for production in payload environment should be production and second for staging- staging.

**Comment by mikecharles** [comment]
Hey, how did you wind up solving this issue?

**Comment by asoong** [comment]
+1
