### ISSUE TITLE
Provide TypeScript declaration files

### ISSUE THREAD

**Issue by dlindenkreuz** [rollbar/rollbar.js#302]
See https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html

**Comment by coryvirok** [comment]
Thanks @dlindenkreuz. We don't currently have plans to do this but are certainly open to PRs!

**Comment by TimMensch** [comment]
FYI, lack of TypeScript declarations is making investigate other options. Been using and liking Rollbar, but I'm not ready to volunteer to create and maintain TypeScript declarations for a commercial project.

Also: You can hardly claim Angular 2 support with declarations, given that Angular 2 recommends TypeScript.

**Comment by emk** [comment]
Having TypeScript declarations would be a huge win for my employer; rollbar is the last server-side library that we use regularly that we still don't have type declarations for. Thank you to @rokob for working on this!
