### ISSUE TITLE
Verbose option removed, but still referenced in docs

### ISSUE THREAD

**Issue by tophernuts** [rollbar/rollbar.js#309]
It looks like the [verbose option](https://github.com/rollbar/rollbar.js/commit/329b8b58bfa3ee60d2ca9cde56f3fa9d9fa9940e#diff-46574108c66fcb1b8eb4e52b455e1c56L577) was removed in the Notifier Rewrite, but it's still [referenced throughout the docs](https://github.com/rollbar/rollbar.js/blob/9b8ec0ace479f6564f0e185530a375d09251cefe/README.md#verbose-option).

Are there any plans of adding it back in?

**Comment by rokob** [comment]
Yes, let's make this the task to track getting this added back.

**Comment by arwinsardana** [comment]
Just wanted to confirm that this is still to be released? What version can we expect this in? Thanks!

**Comment by rokob** [comment]
This will be in v2.1.0 which should be released sometime this week.
