### ISSUE TITLE
Offline storage

### ISSUE THREAD

**Issue by jessewgibbs** [rollbar/rollbar.js#316]
This is a feature in other products, would be cool to have something similar in Rollbar.js
https://raygun.com/docs/languages/javascript#offlinesaving

**Comment by rokob** [comment]
This will take a bit of work to get just right and not end up with bugs like I've seen in other notifiers where we have a backlog of errors that blow through quotas.

**Comment by rivkahstandig3636** [comment]
Hi there, I’m closing out all issues opened before 2018 that haven’t had any activity on them since the start of this year. If this is still an issue for you, please comment here and we can reopen this. Thanks!
