### ISSUE TITLE
Node Server - UnhandledExceptions -> also log to console

### ISSUE THREAD

**Issue by gerwinbrunner** [rollbar/rollbar.js#320]
I'm on node and I use this configuration snippet for rollbar:
```
const rollbar = Rollbar.init({
  accessToken: rollbarServerAccessToken,
  handleUncaughtExceptions: true,
  exitOnUncaughtException: true,
  environment: Meteor.settings.public.env,
});

```

I created a test error, by calling `throw new Error('!!! JUHUHUHU !!! CALLED');`
The error gets reported to rollbar and the server stops 👍 

The problem now is, that in the log I do not have any information at all about the issue.
How can I let rollbar handle the exception but also have a regular console.log or console.error statement?

**Comment by rokob** [comment]
There is an option, `verbose`, that should also log to the console. Try adding `verbose: true` to your configuration.

**Comment by gerwinbrunner** [comment]
Hi @rokob did that already. But the option seems to only work on the client, not on the server.
I use rollbar version `^2.0.4`

**Comment by rokob** [comment]
We use the [debug](https://www.npmjs.com/package/debug) package on the node side which requires you to use an environment variable to enable the log output. For example,

```
DEBUG=Rollbar:* node app.js
```

**Comment by rokob** [comment]
That should be documented somewhere and I don't think it is, I will fix that.

**Comment by gerwinbrunner** [comment]
Ok, I tried it...

I now get the folloging output:
```
I20170622-19:07:24.729(2)? PRE - JUHUHUHU C exception
I20170622-19:07:25.687(2)? Thu, 22 Jun 2017 17:07:25 GMT Rollbar:log Successful api response. Link: https://rollbar.com/occurrence/uuid/?uuid=25e5e414-8588-4024-d2c6-de3c810f80b6
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```
Here is what I configure:
```
export DEBUG=Rollbar:* node 
```

So I see the log message from Rollbar, but I do not see the actual exception that caused it.
Any idea how to get the actual exception stack trace in the log?

**Comment by tophernuts** [comment]
https://github.com/rollbar/rollbar.js/issues/309

The verbose option was just recently added back, but there hasn't been a release yet, I think that's why you're not seeing the stack trace yet!

**Comment by gerwinbrunner** [comment]
When is this going to be released?

Mit freundlichen Grüßen
Gerwin Brunner

**Comment by rokob** [comment]
v2.1.0 should resolve this
