### ISSUE TITLE
maxItems POST request fails in javascript

### ISSUE THREAD

**Issue by arwinsardana** [rollbar/rollbar.js#322]
I've set the global Rollbar (v2.0.4) config `maxItems` property to `5`, but that 5th request seems to fail (HTTP 403) with the following error response:

Request
```
POST https://api.rollbar.com/api/1/item/ HTTP/1.1
Host: api.rollbar.com
Connection: keep-alive
Content-Length: 159
X-Rollbar-Access-Token: <client side access token>
Origin: http://localhost:9000
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.109 Safari/537.36
Content-Type: application/json
Accept: */*
Referer: http://localhost:9000/curate
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.8


{"access_token":"<client side access token>","data":{"message":"maxItems has been hit. Ignoring errors until reset.","err":null,"custom":{"maxItems":5}}}
```

Response
```
HTTP/1.1 403 Forbidden
Server: nginx
Date: Mon, 26 Jun 2017 18:59:00 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 138
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
X-Response-Time: 3ms

{
  "err": 1,
  "message": "insufficient privileges: post_server_item scope is required but the access token only has post_client_item."
}
```

Going to take a guess that this could be 1 of 2 things:
1. I'm dumb and making a silly mistake :)
1. The request body is not what the server is expecting and therefore the server is interpreting this as a server-side generated error message instead of a client-side generated message and thus expecting the server-side token to be included in the request. If this is the case, it would seem to be a problem since this error message is in fact generated client side.

Any help would be appreciated. Thanks so much!

**Comment by rokob** [comment]
I am pretty sure this is a bug, will fix.
