### ISSUE TITLE
Cannot find module "../../package.json"

### ISSUE THREAD

**Issue by gpltaylor** [rollbar/rollbar.js#330]
NOTE: This project works if I remove Rollbar.

I am getting the following error

`Cannot find module "../../package.json"`

I have the following setup using Lerna.js

projecta/packages -
   - /customlibs
   - /server
   - /site1
   - /site2

Server 
This hold a simple Express site that uses Rollbar

Site1
Imports the express server and starts the process
This is build using webpack to bundle the server (Don't ask 😄).

I believe that I am getting this error as Webpack is trying to find the "package.json" from the wrong location and is unable to locate it during the build process.

NOTE: If I edit the rollbar code, and replace all references to packageJson, this works.
If I move all the code into site1, this works.

I'm not sure if this is due to how JSON files are imported or if it's a bug in the Rollbar code not using PATH correctly?

Any help gratefully appreciated

**Comment by rokob** [comment]
That is pretty strange, let me see if I can make a test project that replicates this. What do you change the references of packageJson to in order to get things to work? I have seen things like this related to the way node resolves symlinks and how lerna does bootstrapping. At the moment, I'm not sure where the fault lies, but I'll dig into it a bit.

**Comment by gpltaylor** [comment]
Thanx @rokob, I am not changing the code to get this to work. It's simply where I am using the require statement to import the Rollbar module.

If I import from the "/sever" project (as this is where my Express code lives) it **can't** find the file.
If I import from the main project (Where the current build path is located), in this case "/site1"; it can find the file.

I believe that by importing module "server" that then imports "rollbar" that the real PATH has changed. Therefore relative paths "../../package.json" no longer work. However, this seems to be false, as other imports for ".js" do work.

If I edit the rollbar code and remove all references to "packageJson" variable, and the erquire for package.json, then this does work.
I feel that Webpack is handling relative paths for JSON files incorrectly when under this structure.

NOTE: I am using "json-loader" in webpack to handle the imports.
