### ISSUE TITLE
Confused About logger.error API

### ISSUE THREAD

**Issue by arb** [rollbar/rollbar.js#336]
Per the documentation, you can pass into `rollbar.error` an exception, a string, and an object. What I'd like to do is pass an exception and a string that's a simple human readable label. However, it seems like if I pass an exception into `rollbar.error`, the string is ignored and only the exception information is logged. I can pass an object in with meta data and get around this, but that seems counter to the documentation.

I'm currently trying with `logger.error(result, 'error retrieving databases');` where `results` is an instance of `Error`.

**Comment by rokob** [comment]
Yeah this is a bug in expectations,  and needs to get changed. The expected result of

```
logger.error(result, 'error retrieving databases');
```

should be that we get the stack trace for the result error, but the message string should probably be added either to the description of the error or as part of the custom metadata. Right now it is just thrown away.
