### ISSUE TITLE
not sending exception correctly when upgraded to newest version

### ISSUE THREAD

**Issue by and-megan** [rollbar/rollbar.js#339]
Using syntax `rollbar.error(err, req, {custom: custom})` for handled exceptions.

There's no exception passed in the payload. custom ends up as extraArgs and request is successfully passed. The exception's message ends up getting passed in as `message` at the top level (not nested under body). body.message.body is an empty string. 

The exception is seen in the server logs.

**Comment by rokob** [comment]
Is `err` and instance of `Error`?

**Comment by rivkahstandig3636** [comment]
@and-megan Is this issue still occurring?

**Comment by and-megan** [comment]
Someone else reported this and then didn't answer my follow up question 5 months ago. I assume it isn't a problem anymore. I'll close this one.
