### ISSUE TITLE
promise support + captureUncaught / captureUnhandledRejections on aws lambda 

### ISSUE THREAD

**Issue by nbransby** [rollbar/rollbar.js#342]
would be useful if the log methods returned promises so I could await them instead of having to wrap them in promises everywhere: 
```js
await new Promise(r => rollbar.log('Hello world!', r));`
````
Also the reason I need to wait for the log request to complete is because otherwise it doesnt get sent due to having callbackWaitsForEmptyEventLoop (http://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-context.html) set to false. I don't see how captureUncaught / captureUnhandledRejections would work on aws lambda with this setting?

**Comment by rokob** [comment]
AWS Lambda is a bit new to me, but why would you set `callbackWaitsForEmptyEventLoop` to false? That completely destroys the node programming model. You don't care about things that are happening in the event loop? Also, `rollbar.log` returning isn't the same as the log request completing due to the use of callbacks and async operations throughout the logging process.

**Comment by nbransby** [comment]
Example of why libs set it to false: https://github.com/claudiajs/claudia-api-builder/blame/6e5379282b4d33ed30fa4c0d6f6ef0e781f0d923/RELEASES.md#L53

Understood `rollbar.log` returning isn't the same as the log request completing but that would be the point of returning a promise which would resolve when the callbacks and async operations throughout the logging process are complete.

**Comment by nbransby** [comment]
Looks like some good updates coming! Thanks, can I grab master and try them?

**Comment by rokob** [comment]
The stuff described here https://github.com/rollbar/rollbar.js#lambda, namely the lambdaHandler helper function, is available in the latest release, v2.2.7

**Comment by nbransby** [comment]
I took the latest master as it had some updated typescript definitions. Works great thanks - all I need now is  to see the typescript stacktrace in Traceback!
