### ISSUE TITLE
Transform Issue

### ISSUE THREAD

**Issue by and-megan** [rollbar/rollbar.js#347]
Issue with transforms, specifically building out the stack trace. It would never return and thus causing a timeout (in lambda, which was like 10 seconds). Able to  reproduce this behavior by trying to report any error object. Providing a string it would work fine, but `error(new Error())` or any combination of `error` calls with the request and options it would hang.

**Comment by rokob** [comment]
I'm almost certain this was fixed by always calling the callback which was not always done at the time this issue was created. I'm going to close and let it be re-opened if this happens again.
