### ISSUE TITLE
Add a max frames config option

### ISSUE THREAD

**Issue by coryvirok** [rollbar/rollbar.js#351]
Sometimes the JS SDK will send over very large JSON payloads which cannot be deserialized due to the # of frames, (> 500 in one example). This is probably not very useful for users. Let's add a default max number of frames sent over and allow the user to configure it.

**Comment by rivkahstandig3636** [comment]
Hi there, I’m closing out all issues opened before 2018 that haven’t had any activity on them since the start of this year. If this is still an issue for you, please comment here and we can reopen this. Thanks!
