### ISSUE TITLE
Angular 4 integration instructions

### ISSUE THREAD

**Issue by rivkahstandig3636** [rollbar/rollbar.js#359]

**Comment by miclill** [comment]
Getting these errors:
ERROR in /home/sam/sync/abholung/frontend/node_modules/rollbar/index.d.ts (13,47): ',' expected.

ERROR in /home/sam/sync/abholung/frontend/node_modules/rollbar/index.d.ts (18,30): '{' or ';' expected.

ERROR in /home/sam/sync/abholung/frontend/node_modules/rollbar/index.d.ts (43,39): ',' expected.

ERROR in /home/sam/sync/abholung/frontend/node_modules/rollbar/index.d.ts (43,40): Parameter declaration expected.

Typescript Version: 2.4.2

**Comment by miclill** [comment]
Resolved by using latest version.

**Comment by brunto** [comment]
Perfect it works now. Thx.
