### ISSUE TITLE
Investigate need for handling rejectionhandled events

### ISSUE THREAD

**Issue by jessewgibbs** [rollbar/rollbar.js#362]
Details in https://app.clubhouse.io/rollbar/story/17783/investigate-need-for-handling-rejectionhandled-events

**Comment by rivkahstandig3636** [comment]
Hi there, I’m closing out all issues opened before 2018 that haven’t had any activity on them since the start of this year. If this is still an issue for you, please comment here and we can reopen this. Thanks!
