### ISSUE TITLE
Add ability to include screenshots with exception messages

### ISSUE THREAD

**Issue by jessewgibbs** [rollbar/rollbar.js#364]
details in https://app.clubhouse.io/rollbar/story/12177/add-ability-to-include-screenshots-with-exception-messages

**Comment by rivkahstandig3636** [comment]
Hi there, I’m closing out all issues opened before 2018 that haven’t had any activity on them since the start of this year. If this is still an issue for you, please comment here and we can reopen this. Thanks!
