### ISSUE TITLE
allow person to be a function or an object

### ISSUE THREAD

**Issue by jessewgibbs** [rollbar/rollbar.js#367]
Details in https://app.clubhouse.io/rollbar/story/9215/rollbar-js-allow-person-to-be-a-function-or-an-object

**Comment by rivkahstandig3636** [comment]
Hi there, I’m closing out all issues opened before 2018 that haven’t had any activity on them since the start of this year. If this is still an issue for you, please comment here and we can reopen this. Thanks!

**Comment by glen-84** [comment]
@rokob,

Can this be reopened?

In a SPA, I don't have access to the person data on initial load (of the HTML "shell"). Using a function would allow the value to be retrieved at a later point in time.

**Comment by waltjones** [comment]
@glen-84 we are thinking about a callback that passes the current value of `person` (if any) and returns the new/updated value. Would that work for you?

**Comment by glen-84** [comment]
I'm not sure if I follow – the "current" value is stored in memory by Rollbar after the last logged error, or comes from the `person` config?

Either way, as long as I can set the person ID just before an error is logged, it should be fine.

**Comment by brianr** [comment]
@glen-84 Another way to do this would be to push person data to the Rollbar instance as soon as it becomes available to the application. You can do this using:

```
Rollbar.configure({payload: {person: {id: "123", username: "the_username", email: "the_email@address.com"}});
```

If the person changes, you can call `configure()` again.

**Comment by waltjones** [comment]
@glen-84 Yes, if the value had been updated by you or Rollbar, that would be the current value. Otherwise, the value from config.

**Comment by glen-84** [comment]
@brianr,

> Another way to do this would be to push person data to the Rollbar instance ...

Ah, I didn't realize that this was possible. I think that this will work – should I go ahead with this option?

**Comment by brianr** [comment]
@glen-84 OK, great - yes, I think that is probably a better way to go. I'm going to close this issue out. If that ends up not working, let us know and we can reopen this.
