### ISSUE TITLE
Detect 3rd party <script> tags

### ISSUE THREAD

**Issue by jessewgibbs** [rollbar/rollbar.js#372]
details in https://app.clubhouse.io/rollbar/story/7601/sniff-for-script-tags

**Comment by jessewgibbs** [comment]
Also related to https://app.clubhouse.io/rollbar/story/19174

**Comment by rivkahstandig3636** [comment]
Hi there, I’m closing out all issues opened before 2018 that haven’t had any activity on them since the start of this year. If this is still an issue for you, please comment here and we can reopen this. Thanks!
