### ISSUE TITLE
Rollbar.warn should use console.warn to reprint

### ISSUE THREAD

**Issue by jessewgibbs** [rollbar/rollbar.js#373]
details in https://app.clubhouse.io/rollbar/story/6135/rollbar-js-rollbar-warn-should-use-console-warn-to-reprint

**Comment by rokob** [comment]
I don't know what this is asking for

**Comment by rokob** [comment]
Is this saying that if verbose is true and rollbar.warn is used then use console.warn instead of console.log?

**Comment by rivkahstandig3636** [comment]
@rokob do you have access to the helpscout convo linked in the ch story?

**Comment by rokob** [comment]
The actual conversation is asking for something different than the title of this issue. It is about capturing console.warning calls that happen prior to a thrown exception to enrich the error data with possibly useful data that occurred before the error happened. Telemetry does this with the log capturing turned on. So I am going to close this.
