### ISSUE TITLE
scrub() in utility.js reach maximum call stack size

### ISSUE THREAD

**Issue by tw0517tw** [rollbar/rollbar.js#374]
When I try to pass in some custom fields to rollbar, it keeps raising `RangeError: Maximum call stack size exceeded`.
After digging for a while, I found it may be caused by recursive `scrub()` in utility.js
https://github.com/rollbar/rollbar.js/blob/master/src/utility.js#L500-L512

More info at my reproducing repo:
https://github.com/tw0517tw/rollbar-overflow

**Comment by fmquaglia** [comment]
Having the same issue

**Comment by rokob** [comment]
The koa request object is self-referential, scrubbing isn't written to handle that but it should.
