### ISSUE TITLE
API error: Invalid format. data.body.telemetry[0].timestamp_ms string value found, but a integer is required.

### ISSUE THREAD

**Issue by DexterTheDragon** [rollbar/rollbar.js#388]
I upgraded our rollbar.js to 2.2.3 today (using the snippet defined on the README). Since then we've been getting errors from the "Rollbar System" that say

API error: Invalid format. data.body.telemetry[0].timestamp_ms string value found, but a integer is required. data.body.telemetry[1].timestamp_ms string value found, but a integer is required. data.body.telemetry[2].timestamp_ms string value found, but a integer is required. data.body.telemetry[3].timestamp_ms string value found, but a integer is required.

**Comment by ezarowny** [comment]
Hey @DexterTheDragon thanks for the report! We're looking into it.

**Comment by ezarowny** [comment]
Do you get this for every error you try to send or just some?

**Comment by DexterTheDragon** [comment]
We've gotten 2 so far that have been that error and no other errors. Talking to support it looks like it might be that we use Date.js that overrides `Date.now()` to return `new Date()`.

**Comment by DexterTheDragon** [comment]
If this is something you are unable to fix I'll understand. It's hard to do stuff when what is considered the standard library is being overwritten to do something different. In which case go ahead and close this issue.

I'm going to disable telemetry for now and look into ripping Date.js out of our site.

**Comment by ezarowny** [comment]
I think @rokob might have a fix. We'll keep you posted.
