### ISSUE TITLE
Publish 2.2.3 on NPM

### ISSUE THREAD

**Issue by whroman** [rollbar/rollbar.js#393]
Hi, I heard about [Rollbar Telemetry](https://rollbar.com/blog/introducing-javascript-telemetry/) today and I'm looking forward to trying it out!

I noticed that the latest version of `rollbar-browser` on NPM is `1.9.4`, but it looks like I need `2.2.3` to use Telemetry.

I couldn't find any install information on the README besides the copy+paste code, so I couldn't tell if this is how devs are now supposed to add `rollbar-browser` to their sites or whether someone had simply forgotten to publish to NPM.

## Questions

1) Will you continue to support NPM installation?
2) If so, can you publish the latest version? :)

**Comment by rokob** [comment]
1. Yes
2. It is already published, the package name is `rollbar` as of the 2.0 release. See the package.json file in this repo
