### ISSUE TITLE
Can't changes fingerpring and autoInstrument after creation on instance

### ISSUE THREAD

**Issue by andreiucm** [rollbar/rollbar.js#394]
```
var rollbar = new Rollbar({fingerprint: "first finger print"})

rollbar.configure({
  fingerprint:"new fingerprint value", 
  autoInstrument: {
    network: true,
    dom: false,
    navigation: true,
    connectivity: true,
    log: false
}})

rollbar.error("test error")
```

Problems
1. fingerprint is **first finger print** instead of **new fingerprint value**
2. telemetry log and dom still enabled!

Environment
Rollbar: 2.2.3
OS: linux 16.04

**Comment by rokob** [comment]
Well the syntax there for configure is wrong, both fingerprint and autoInstrument should be keys in the same object. Second, the autoInstrument is not reconfigurable by mistake, that is what #395 is meant to fix. As to fingerprint, I need to dig a little more.

**Comment by andreiucm** [comment]
Ok, waiting for fingerprint then. And yes I updated the description to be both fingerprint and autoInstrument in the same object.

**Comment by rokob** [comment]
The fingerprint needs to be embedded inside the payload argument, as the code is written above, neither fingerprint value should end up in the final item sent to Rollbar. Are you saying that the items sent to Rollbar have the given fingerprint value when calling `new Rollbar({fingerprint: 'something here'})`?
