### ISSUE TITLE
Telemetry captures other forms of PII

### ISSUE THREAD

**Issue by clinejj** [rollbar/rollbar.js#397]
While telemetry excludes password input fields, it does not exclude or offer the ability to exclude other input types like credit card. Two requests:
- Separate out clicks from form inputs in the configuration for telemetry (so you can configure to collect one or the other but not both)
- Support passing in a configuration for elements to exclude from telemetry logs

**Comment by brianr** [comment]
Thanks @clinejj for bringing this up.

At the moment, you can prevent those values from being sent using a `transform` hook - this will let you inspect and modify the payload being sent from the browser to api.rollbar.com before it's sent. However, this is not a very friendly solution. We probably need something like `scrubFields` for the telemetry input values.

**Comment by jonathanbrockman** [comment]
Being able to list all inputs to scrub in the config would be nice. 
Hotjar's also has a nice solution for preventing the upload of sensitive form data. Adding a `data-hj-masked` attribute to an input replaces the input value with asterisks in the Hotjar payload. 

https://docs.hotjar.com/docs/masking-elements-in-recordings-and-heatmaps

**Comment by megatimes** [comment]
Being able to list all inputs to scrub in the config would be nice.
Hotjar's also has a nice solution for preventing the upload of sensitive form data. Adding a data-hj-masked attribute to an input replaces the input value with asterisks in the Hotjar payload.

https://docs.hotjar.com/docs/masking-elements-in-recordings-and-heatmaps

**Comment by Nostrus** [comment]
@brianr @megatimes the linked PR is already merged and it seems to work fine for password input fields using `scrubTelemetryInputs: true`, but other sensitive fields like email still seem to be sent as Form value. Any tips on how to work around it at the moment?

**Comment by rokob** [comment]
What do you mean by "sensitive fields like email still seem to be sent as Form value"? Based on `https://github.com/rollbar/rollbar.js/blob/master/src/browser/telemetry.js#L323` setting `scrubTelemetryInputs` to `true` will result in all values being replaced with `[scrubbed]`. There will still be events for editing the elements but the value should not end up as part of the event. This was only included as of v2.2.4

**Comment by Nostrus** [comment]
Sorry for not phrasing clearly. 

What I meant in this case is that I have a login form, and I don't see the password field's value sent at all, but I can still see the entered value for the Email input field (which is just a normal `type="text"` field in the end). However, the password field's value is not `[scrubbed]` as it should be based on the code you shared, but it's just not sent, so it might be something else related to that specific error occurence.

Also, what I see is that the input field's value is not shown as entered into an input element but as entered into a div, but that might just be a flaw in the Telemetry reporting itself, i'm not sure. 
Maybe this screenshot explains it better: 
<img width="634" alt="screen shot 2017-08-30 at 8 20 59 pm" src="https://user-images.githubusercontent.com/1503990/29889639-3033f89e-8dc5-11e7-9bc3-8927a92fa124.png">

**Comment by rokob** [comment]
Okay gotcha, yeah this shouldn't be happening with v2.2.4+, I'll look into this and get an update to you as soon as I can.

**Comment by Nostrus** [comment]
Awesome, thank you :)

**Comment by rokob** [comment]
This should be fixed in 2.2.7
