### ISSUE TITLE
Is there a way to prevent rollbar from logging into the console, especially in dev mode ?

### ISSUE THREAD

**Issue by HadrienPierart** [rollbar/rollbar.js#399]
Whether I have set enable to true or false, the result is the same, every error caught by rollbar is also wrapped in the console. This is quite annoying as it messes the line and file the error occured in...

For instance, i get in the console : 
> GET http://localhost:8080/api/tags 401 (UNAUTHORIZED) rollbar.min.js:2

And then I have to unwrap the error to find this :
```

send | @ | jquery.js?eedf:9566
  | ajax | @ | jquery.js?eedf:9173
  | search | @ | tags.js?82db:14
```

Is there a way to prevent that behaviour ? I tried enabled and checkIgnore properties but to no avail...

**Comment by rokob** [comment]
Turning off console telemetry should solve this if it is caused by what I think is causing this issue
```
config = {
    ...
     autoInstrument: {
         console: false
     }
}
```

**Comment by azharkhan** [comment]
This happened to me as well, I think the right setting is: 

```
autoInstrument: {
    log: false
}
```

thanks for the tip @rokob!

**Comment by rokob** [comment]
Oops, I had the key wrong, yes it is `log`, I edited my comment.
