### ISSUE TITLE
Enabling Telemetry functionality changes the script/line number reported in browser console.

### ISSUE THREAD

**Issue by manemal** [rollbar/rollbar.js#400]
Normally when using window.console methods, the message logged to the console window contains the script file and line number that generated the log message.  When you enable the Telemetry functionality in Rollbar, any log messages are now reported as coming from the Rollbar script (and line number) and not the originating script/line number.

e.g.
![rollbar-telemetry](https://user-images.githubusercontent.com/11514265/29541644-c4717288-8718-11e7-80ed-af17d4f40411.png)

**Comment by gaiottino** [comment]
The above is extremely annoying since it essentially means we have to unload the Rollbar-script during development instead of just disabling it.

**Comment by rokob** [comment]
I'm trying to figure out a way to solve this, but for development, setting the log option to false inside the autoInstrument object will restore file and line numbers at the expense of not tracking telemetry data. But if you were going to disable rollbar in dev anyway then that should not be a problem.

**Comment by gaiottino** [comment]
At the very least setting `enabled: false` should also apply to `autoInstrument.log`. Or is there a good reason for not making this change?

**Comment by rokob** [comment]
Yeah that seems fair, I'll do that.

**Comment by gaiottino** [comment]
As far as I can tell this is still an issue. Testing with https://cdnjs.cloudflare.com/ajax/libs/rollbar.js/2.3.1/rollbar.js and `enabled: false` it's still highjacking the `console.logs`. I dont know it's been reintroduced at this point or never made it into a release.

**Comment by rokob** [comment]
I added a button to the page at examples/universal-browser/test.html to call `Rollbar.configure({enabled: false})`. As you can see in the default configuration the logs are wrapped, but after setting enabled to false they are not anymore.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/831355/33392486-180120ee-d4f1-11e7-8479-580a22626f25.gif)

What scenario are you describing where `enabled: false` is still wrapping console.log? Are you calling configure for a different instance of Rollbar? What browser are you seeing this in?
