### ISSUE TITLE
Angular 2 instructions do not work for Angular 4.

### ISSUE THREAD

**Issue by gaiottino** [rollbar/rollbar.js#402]
I've spent a lot of time trying to get the rollbar integrated with our Angular 4 app with AOT enabled. I'm running Angular CLI 1.2.6, Angular 4.3.5 and was trying to use Rollbar 2.2.3.

The current instructions do not work and will result in

`
ERROR in Error encountered resolving symbol values statically. Reference to a local (non-exported) symbol 'PROVIDERS'. Consider exporting the symbol (position 44:7 in the original .ts file), resolving symbol AppModule in /Users/daniel/Documents/src/hub-app-seed/frontend/src/app/app.module.ts
`

I refactored my code to be AOT compliant and also found this gist https://gist.github.com/saschwarz/bee0618f5604646dfe56ca61124e5122 but ran into another issue. Once the code was running on the server, it was unable to find Rollbar which seems to have been optimized away the Rollbar import. When running it locally it worked fine so something happens in the AOT step.

The only way I got it working in the end was to include

```
// Rollbar Snippet
var _rollbarConfig = {}!function(r){function o(n)...
// End Rollbar Snippet
</script>
```

in my index.html so that I could update my ErrorHandler to 

```
export class RollbarErrorHandler implements ErrorHandler {
  private rollbar = (<any>window).Rollbar

  constructor(private session: SessionService, private logger: Logger) {
    this.rollbar.configure(environment.rollbar)
  }
}
```

and thus allowing me to keep my config in environment files. If anyone has this working for a setup similar to mine, I'd love to know what you did differently. For now, hopefully my workaround and this issue will help someone else.

**Comment by rokob** [comment]
I will put this on our radar to document working with AOT and Angular 4.

**Comment by rokob** [comment]
The docs are updated and should work with Angular 4 with and without AOT

**Comment by cyberabis** [comment]
FInally this helped, thanks! But, looks like the docs on the website and in the app are still not updated for angular 4 with AOT. Please do, spent quite some time to get here and solve the issue :)
