### ISSUE TITLE
All messages are being blacklisted.

### ISSUE THREAD

**Issue by jahed** [rollbar/rollbar.js#411]
Commit 0e03a510b080e2f767952417742fb6ca75f9423f seems to have introduced a problem where it forces a `hostBlacklist` to be defined in the configuration and for there to be a trace in the item body. If it's not defined, the result of the predicate is always false and messages never get POSTed.

`urlIsOnAList` in predicates.js returns `true` early if there's no list or no trace. This makes perfect sense for whitelists, but if it's a blacklist, the early result should be `false`.

See https://github.com/rollbar/rollbar.js/blob/master/src/browser/predicates.js#L53

**Comment by jahed** [comment]
I can confirm that rolling back to 2.2.3, before this change was published, fixes the problem.

**Comment by rokob** [comment]
Will fix

**Comment by rokob** [comment]
2.2.6 fixes this, sorry about that
