### ISSUE TITLE
Updating to 2.2.3 with Telemetry enabled is gobbling up browser memory

### ISSUE THREAD

**Issue by alanosman** [rollbar/rollbar.js#413]
We recently updated our rollbar backend SDK and front end to 2.2.3 to take advantage of telemetry data.   

Since updating, we noticed that browser memory used by our app was accumulating each time a user changed a view within our product (our views are React based interactive - lane kanban type views with saved filters). 

When we disabled Telemetry, the memory consumption issues go away.  I've prepared a heap dump from Google chrome to show the differences we are seeing in a short moment between switching views and what is going on with the rollbar instrumentor.  

You can get it here along with the screenshots:

https://www.dropbox.com/s/r1v4iummg5doazc/heap.zip?dl=0

**Comment by rokob** [comment]
Looking into this, let me see what is going on.
