### ISSUE TITLE
All console logs point to rollbar instead of original file.

### ISSUE THREAD

**Issue by lukephills** [rollbar/rollbar.js#416]
Just upgraded from version 1 and now all console.logs point to rollbar in dev mode instead of the particular file. This makes it very difficult to debug. Is there a way to change this?

I've tried using both noconflict and main js files. I'm using typescript with sourcemaps.

<img width="463" alt="screen shot 2017-08-24 at 17 37 35" src="https://user-images.githubusercontent.com/6436772/29868485-fa18ca62-8d76-11e7-8898-5d6042be2fee.png">

**Comment by rokob** [comment]
See #400
