### ISSUE TITLE
Enable `maxItems` global settings for browser only

### ISSUE THREAD

**Issue by fraserxu** [rollbar/rollbar.js#420]
Hi there, I have a question regarding to the new Isomorphic Rollbar JavaScript library:

Before we migrating to the new isomorphic version, we use the browser version of Rollbar.js to limit the report number for per page load.

```js
rollbar.config({ 
  // Max number of items to report per page load.	
  maxItems: 20
}) 
```

This settings is great because sometimes the browser can run into a loop thus sending the same error a few thousands of times per browser session.

But after migrating to the Isomorphic version, we are creating the `rollbar` instance in a separate module like this:

```js
import Rollbar from 'rollbarjs'

export default new Rollbar({
  accessToken: rollbarClientSideToken,
  // and other configs
})
```

And in our isomorphic React app, we import this module 

```js
import rollbarInstance from './rollbar'

rollbarInstance.log('this is a test')
```

If we set the `maxItems` to 20 like this

```js
rollbarInstance.global({
  maxItems: 2
})
```

This will be fine for browser as the instance will be created per browser session. But what about server side? We initialise the Rollbar instance as a module on the server side, does setting this means there will be only `20` reports when we start our server?

I've tried to contact support from Intercom on Rollbar website. I get a suggestion from your support that do the check in `checkIgnore` function. I have some simple code like this:

```js
checkIgnore: (isUncaught, args, payload) => {

  // this will runs every single time we send a new report...
  if (isBrowser()) {
    rollbarInstance.global({
      maxItems: 2
    })
  }
}
```

With this, the global config will not enable for server. But the issue here is that we are setting `global` config on everything single `checkIgnore` run, as from the api I can't seem to be able to check whether we have set the `maxItems` yet.

### Possible improvement?

I'm wondering, if it makes sense, to modify the api or extend the global api, to have browser/server only settings, to allow user to have fine control of settings like this one.

Other than that, do you have any other suggestion on how can we can achieve this browser only setting requirement?

Sorry I'm not sure whether this is the right place to ask a question like this, but doing this with Intercom support on the website is definitely feel not right.

Cheers.

**Comment by rokob** [comment]
Your suggestion makes sense. Let me see if I can figure out a way to do this. To be honest the maxItems setting probably really only makes sense on the browser so maybe if we are on the server we will just ignore that settting. However, I am surprised this works for you because the client side access token shouldn't work on the server?

**Comment by fraserxu** [comment]
Isn't that supposed to can be enabled from the token settings?

![screen shot 2017-09-07 at 10 01 31 am](https://user-images.githubusercontent.com/1183541/30139831-ae0348da-93b3-11e7-9b0d-22e295e797a2.png)

👍  that it would be great to ignore that setting on server.
