### ISSUE TITLE
Version 2.2.7 is not published to npm

### ISSUE THREAD

**Issue by ento** [rollbar/rollbar.js#421]
https://changelog.rollbar.com/javascript-telemetry-scrubbing-32840 seems to indicate that version 2.2.7 is available for download, but the [npm registry](https://www.npmjs.com/package/rollbar) says "2.2.6 is the latest of 77 releases."

Trying to install 2.2.7 through npm results in an error as well.

> npm ERR! notarget No matching version found for rollbar@2.2.7

[The cdnjs version](https://cdnjs.cloudflare.com/ajax/libs/rollbar.js/2.2.7/rollbar.min.js) loads fine though.

Is it expected to see a bit of delay between the release to cdnjs and npm?

**Comment by rokob** [comment]
It is on npm now, there was an issue with npm before.
