### ISSUE TITLE
UMD build sets window.global = () => {...}, messing up my app

### ISSUE THREAD

**Issue by jonathanong** [rollbar/rollbar.js#433]
in the rollbar UMD build, i see this: `r.global=function(t){return w?w.global(t):void o()}`. what's up with that? if i load it in the browser, i see:

![screen shot 2017-09-18 at 5 18 47 pm](https://user-images.githubusercontent.com/643505/30570332-7266c0aa-9c95-11e7-9738-35ff67835663.png)

should i be using a different file for a global `Rollbar`?

**Comment by rokob** [comment]
The minified code you are referring to is from https://github.com/rollbar/rollbar.js/blob/master/src/browser/rollbar.js#L52,L62 Nothing is getting set on the window, `w` here is the managed instance `_instance`, `r` is just Rollbar, and `global` is a function for setting configuration values. This is the right file to use, but if you are including minified code with other minified code, you probably need to use the unminified build via whatever module loader you are using and then minifying everything together.

**Comment by jonathanong** [comment]
the screenshot above is from me typing `global` in the browser.

what's the correct file to use as a `<script src="..."></script>` src?

**Comment by rokob** [comment]
Huzzah yes that is a bug, will fix, sorry about that.
