### ISSUE TITLE
SourceMaps: Rollbar still tries to download sourcemaps even when prior upload performed

### ISSUE THREAD

**Issue by MayasHaddad** [rollbar/rollbar.js#441]
Hi,

I'm having a bit of a hard time getting rollbar to print original source code in stacktraces 😔

I use the [wepback plugin](https://github.com/thredup/rollbar-sourcemap-webpack-plugin) thus going for the prior upload way as documented [here](https://rollbar.com/docs/source-maps/) "Recommended Method: Upload pre-deploy"

following this:
> For example, let's say Rollbar received an exception that had a code_version of 12345 and a frame with the filename https://myapp.com/assets/js/abc.js. Rollbar can only de-minify the frame if it finds a source map with the exact minified url //myapp.com/assets/js/abc.js and code_version of 12345.

I provide the commit id hash both at sourcemap upload time and browser side rollbar configuration as a `code_version`.

I also provide the correct "minified url".

But still, rollbar attempts to download the `.map` file from my server and complains about the missing `//# sourceMappingURL=yourapp.min.map` comment.

<img width="1024" alt="screen shot 2017-09-22 at 11 14 08 am" src="https://user-images.githubusercontent.com/1893921/30738242-c2bcba18-9f89-11e7-88ee-1ac8ac138cec.png">

<img width="1072" alt="screen shot 2017-09-22 at 11 42 32 am" src="https://user-images.githubusercontent.com/1893921/30738836-a64a40ec-9f8b-11e7-8dd0-d2b94b902935.png">

Am I missing something here?

**Comment by rivkahstandig3636** [comment]
@MayasHaddad Are you still experiencing this issue? If so, please email us at support@rollbar.com, as this isn't actually a rollbar.js issue :)

**Comment by MayasHaddad** [comment]
apologies 🙏 the issue wasn't related with rollbar indeed
