### ISSUE TITLE
Add failure callback for Rollbar.log()

### ISSUE THREAD

**Issue by MatthewAry** [rollbar/rollbar.js#442]
Right now there is a success callback for the Rollbar.log() method but there is no failure method. In the event that Rollbar.log fails to send the message to Rollbar, I might want to tell my customer to contact me for support, otherwise, I might want to tell them that I've been notified about the issue.

**Comment by rokob** [comment]
The callback has the standard signature of `function(error, result)` if the callback gets called with a non-null first argument then some type of failure happened.
