### ISSUE TITLE
Show the details of the requests in the Telemetry

### ISSUE THREAD

**Issue by alexeybondarenko** [rollbar/rollbar.js#444]
[Syft](https://syftapp.com) API sends the `X-Request-ID` header to the client. It can be used to debug the request/response in API logs. It would be nice to see it in the telemetry.

It would be nice to have the configuration of the network option of autoInstrument to specify the request/response properties to show in the Telemetry rows.

**Comment by rokob** [comment]
I'm going to do this is #454 as these are related.
