### ISSUE TITLE
Uncaught TypeError: rollbar.error is not a function

### ISSUE THREAD

**Issue by tapas08** [rollbar/rollbar.js#446]
Hello,
I am trying to integrate rollbar in angular2 app and followed [this solution](https://gist.github.com/saschwarz/bee0618f5604646dfe56ca61124e5122) for setting up rollbar.
But when it tries to log error to rollbar it throws error saying
`Uncaught TypeError: rollbar.error is not a function`
Thanks.

**Comment by tapas08** [comment]
Can anyone please help?
A guy from rollbar team on stackoverflow told me to post my issue here saying the rollbar team monitors for new issues and will help with the issue!

**Comment by rokob** [comment]
What version of Rollbar and what version of Angular are you using? I just created this app https://github.com/rokob/angularbar which uses the code that you linked to integrate Rollbar. I ran it both in dev and prod modes and both send an error to rollbar via the rollbar.error call. I added an `<li>` tag at the root page with the title `Throw` that throws an error when clicked.

**Comment by racedale** [comment]
@rokob The way you used [InjectionToken](https://github.com/rokob/angularbar/blob/master/src/app/rollbar.ts#L31) was key to me fixing a similar error, "Internal error: unknown identifier null".  This needs to be added to the docs for how to use Rollbar with Angular2/4, because it is currently missing!

**Comment by gofreddo** [comment]
Please update the documentation with the example from https://github.com/rokob/angularbar.  I wasted an hour trying to find this solution.

**Comment by rokob** [comment]
👍
