### ISSUE TITLE
Node Security Package (nsp) has advised that debug be updated to 2.6.9 or greater

### ISSUE THREAD

**Issue by cp4r3z** [rollbar/rollbar.js#451]
https://nodesecurity.io/advisories/534

**Comment by brianr** [comment]
Thanks @cp4r3z - this is already fixed in master (see https://github.com/rollbar/rollbar.js/pull/448 ). We'll have a new release out ~this week.

**Comment by cp4r3z** [comment]
@brianr Ah, I just came back to check the closed issue list and saw your comment. Thanks!

**Comment by rokob** [comment]
Released as v2.2.9
