### ISSUE TITLE
rollbar cdn javascript react doesn't report environment

### ISSUE THREAD

**Issue by adinu** [rollbar/rollbar.js#452]
for some reason, in the last month Rollbar client stopped reporting environment. 

when i tried doing the test report (window.onerror("TestRollbarError: testing window.onerror", window.location.href) i still don't get environment details.

i have tried using:
 var _rollbarConfig = {
    payload: {
      environment: window.env
    }

and saw that "window.env" is working.

i am using this version:
https://cdnjs.cloudflare.com/ajax/libs/rollbar.js/2.2.8/rollbar.min.js

**Comment by jessewgibbs** [comment]
Hey there,

Is the value `env` being set in your code, or is this something that Rollbar used to set up but no longer does?

Also, when Rollbar was previously working, were you also using v 2.2.8?
