### ISSUE TITLE
Optionally show body of request and response in telemetry XHR entries

### ISSUE THREAD

**Issue by jessewgibbs** [rollbar/rollbar.js#454]
From a customer via support:
> with our current configuration rollbar is capturing the url of get and post requests and the response code but if its capturing the body of the request and response i cant see it in the telemetry UI

**Comment by nezoomie** [comment]
+1

**Comment by yurygnutov** [comment]
+1

**Comment by jessewgibbs** [comment]
+1 from me too =) - I'm investigating a Rollbar issue where additional data in telemetry would be useful.

**Comment by rokob** [comment]
We are not currently capturing the body, we could do this. However, I am going to err on the side of making it configurable but off by default. There is the potential for a massive blowup in the payload side as well as data to leak.
