### ISSUE TITLE
Error in documentation: "TypeError: window.onerror is not a function"

### ISSUE THREAD

**Issue by pmourlanne** [rollbar/rollbar.js#458]
In the documentation, to test things out, you write:
```
Type the following code into the console and press enter: window.onerror("TestRollbarError: testing window.onerror", window.location.href)
```
Doing this in Firefox raises a `TypeError: window.onerror is not a function`. This is because window.onerror is not accessible from the console.

In the end, I checked that the rollbar integration worked with this:
```
setTimeout(function() {notThere();}, 1000);
```
You could use a snippet like this in your documentation :)

**Comment by rivkahstandig3636** [comment]
Thanks for the info @pmourlanne! We'll update the docs.
