### ISSUE TITLE
onreadystatechange not being called

### ISSUE THREAD

**Issue by thomask** [rollbar/rollbar.js#462]
Hi,

Our library uses `XMLHttpRequest`. In order to fire callbacks, we depend on `onreadystatechange`. We have done some testing and found that the handler is not being called whenever Rollbar is on the page.

We noticed this because our library stopped working for one of our clients somewhere between 2017-09-08 and 2017-09-10. Now, this might of course be a coincidence, but I can see code being merged on 2017-09-09 that actually wraps `onreadystatechange` (https://github.com/rollbar/rollbar.js/pull/340/files/ed90db41b111dde1338de4a28c7a799b4aa2c56e#diff-2730e96c66b58c48a259f25cb8c82107R127).

Simplified version of our library's ajax function:

```js
function ajax(url, data, method, callback) {
        // Do things

        var xhr = new XMLHttpRequest();
        if ("withCredentials" in xhr){
            xhr.open(method, _url, true);
        } else if (typeof XDomainRequest != "undefined"){
           // More stuff
        } 

        xhr.onreadystatechange = ensureReadiness;

        function ensureReadiness() {
            // Do stuff.. Not being called when Rollbar is present
        }

        xhr.send(data);
}
````
Could you please look into this? Thanks!

**Comment by rokob** [comment]
There was a bug in the way that wrapped `onreadystatechange` which was fixed in a subsequent release.

**Comment by thomask** [comment]
Does that mean our client has to upgrade their Rollbar version?

**Comment by rokob** [comment]
That would probably resolve the issue. It was a problem in v2.2.0 but anything v2.2.1 or higher should not have the same issue. So if they are on v2.2.1+ then it would be something else I am unaware of.

**Comment by thomask** [comment]
Thanks, we have adviced the customer.

**Comment by thomask** [comment]
Oh and Blue skies! ;)
