### ISSUE TITLE
window.Rollbar not always available on app boot

### ISSUE THREAD

**Issue by rgoldfinger** [rollbar/rollbar.js#463]
I've been having a number of issues with the notifier sometimes seeming to:
- not respect the global `maxItems` setting,
- not use the `transform` function, and
- not use the `checkIgnore` function. 

I've been setting these at boot using `window.Rollbar.configure({ ...` etc. I added some logging, and it looks like I'm having these issues because `window.Rollbar` is only sometimes available at app boot.

**Comment by rokob** [comment]
How are you loading Rollbar, with the snippet? Bundled in your own js?

**Comment by rgoldfinger** [comment]
With the snippet, which is included in the html. Here's what I'm using for that, along with my checks to see that the `transform` etc functions are getting called here rather than from `Rollbar.configure`

https://gist.github.com/rgoldfinger/b1dfe3994a887743b1b620b3a0336430

**Comment by rokob** [comment]
I'm looking into this right now, I have a few ideas what could be going on, I am just testing the details. I should have a fix up within a day.

**Comment by rokob** [comment]
Here is the sequence of events that should occur when loading Rollbar with the snippet:

1. Before the script block with the snippet is encountered, window.Rollbar is undefined
2. After the script block with the configuration and snippet is encountered, window.Rollbar is a shim object that understands all of the methods as the full notifier object but mostly acts as a queue for capturing these method calls. The snippet makes an asynchronous request to load the full notifier.
3. The full notifier loads and all method calls to Rollbar are replayed (in the order they were called on the shim) on the full object, including calls to configure.

The key being that the order of the calls are respected. This means that if an error is thrown between the snippet block and the calls to Rollbar.configure, then the settings used will be those set in the initial configuration.

Take this example

```
<script>
var _rollbarConfig = {
        accessToken: "POST_CLIENT_ITEM_TOKEN",
        captureUncaught: true,
        checkIgnore: function(a, b, c) {
          console.log("CONFIG checkIgnore");
          return true;
        },
        transform: function(p) {
          console.log("CONFIG transform");
        },
        payload: {
          environment: "test"
        },
      };
      // Rollbar Snippet
      ...
</script>
<script>
      throw new Error("BORK BORK");
</script>
<script>
     Rollbar.configure({
        checkIgnore: function(a,b,c) {
          console.log("AFTERWARDS checkIgnore: ");
          return true;
        },
        transform: function(p) {
          console.log("AFTERWARDS transform");
        }
      });
</script>
<script>
      throw new Error("ANOTHER ONE");
</script>
```

You will see in the console

```
Uncaught Error: BORK BORK
Uncaught Error: ANOTHER ONE
CONFIG transform
CONFIG checkIgnore
AFTERWARDS transform
AFTERWARDS checkIgnore
```

If `window.Rollbar` is undefined strictly after the snippet has executed then I have no idea what is going on. There is an issue with `maxItems` not getting set properly via the constructor which I have a simple fix for. However, I haven't been able to find a scenario where `window.Rollbar` is undefined after the snippet has run.

The only thing I can think of is that maybe there is an issue with the order of execution of script blocks in some browsers. But my understanding of the spec is that a static script block that is not marked with async or defer is executed in the order the parser sees it. Dynamically injected script blocks are sometimes sync and sometimes async depending on the browser, and async and defer do other things. But, if you have `_rollbarConfig = ...; // snippet` in the head of an html document statically from the view of the browser, then there is no way that javascript code running after that block will have `window.Rollbar` undefined.

**Comment by rivkahstandig3636** [comment]
@rgoldfinger Is this still an issue for you?

**Comment by rgoldfinger** [comment]
No, I don't think so. I think my confusion was that when errors are thrown before `Rollbar.configure` is run, they don't seem to respect the options I passed there. Since using `Rollbar.configure` is unreliable, it'd be nice if the documentation was updated to reflect this, and direct users to use the initial rollbar config instead.
