### ISSUE TITLE
Can't execute from a freed script 

### ISSUE THREAD

**Issue by and-megan** [rollbar/rollbar.js#464]
the only frame is a _rollbar_wrapped frame

Could be related: https://github.com/bugsnag/bugsnag-js/issues/203

It could be related to wrappers holding references to things that are subsequently removed from the page, that’s a really hard one if that is what is happening. there might not be a way fully around that, but perhaps we could expect this error and code around it? i.e. still report whatever useful info we can about the original error

limited googling about it leads me to believe it is one of those scary older browser and iframe things

**Comment by rokob** [comment]
The only fix for this is to turn off auto instrumenting or at least dom instrumentation. I'm going to close this out as there isn't much we can do.
