### ISSUE TITLE
Convenience handler support for Google Cloud Functions

### ISSUE THREAD

**Issue by erikaxel** [rollbar/rollbar.js#465]
Hi,

It would be great to have a convenience handler for Google Cloud Function in the same way as you support AWS Lambda functions.

**Comment by simlu** [comment]
Take a look at https://github.com/simlu/lambda-rollbar - should be relatively easy to modify it for your purpose.

**Comment by coryvirok** [comment]
@simlu your wrapper looks great! We'd love a PR if you want to include it in the SDK. :)

**Comment by rivkahstandig3636** [comment]
Hi there, I’m closing out all issues opened before 2018 that haven’t had any activity on them since the start of this year. If this is still an issue for you, please comment here and we can reopen this. Thanks!

**Comment by fgilio** [comment]
It'd be really helpful to have this built in
