### ISSUE TITLE
Error Stack not being reported corectly.

### ISSUE THREAD

**Issue by kwstoikonomou** [rollbar/rollbar.js#467]
an error occurs in a js of my project. 
Here is the error as seen in the console of my browser: 
![image](https://user-images.githubusercontent.com/13237811/31719190-44b57f14-b41b-11e7-8c2c-9f42728f4c25.png)

But Rollbar reports this on the dashboard:
![image](https://user-images.githubusercontent.com/13237811/31719221-58e62786-b41b-11e7-9a33-bfade8d23ce1.png)

It is my understanding that (unknown): script errors occur when the file is loaded through CORS and you dont have line info. (https://rollbar.com/Rollbar/rollbar.js/items/134/solutions/)
But the file is on the same domain with my website (Different sub-domain though, but that should not affect CORS)

**Comment by rokob** [comment]
The host includes any subdomains: https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy

**Comment by kwstoikonomou** [comment]
@rokob i did not get what you mean. The point is that this unknown errors should only occur when the js file is loaded through CORS not from another host.

**Comment by rivkahstandig3636** [comment]
@rokob Can you clarify?

**Comment by rokob** [comment]
> But the file is on the same domain with my website (Different sub-domain though, but that should not affect CORS)

Another subdomain is a different host, this _is_ due to CORS.
