### ISSUE TITLE
Error: "Rollbar is not enabled"

### ISSUE THREAD

**Issue by simlu** [rollbar/rollbar.js#482]
Why was this error introduced? Extremely confusing...

E.g. How are we supposed to get coverage in our tests now?

**Comment by simlu** [comment]
This was changed in https://github.com/rollbar/rollbar.js/commit/a9864a43036e6357060172bbe3c2ce75100230c4 (Issue: https://github.com/rollbar/rollbar.js/issues/280)

**Comment by simlu** [comment]
I've opened a pull request. Looking forward to some feedback....

**Comment by rokob** [comment]
This does not throw an error, it calls your callback with an error if you call log and have Rollbar not enabled. This is the semantics required of the callback when we do not process a log call. It is not clear why this would have an effect on your tests.

**Comment by simlu** [comment]
I don't use a callback. I'm using rollbar.wait instead... I think in that case it does throw an error? Let me double check where the error comes from.

**Comment by simlu** [comment]
Yeah, this seems to be thrown from the rollbar.wait - urg

**Comment by rokob** [comment]
The only time we throw from wait is in the lambda handler which is just a rethrow to allow for any other higher level error handling to still take place and to fail the request otherwise rather than swallowing errors.

**Comment by simlu** [comment]
Removing `endpoint: "https://api.rollbar.com/api/1/",` from the options magically solved this. Wow, those were some bizarre errors. Apologies for not checking the change-log earlier.

**Comment by rokob** [comment]
Sorry yeah, I wasn't happy about breaking that, but I needed it to get this library to match the semantics of rollbar-ios and rollbar-android so I could mix these together for React Native. I thought about going to 3.0.0 for it, but it seemed like bumping from 2.2.x to 2.3.0 should be enough.

**Comment by simlu** [comment]
Makes perfect sense. React Native looks very promising. We're investigating it as well.

Suggestion: Possible to log a warning if somebody is using the old endpoint semantics? E.g. check with a regex? I wouldn't be surprised if other ppl run into this as well.
