### ISSUE TITLE
reportMessageWithPayloadData deprecated

### ISSUE THREAD

**Issue by simlu** [rollbar/rollbar.js#484]
What are we supposed to use instead?

**Comment by rokob** [comment]
https://github.com/rollbar/rollbar.js#rollbarlog
https://github.com/rollbar/rollbar.js#rollbardebug-info-warn-warning-error-critical

**Comment by simlu** [comment]
Thank you!

**Comment by simlu** [comment]
I'm confused. So we don't have access to the payload data anymore. Where would the lambda context object go then?

**Comment by simlu** [comment]
@rokob I'm confused. So we don't have access to the payload data anymore. Where would the lambda context object go then?

**Comment by rokob** [comment]
If you pass an object to one of `log/debug/info/warning/error/critical` it will end up as the `custom` key in the final payload. You can also set an object in the configuration under the `payload` key which will get merged into all payloads that get sent.

**Comment by simlu** [comment]
Ok, just making sure I understand correctly with my example. Ih ave
```javascript
rollbar.reportMessageWithPayloadData(err.message, {
      level,
      custom: { 
        data: ...
        err: ...
      }
    }, { <-- request object -->
      headers: event.headers,
      protocol: get(event, 'headers.X-Forwarded-Proto'),
      url: ...,
      method: event.httpMethod,
      body: event.body,
      route: {
        path: get(event, 'requestContext.path')
      }
    });
```

would translate to

```javascript
rollbar[level](err.message, err, { data: ... })
```
and then then how do I make sure the former request object gets picked up correctly?

**Comment by rokob** [comment]
Yeah so this is a bit magical, but sorry I put the wrong link above (https://github.com/Rollbar/rollbar.js/#rollbarlog-1) this is the server side one. If you pass an object that has a certain set of keys:

```
headers: an object containing the request headers
protocol: the request protocol (e.g. "https")
url: the URL starting after the domain name (e.g. "/index.html?foo=bar")
method: the request method (e.g. "GET")
body: the request body as a string
route: an object containing a 'path' key, which will be used as the "context" for the event (e.g. {"path": "home/index"})
```

then we will take that to be the request.

**Comment by simlu** [comment]
That finally seems to work. Thank you very much for your help!

Also you might want to put a note that putting `endpoint: "https://api.rollbar.com/api/1/"` now breaks things (if you haven't already). Took me a while to figure that out.

**Comment by rokob** [comment]
https://github.com/rollbar/rollbar.js/blob/master/CHANGELOG.md#v230

**Comment by simlu** [comment]
Right, I obviously didn't get there. Thanks, I'll check it out first next time :)
