### ISSUE TITLE
404 error for 2.3.0 rollbar.min.js on Cloudflare CDN

### ISSUE THREAD

**Issue by barrywoolgar** [rollbar/rollbar.js#487]
Hello

Just in case you're not aware of this, the URL embedded in the 2.3.0 version of the JS snippet is returning a 404 at the moment:

`https://cdnjs.cloudflare.com/ajax/libs/rollbar.js/2.3.0/rollbar.min.js`

The previous version is being returned as expected:

`https://cdnjs.cloudflare.com/ajax/libs/rollbar.js/2.2.10/rollbar.min.js`

Thanks

**Comment by jessewgibbs** [comment]
@rokob I was able to reproduce this.  Looks like CDNJS didn't get properly updated for the 2.3.0 release?

**Comment by barrywoolgar** [comment]
Thanks, the 2.3.1 release works (as does the 2.3.0 one now too).
