### ISSUE TITLE
Callback not called on nodejs

### ISSUE THREAD

**Issue by jcurlier** [rollbar/rollbar.js#489]
We are using rollbar to report our errors through a direct call to the `error` method as well as the Express middleware.

When an error occurs, sometimes we log them twice, once with the direct call and once with the middleware. In such case, the `next()` method of the middleware is not called as the code determines that this error was already logged (`_sameAsLastError`).

We should review the method:
https://github.com/rollbar/rollbar.js/blob/master/src/rollbar.js#L97

If a callback exist, we should call it before returning, ie I am proposing:
```
Rollbar.prototype._log = function(defaultLevel, item) {
  if (this._sameAsLastError(item)) {
    if (item.callback) item.callback();
    return;
  }
```

**Comment by rokob** [comment]
Ah yes you are right, we definitely should call the callback no matter what.

**Comment by jcurlier** [comment]
Created the PR #490
