### ISSUE TITLE
No source maps published for the .min.js dist bundles?

### ISSUE THREAD

**Issue by papandreou** [rollbar/rollbar.js#491]
As per https://github.com/rollbar/rollbar.js/blob/626aac317d7879a3ecf62b71b0cadfa0dcc226b4/package.json#L10 I'm using `dist/rollbar.umd.min.js` in production. I just ran into a scenario where an error occurred in rollbar itself, and I discovered that there's no `sourceMappingURL` ref in the file and no `rollbar.umd.min.js.map` either.

Seems like that goes for *.min.js in the dist dir: https://github.com/rollbar/rollbar.js/tree/master/dist

I'm assuming this is by accident?

**Comment by rokob** [comment]
This is the reason we don't: 

https://github.com/rollbar/rollbar.js/blob/master/webpack.config.js#L10,L12

But I am not sure how relevant that comment is anymore.

**Comment by rokob** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1020846 makes me think that is probably the "bug" which has been fixed since FF 33, so we should probably be able to turn source maps back on
