### ISSUE TITLE
Apply console formatting in telemetry messages

### ISSUE THREAD

**Issue by jessewgibbs** [rollbar/rollbar.js#493]
Asked in https://app.intercom.io/a/apps/rlisg82q/respond/inbox/487663/conversations/12675792751: 
> We use Bows (https://github.com/latentflip/bows) to format our console messages. In Rollbar, the formatting (color/font) shows up at the beginning of each line e.g. `color: hsl(267.35248304928183,99%,40%); font-weight: bold`. Any chance Telemetry can apply this formatting, or allow us to filter/remove it?

**Comment by rivkahstandig3636** [comment]
Hi there, I’m closing out all issues opened before 2018 that haven’t had any activity on them since the start of this year. If this is still an issue for you, please comment here and we can reopen this. Thanks!
