### ISSUE TITLE
Add ability to pass custom data in the body using Rollbar log methods 

### ISSUE THREAD

**Issue by and-megan** [rollbar/rollbar.js#494]
If you call Rollbar.info() or Rollbar.error() etc, could we edit these functions to send custom data nested under the body key?

I.e. Rollbar.error(err, {'body': {'custom_key': 'custom_value'}}) would result in the below example in the final payload

{
  "body": {
    "message": {
      "body": "Testing123"
    } ,
    "custom_key": "custom_value"
  ...
}

**Comment by rivkahstandig3636** [comment]
Hi there, I’m closing out all issues opened before 2018 that haven’t had any activity on them since the start of this year. If this is still an issue for you, please comment here and we can reopen this. Thanks!
