### ISSUE TITLE
Content Security Policy error: not posting to rollbar

### ISSUE THREAD

**Issue by ggrillone** [rollbar/rollbar.js#495]
**Relevant code:**

```
import { init } from 'rollbar'

this.rollbar = init({
    accessToken: rollbarToken,
    captureUncaught: true,
    payload: {
      environment: 'development'
    }
})

window.onerror("TestRollbarError: testing window.onerror", window.location.href)
```

**Error =>**

```
rollbar.umd.min.js:2 Refused to connect to 'https://api.rollbar.com/api/1/item/' because it violates the following Content Security Policy directive: "connect-src 'self' ws://localhost:18000 http://localhost:18000".
```

**Comment by rokob** [comment]
That looks like expected behavior with those CSP settings.

**Comment by ggrillone** [comment]
could you elaborate? thanks

**Comment by rokob** [comment]
You specified in your CSP setting to only allow self (i.e. same origin) and localhost, so you can't make post requests to api.rollbar.com. You would need to allow xhr requests to api.rollbar.com or proxy the rollbar requests through you same origin server by setting the endpoint in the configuration. Either way this is an issue with your specific configuration not an issue with Rollbar itself.

**Comment by ggrillone** [comment]
thanks, closing
