### ISSUE TITLE
Prettier/more explicit option to pass callbacks for uncaught exceptions

### ISSUE THREAD

**Issue by and-megan** [rollbar/rollbar.js#500]
It'd be great to have a more explicit configuration option for a callback to be fired when an exception is uncaught. We currently have an explicit way to pass callbacks when an exception is handled. 

checkIgnore works fine for now.

**Comment by rivkahstandig3636** [comment]
Hi there, I’m closing out all issues opened before 2018 that haven’t had any activity on them since the start of this year. If this is still an issue for you, please comment here and we can reopen this. Thanks!
