### ISSUE TITLE
console.log items showing up as rollbar.umd.min.js:2 instead of actual line

### ISSUE THREAD

**Issue by brucek** [rollbar/rollbar.js#506]
As touched on in #476, console.log is being captured by rollbar.js even with `autoInstrument: { log: false }`

This works in 2.2.3 but is broken as of 2.2.4 looks like.

Note I am using require.js and the UMD distro

**Comment by rokob** [comment]
I am confused, this should be broken in 2.2.3 and fixed in 2.2.4

**Comment by brucek** [comment]
I agree it is strange, but I can use 2.2.3 and my console log output looks fine.  Then when I move to 2.2.4 or higher, it starts incorrectly numbering console.log lines.  I am running:

Google Chrome 62.0.3202.94 (Official Build) (64-bit)
OSX 10.12.6 (16G1036)

**Comment by brucek** [comment]
nope, latest require.js (2.3.5) didn't help :-(

**Comment by rokob** [comment]
With the default auto instrument setting you should see the console log lines coming from Rollbar. With `autoInstrument: { log: false }` (and v2.2.4+) you should see the normal log lines restored. Let me see what is going on.

**Comment by brucek** [comment]
OK wait - I had a later call to rollbar.configure that looks like it was messing things up - I'll figure out how to update it.  Sorry for the false alarm.

**Comment by alastair-todd** [comment]
Same issue but `configure `only takes one argument?

Alternative:

`rollbar.configure({...currentConfig, ...extraConfig});`
