### ISSUE TITLE
Docs about fields scrubbed by default are inaccurate.

### ISSUE THREAD

**Issue by serhalp** [rollbar/rollbar.js#507]
The [docs here](https://github.com/rollbar/rollbar.js#context-1) claim:
> Default: `["passwd", "password", "secret", "confirm_password", "password_confirmation"]`

but the source code claims otherwise - there are [35 fields scrubbed by default on servers](https://github.com/rollbar/rollbar.js/blob/f0140a050c270981cfb980c9aa492a2d032fcb2f/package.json#L136-L160) and [14 in browsers](https://github.com/rollbar/rollbar.js/blob/f0140a050c270981cfb980c9aa492a2d032fcb2f/package.json#L106-L119).

In addition the docs make no mention of this browser/server difference.

**Comment by rivkahstandig3636** [comment]
Thanks for the feedback! We'll update the docs.

**Comment by rivkahstandig3636** [comment]
@rokob It's unclear to me if we do in fact need to update our documentation here or if this has been fixed.

**Comment by rokob** [comment]
The docs need to be updated

**Comment by rivkahstandig3636** [comment]
Okay thanks, I'll make a note to update these.

**Comment by rivkahstandig3636** [comment]
Closed via #570
