### ISSUE TITLE
Field scrubbing *mutates* logged objects!

### ISSUE THREAD

**Issue by serhalp** [rollbar/rollbar.js#509]
The feature that scrubs fields detected to be "sensitive" – [which suffers from false positives](https://github.com/rollbar/rollbar.js/issues/508), is [poorly documented](https://github.com/rollbar/rollbar.js/issues/507), and seemingly cannot be disabled(?) – actually _mutates_ these properties on the logged objects. This is a pretty egregious breach of expected conventional node module behavior. If this is intentional (I hope not...), it should be very clearly indicated in the documentation.

The combination of this mutation bug and [the false positive bug](https://github.com/rollbar/rollbar.js/issues/508) made for a pretty nasty (though admittedly fascinating) bug, that I could easily see happening to others. We're using the [cookie-session](https://github.com/expressjs/cookie-session) middleware, which populates the contents of a user cookie on `req.session`. We attach a part of this user context to our logger, which ships errors to Rollbar with that context. The cookie-session middleware's behavior is to set a `set-cookie` header on the response when `req.session` has been changed. These bugs led to, when an error is logged, a boolean property named `tempWorker` being mutated to "********", which sent an updated corrupted cookie down to the browser, which was persisted then sent back on subsequent requests, which led to authentication errors. Oof.

Looks like [the mutation is in the `traverse` function](https://github.com/rollbar/rollbar.js/blob/f0140a050c270981cfb980c9aa492a2d032fcb2f/src/utility.js#L156) and it does seem like the behavior [was somewhat intentional](https://github.com/rollbar/rollbar.js/blob/f0140a050c270981cfb980c9aa492a2d032fcb2f/src/server/transforms.js#L175)...

I could open a PR if creating a deep clone of the object and returning a scrubbed copy in `scrub()` sounds good. Thanks!

**Comment by rokob** [comment]
Yikes, there are several issues here which you have brought up that should be resolved. Sorry about this. I am working on fixing these right now.
