### ISSUE TITLE
add rollbar.commonjs.js to npm (+ UMD)

### ISSUE THREAD

**Issue by twhid** [rollbar/rollbar.js#51]
Be nice to be able to add it to a package.json file. Unless I'm mistaken, one is currently required to manually download and keep updated.

Also, any reason not to UMD it and just have 1 dist?

Thanks!

**Comment by mbrevda** [comment]
Any update here? Requing rollbar for the browser via npm would be quite helpfull

**Comment by dozoisch** [comment]
I would love having a npm package also. I don't want to bring bower in my build chain for no reason. For now I ended up copying the dist in my own src folder... but that is not optimal!

rollbar-browser would be perfect. And to answer, they don't care if it's a browser or backend package!

Also, by putting `main: 'dist/rollbar.umd.nojson.min.js'` in the package.json it will enable the following `var Rollbar = require('rollbar-browser');` directly

**Comment by brianr** [comment]
Hey all - thanks for the request -this is now high on our todo list. Should happen either this week or next. We'll update here with any news.

**Comment by coryvirok** [comment]
https://www.npmjs.com/package/rollbar-browser

**Comment by dozoisch** [comment]
:tada: awesome!

**Comment by twhid** [comment]
woohoo :100:

**Comment by mbrevda** [comment]
Hey - thanks so much! 

Im not sure it it's actually necessary to link directly to the minified code here. I would guess that most projects packing their own code are also minifing. Linking directly to the minified version means extra work (i.e. to including things like sourcemaps). Might want to consider pointing `main` at a non min version.
