### ISSUE TITLE
Lambda: captureUncaught and captureUnhandledRejections

### ISSUE THREAD

**Issue by simlu** [rollbar/rollbar.js#512]
Do the options captureUncaught and captureUnhandledRejections have any purpose when running in a lambda environment? Just checking that setting them both to false is not a problem.

Cheers, L~

**Comment by rokob** [comment]
No they have no purpose. As far as I know the Node.js environment in AWS Lambda does not support the event handlers required to implement capturing all uncaught exceptions and unhandled rejections. Therefore those settings should have no meaning in lambda.
