### ISSUE TITLE
userAgent undefined when it shouldn't be

### ISSUE THREAD

**Issue by and-megan** [rollbar/rollbar.js#513]
Rollbar.js v2.3.1

There's no user agent data being passed in the occurrence. Seeing these two logs in the telemetry data:
`TypeError: undefined is not an object (evaluating 'navigator.userAgent.toLowerCase')`
`Rollbar: undefined is not an object (evaluating 'navigator.userAgent.toLowerCase')`

Normally, would blame on bots, but there's a backup page tracker that has no problem getting the useragent data, which can be linked to Rollbar occurrences. 

internal:
https://app.intercom.io/a/apps/rlisg82q/respond/inbox/488687/conversations/13203078795

**Comment by rokob** [comment]
I don't see how this is possible to even evaluate `navigator.userAgent.toLowerCase`, we never call `toLowerCase` on userAgent. I made some changes in v2.3.2 which was defensive about navigator being undefined. But there never has been code that would result in this error.

**Comment by rokob** [comment]
I'm going to close this because I'm almost certain this is a bot doing something weird.
