### ISSUE TITLE
script prevents mouse wheel scrolling for Windows 10 + Chrome 61

### ISSUE THREAD

**Issue by and-megan** [rollbar/rollbar.js#516]
Users with Windows 10 + Chrome 61 cannot use the mouse wheel to scroll on a page where rollbar.js is installed. 

If we do not include the rollbar JavaScript code then the mouse wheel does work again. 

internal:
https://app.intercom.io/a/apps/rlisg82q/respond/inbox/488687/conversations/13242126057

**Comment by marcelgleis** [comment]
This is really urgent for us because it affects 10% of our visitors...

**Comment by rokob** [comment]
I still have no idea what this is.

**Comment by jessewgibbs** [comment]
Closing this since we've not had any reports of it in a long time.
