### ISSUE TITLE
"maxItems has been hit" but maxItems is 0

### ISSUE THREAD

**Issue by ento** [rollbar/rollbar.js#517]
I'm puzzling over this item:

```json
{
  "body": {
    "message": {
      "body": "maxItems has been hit. Ignoring errors until reset.", 
      "extra": {
        "maxItems": 0
      }
    }
  }, 
  "uuid": "9ec743c7d863436297f04f546201897e", 
  "language": "javascript", 
  "framework": "browser-js", 
  "timestamp": 1512490406, 
  "environment": "production", 
  "platform": "browser", 
  "notifier": {
    "version": "2.3.1", 
    "name": "rollbar-browser-js"
  }, 
  "metadata": {}
}
```

I'm guessing this is coming from this line:
https://github.com/rollbar/rollbar.js/blob/218ac44acef14996f83a61bb2c6a477a15418887/src/rateLimiter.js#L76

- the second check for `globalRateLimitPerMin` in `RateLimiter.prototype.shouldSend` failed
- `rateLimitPayload` gets called to build the error payload
- `rateLimitPayload` assumes that the `globalRateLimit` was hit

**Comment by rokob** [comment]
Yeah that is a bug I have on my radar to fix, the payload is just specifying the wrong limit which got hit as you describe.

**Comment by jpike88** [comment]
Just encountered this for the first time after months of usage, seems totally random.
