### ISSUE TITLE
SecurityError in rollbar.js itself, Edge on Windows Phone

### ISSUE THREAD

**Issue by papandreou** [rollbar/rollbar.js#518]
Hi!

We've just had a weird error reported through the rollbar service:

```
(unknown): SecurityError
1
File "webpack:////tmp/build_460fe1f89b07179f4a198c7dbce7469d/node_modules/rollbar/dist/rollbar.umd.min.js" line 2 col 17985 in [anonymous]
}try{o=t.detail,!n&&o&&(n=o.reason,r=o.promise)}catch(t){o="[unhandledrejection] error getting `d...
```

Which seems to map back to https://github.com/rollbar/rollbar.js/blob/3ad9e8cd4c6ca059dacfaff4dcb70f05c6288f70/src/browser/telemetry.js#L131 (again, this would have been easier if [source maps were available](https://github.com/rollbar/rollbar.js/issues/491) :)

It was triggered in Edge on a Windows Phone: Mozilla/5.0 (Windows Phone 10.0; Android 6.0.1; Microsoft; Lumia 650) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Mobile Safari/537.36 Edge/14.14393

We're running rollbar.js 2.3.2

It's occurrence 34302274687, in case that helps.

I'm bringing it up here because the problem comes from rollbar itself -- I hope you can help.

**Comment by rivkahstandig3636** [comment]
Hi @papandreou, Thanks for letting us know. I took a look at the three occurrences of this error that you have in your project, and only one of them has any frames. I believe this may be showing as an error in our code due to how we wrap functions in event listeners. Let us know if it comes up again.

**Comment by papandreou** [comment]
@rivkahstandig3636, I will, thanks. In the mean time, we can keep this issue open so others can discover it and chime in as well.

**Comment by papandreou** [comment]
... Or not, okay :)

**Comment by rivkahstandig3636** [comment]
If it comes up again it can always be reopened :)
