### ISSUE TITLE
Telemetry: ability to ignore certain network requests

### ISSUE THREAD

**Issue by brianr** [rollbar/rollbar.js#519]
(Via customer request.)

It'd be nice to be able to ignore certain network requests from the telemetry timeline, e.g. ignore requests made to certain hosts.

Why:

- drop minimally-useful telemetry events so they don't clutter the UI
- avoid using up the whole telemetry queue (which we cap at a hard max of 100) with such events

**Comment by msokk** [comment]
Would also love to have this. Our use case would be to filter out all mixpanel requests, as the each 4000 character payload is encoded into URL as base64. 

Blacklisting full url (with regexp) support would make sense or maybe even more generic callback based filter would make sense? `filterNetworkTelemetry(metadata): boolean`

**Comment by msokk** [comment]
Mixpanel made up 80% of our telemetry content so I went ahead and created a PR #521
