### ISSUE TITLE
Zero error frames when sending unthrown error with Rollbar.error() on IE 11

### ISSUE THREAD

**Issue by timdown** [rollbar/rollbar.js#523]
When sending an `Error` object that has not been thrown to Rollbar via `Rollbar.error()` on IE 11, zero frames in the error trace are sent. In other browsers, there are frames. Also, if you instead throw the error and allow Rollbar to catch it (presumably via `window.onerror`), you do get frames.

This is a problem for the `hostWhiteList`, which relies on the presence of frames. If there are none, as in IE 11 for an unthrown error, all Rollbar error notifications are suppressed.

I strongly suspect the underlying issue is that in IE, unlike other browsers, an `Error` object does not have a `stack` property until it's thrown. Therefore a potential workaround (both for you for future releases and for me now) is to throw and catch an error that has no `stack` property before attempting to parse the frames out of `stack` (and presumably filtering out extra frames that have resulted from throwing the error somewhere other than where it was created).

**Comment by rokob** [comment]
If the trace has no frames then the whitelist is ignored, it does not suppress errors without frames. https://github.com/rollbar/rollbar.js/blob/35df2f01e56fac6084f43a286f775703e72c2d1f/src/browser/predicates.js#L62,L64

**Comment by timdown** [comment]
The line you linked to says that if `frames` is falsy then errors are not suppressed but an array with zero elements (which is indeed what you get in IE 11 with an unthrown error) is not falsy.

**Comment by rokob** [comment]
Ahhh
