### ISSUE TITLE
Usage with Create React App error(s)

### ISSUE THREAD

**Issue by veddermatic** [rollbar/rollbar.js#524]
Make a new creat-react-app app. Then, follow the example here: https://github.com/rollbar/rollbar.js/tree/master/examples/webpack

```
// src/index.js:
const rollbarConfig = { ... }
const rollbar = require('./rollbar.umd.min.js');
const Rollbar = rollbar.init(rollbarConfig);
```
```
// src/otherFile.js:
export function blah() {
  Rollbar.error("Oh no!");
}
```

results in this in the following in the react console:

```
Failed to compile.

./src/rollbar.umd.min.js
  Line 1:  'define' is not defined         no-undef
  Line 1:  'define' is not defined         no-undef
  Line 2:  'ActiveXObject' is not defined  no-undef
  Line 2:  'ActiveXObject' is not defined  no-undef
  Line 2:  'ActiveXObject' is not defined  no-undef

Search for the keywords to learn more about each error.
```

If one installs `rollbar` via npm and updates to this:

```
// src/index.js:
const rollbar = require('rollbar');
// OR  import rollbar from 'rollbar';
// OR import { rollbar } from 'rollbar';
const rollbarConfig = { ... }
const Rollbar = rollbar.init(rollbarConfig);
// OR const Rollbar = new rollbar(rollbarConfig);
```

Then the react console gives this:
```
Failed to compile.

./src/someFile.js
  Line 28:  'Rollbar' is not defined  no-undef

Search for the keywords to learn more about each error.
```

Following the suggestion here: https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#using-global-variables

and appending `window.` to Rollbar  results in it compiling, but throwing an error at runtime that `window.Rollbar` is not defined.

Is this something dumb I am doing? Something with how create-reat-app configures webpack by default?

**Comment by veddermatic** [comment]
So I managed to get this working.  By using the npm version like so and explicitly adding it to window like so:

```
// src/index.js
import rollbar from 'rollbar';

const Rollbar = new rollbar(rollbarConfig);
window.Rollbar = Rollbar;
```

I was then able to use it like so in other files:
```
// src/otherFile.js
export function blah() {
 const RB = window.rollbar;
 try {
      aThingThatCouldFail()
  } catch(e) {
    RB.error("Oh no!");
  }
}
```

However, following the Webpack example still errors, and what I'm doing seems ugly.

**Comment by rokob** [comment]
The webpack example is old and is something I will just remove, it isn't a bug. The way you are doing it is one approach. If you want a global variable and you want to use a bundler then you need to manage the global variable yourself, i.e. via adding it to the window. You are trying to share something across files without using the module system to share references, hence the need to add something to the window yourself. There are other ways to do this, but it is dependent on the structure of your code and your webpack setup.

**Comment by kimochg** [comment]
FYI, the error about the `define` not defined comes from the umd js file. you can config your eslint file adding amd env to solve it
```
"env": {
    "amd": true
},
```
