### ISSUE TITLE
Custom Logger / No longer use bind

### ISSUE THREAD

**Issue by simlu** [rollbar/rollbar.js#526]
Is there a way to inject a custom logger (server) into rollbar.js? If not, how would we best support this?

The problem with the current [logger.js](https://github.com/rollbar/rollbar.js/blob/master/src/server/logger.js) is that we can't inject into the console since it uses bind.

So the option for my use case is either (1) use `function (...args) { console.log(...args); }` (PR) or (2) somehow inject a custom logger (which could then do that).

Suggestions?

*Use Case:*
I need to capture all console output for automatic analysis in testing. With the current rollbar setup the generic catch all fails since it uses `bind`.

**Comment by rivkahstandig3636** [comment]
@rokob do you have any thoughts?

**Comment by rokob** [comment]
If we replace logger.js with the following would it solve your problem:

```js
'use strict';

var logger = {
  /* eslint-disable no-console */
  log: function() { console.log.apply(console, arguments) },
  error: function() { console.error.apply(console, arguments) },
  /* eslint-enable no-console */
};

module.exports = logger;
```

**Comment by simlu** [comment]
@rokob Yes, that should do the trick. Thank you for getting back btw!
