### ISSUE TITLE
How to ignore third party errors injected into the page?

### ISSUE THREAD

**Issue by and-megan** [rollbar/rollbar.js#527]
How to ignore third party errors injected into the page?

* Error is coming from some 3rd party code likely injected to the page by a browser extension
* Error message is generic (TypeError) so can't ignore the class/message
* The same error gets reported multiple times within the same page view
* Can't filter by `filename` in trace.frames, because it's the URL of the page
* Most (?) occurrences seem to have trace.extra._wrappedSource, but it's mangled so probably cannot reliably filter by a blacklist of keywords or some such

Probably want to use checkIgnore based on body.trace.extra._wrappedSource. However, I'd be concerned about false positives. Could include a special string in *relevant* JS code and ignore any _wrappedSource without that string BUT that would create a need to add strings to each and every callback of event listeners we add (time-consuming). Another thought is to name the anonymous JS functions. However, the stack traces may still contain anonymous functions due to frameworks using anonymous functions.

Rollbar *might* be able to modify the `wrap()` code to grab the stack trace at the time of function wrapping and store that somewhere. This could be useful in finding the places where the wrapped functions were originally wrapped. However, if that happens in a callback then you’re sort of back to square one.

internal: https://app.intercom.io/a/apps/rlisg82q/respond/inbox/488687/conversations/13396652194

**Comment by rivkahstandig3636** [comment]
@rokob thoughts?

**Comment by rokob** [comment]
Browsers are some of the worst amalgamations of technology that we have to operate within. There is not a great generic answer for this. I'd be open to any suggestion, but custom checkIgnore functions and/or whitelists are the way to go, but they require some work. I'm of the opinion that some sort of intelligence on the backend cross project for detecting likely browser extension caused errors and surfacing those differently might be the ultimate way to go. Spam filtering for js errors.
