### ISSUE TITLE
Object.assign requirement missing

### ISSUE THREAD

**Issue by Steveb-p** [rollbar/rollbar.js#529]
Hi.

Just wanted to say that standalone (installed via `npm install rollbar`) is missing `Object.assign` dependency, which might cause some people (like me) to miss errors on IE Edge and alike (truth be told, issue in my own code stemed from that same function missing).

I'd say it might be a good idea to add a note to rollbar docs about this particular dependency?

Polyfill to use in such case: [object-assign](https://github.com/sindresorhus/object-assign)

**Comment by rokob** [comment]
This is odd, we should not be using Object.assign in any browser target.

**Comment by rokob** [comment]
There hasn't existed an Object.assign call since 1.9.4 so I'm going to close this
