### ISSUE TITLE
handle cross origin promise rejections?

### ISSUE THREAD

**Issue by and-megan** [rollbar/rollbar.js#536]
set up the configuration for unhandled promise rejections.

Inlining the Rollbar code into our HTTP response and the FunctionLocation points into the minified rollbar.js code.

"foo" is passed to the handler upon page load. When I call rejectPromise() from the console, "bar" is handled. But if I try to manually reject "baz" from the console, that never makes it to the unhandled rejection handler. I haven't experimented beyond this, but I'm wondering if the symptoms here ring a bell.

Here's a StackOverflow question that's similar:

https://stackoverflow.com/questions/40026381/unhandledrejection-not-working-in-chrome

internal: https://app.intercom.io/a/apps/rlisg82q/respond/inbox/488687/conversations/13799383736

**Comment by jessewgibbs** [comment]
I'm closing this due to old age.  If it continues to be a problem, let's reopen it.
