### ISSUE TITLE
Rollbar 2.3.4 incompatible with Angular 4.3.6

### ISSUE THREAD

**Issue by i-ghost** [rollbar/rollbar.js#539]
## Description
2.3.3 seems to be the last version working with angular 4.3.6.

Here's the relevant typescript error from webpack:

```text
ERROR in [at-loader] ./ClientApp/app/app.module.ts:158:71 
      TS2351: Cannot use 'new' with an expression whose type lacks a call or construct signature.
```

app.module.ts, `useFactory...` being line 158

```typescript
providers: [
    {
        provide: Rollbar,
        useFactory: () => typeof _rollbarConfig !== 'undefined' ? new Rollbar(_rollbarConfig) : null
    },
```

I'm just raising this here in case anybody else can't move away from angular 4.3.6 for whatever reason.

I'm not sure if it's a bug introduced as a result of bf1925b950f0346fef3eea4d3a7ae1f073d05f32 to fix #504 or if it's an intentional breaking change (no notes to indicate as such, and it's only a semver patch increment...), but I hope this issue stops somebody else spending hours tracking down the cause of their broken builds 😄.

## Workaround
Just pin rollbar to 2.3.3 in your `package.json`.

**Comment by mstip** [comment]
Same with angular 5.1.0.
I think it effects all versions.

Many Thanks to @i-ghost for saving me hours of debugging ;)

**Comment by rokob** [comment]
Fixed in https://github.com/rollbar/rollbar.js/releases/tag/v2.3.5
