### ISSUE TITLE
Broken types definitions for Typescript

### ISSUE THREAD

**Issue by LKay** [rollbar/rollbar.js#540]
There were some changes made for types definitions recently that got merged in. But these lines: https://github.com/rollbar/rollbar.js/commit/6401317850d1bba326553e9aaf5246673a8957a2#diff-b52768974e6bc0faccb7d4b75b162c99R4 break the imports. Previous export definition was correct.

**Comment by LKay** [comment]
Related to #539

**Comment by rokob** [comment]
Fixed in https://github.com/rollbar/rollbar.js/releases/tag/v2.3.5
