### ISSUE TITLE
WebWorker support

### ISSUE THREAD

**Issue by solgarius** [rollbar/rollbar.js#549]
I am having trouble using the module inside a webworker with webpack build (though I suspect it would fail via other code bundling tools). 

I am getting the error:
```
Uncaught ReferenceError: window is not defined
    at Object.<anonymous> (rollbar.umd.min.js:1)
    at e (rollbar.umd.min.js:1)
    at Object.<anonymous> (rollbar.umd.min.js:1)
    at e (rollbar.umd.min.js:1)
    at rollbar.umd.min.js:1
    at rollbar.umd.min.js:1
    at rollbar.umd.min.js:1
    at Object.<anonymous> (rollbar.umd.min.js:1)
    at __webpack_require__ (bootstrap 12d908e1a57503409ef5:19)
...
```
As webworkers don't have the `window` global and rather use the `self` global the code would need to check for existence of each to use appropriately.

I am using the rollbar.umd.js dist however all dists have this same issue. The offending code lies in cases where testing for the window variable e.g.
```
	var options = window && window._rollbarConfig;
```
On chrome this throws the above error and the existence of window should instead be checked by:
```
	var options = (typeof window !== 'undefined') && window._rollbarConfig;
```
For proper support would probably need a function that resolves the proper global to use e.g.
```
function getGlobal(){
  if(typeof window !== 'undefined'){
    return window // browser main renderer
  } else if(typeof self !== 'undefined'){
    return self // web worker
  }
  return null 
}
```
Might also want to do a check for `global` as a 3rd option for app build tools like electron, however electron processes may want to use the server version of rollbar.

Additionally for web worker support, might need to submit the error in a different way. I didn't check whether the rollbar module uses a method to submit errors to rollbar.com that is supported in web workers.

**Comment by rivkahstandig3636** [comment]
Thanks for the report! We'll take a look.
