### ISSUE TITLE
Build better support for bundling rollbar.js in 3rd party libraries

### ISSUE THREAD

**Issue by coryvirok** [rollbar/rollbar.js#57]
E.g. A new analytics company has a javascript library that their customers will include on their site. It should be easy for them to bundle rollbar.js into their library and have it work regardless if rollbar.js is on their customer's site already.

**Comment by captn3m0** [comment]
We have a similar usecase, where we develop a 3rd party JS library, that should report errors to rollbar. We can't figure out how to only get errors related to our library, and not general customer site js errors.

/cc @shashankmehta

**Comment by coryvirok** [comment]
There are still some parts of the code that make this difficult:

- `window.XXX` variables in notifier.js
- `window.onerror` - must play nicely with other error handlers

Ideally, rollbar.umd.js would not reference any `window.XXX` variables.

**Comment by rokob** [comment]
Let's unify this discussion on #141 as it is newer and has some more comments.
