### ISSUE TITLE
Turning off console output on the server.

### ISSUE THREAD

**Issue by Richie765** [rollbar/rollbar.js#574]
I don't want to see the `Successful api response.` messages every time an error is logged.

It is documented that the debug package is used and the output can be turned off with the `verbose` option. Looking at the source, I see that `server/logger` outputs directly to console without any way to turn it off (older version _did_ use debug). Could this be implemented? Thanks!

**Comment by rivkahstandig3636** [comment]
Good idea @Richie765, thanks for the suggestion.

**Comment by johnelliott** [comment]
+1 I would like to be able to pass an instance of debug or some other logger to rollbar to get some control over this. I do like the feature and leave it on in dev.

**Comment by pedrosanta** [comment]
👍 for this as well. 😕

**Comment by rokob** [comment]
Good enough I presume if `verbose: false` actually does what it sounds like (says it does) and turns off console messages?

**Comment by tnguyen14** [comment]
@rokob Is there a way to see all of my calls to rollbar to be printed via the console with `verbose: true`, without seeing the `Successful api response` message?
