### ISSUE TITLE
Best practice for using Rollbar with create-react-app?

### ISSUE THREAD

**Issue by MattSidor** [rollbar/rollbar.js#583]
What is the best practice for using Rollbar with [create-react-app](https://github.com/facebook/create-react-app)?

Specifically, I am trying to figure out how to include Rollbar only within my production build files, so I am not triggering Rollbar errrors while in development/testing environments.

create-react-app handles all of the webpack configurations automatically. The pro of this is that it makes it easier for novice developers like me to create a new React app following best practices. The con of this is that it may be harder for novice developers like me to figure out how to integrate a project like Rollbar.

I can include the "Quick start browser" `<script>` in my `public/index.html` file, but then it triggers errors in all environments.

**Comment by rokob** [comment]
Based on my quick reading of what is possible in `create-react-app`, one quick solution is to add our script tag to your `public/index.html` file and then set `enabled: (%NODE_ENV% === 'production')` in the Rollbar configuration (`_rollbarConfig`) that you would also include in that file. This uses https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#referencing-environment-variables-in-the-html to get the environment. It depends what the `NODE_ENV` variable actually becomes in production, but that is the general idea.

I would have to think about it some more for a better/different solution.

**Comment by MattSidor** [comment]
This is perfect; thanks @rokob!

I just tested it out and it works as expected, with one small modification: the `%NODE_ENV%` parameter needs to be encapsulated in quotation marks, so it gets passed in as a string.

`enabled: ("%NODE_ENV%" === 'production')`

This may not be the only way to load Rollbar in `create-react-app`, but I'm pretty sure it is the easiest.

Thanks so much, I really appreciate it.
