### ISSUE TITLE
Rollbar breaks ckeditor.js

### ISSUE THREAD

**Issue by JasonBarnabe** [rollbar/rollbar.js#584]
When enabling Rollbar JS through the Rollbar gem v2.15.5, ckeditor.js on our page breaks with:

```
TypeError: e.on is not a function
Stack trace:
listenTo@https://cdn.ckeditor.com/ckeditor5/1.0.0-alpha.2/classic/ckeditor.js:5:79447
listenTo@https://cdn.ckeditor.com/ckeditor5/1.0.0-alpha.2/classic/ckeditor.js:5:222410
add@https://cdn.ckeditor.com/ckeditor5/1.0.0-alpha.2/classic/ckeditor.js:5:256269
init@https://cdn.ckeditor.com/ckeditor5/1.0.0-alpha.2/classic/ckeditor.js:5:319846
```

**Comment by rivkahstandig3636** [comment]
Thanks for reporting this @JasonBarnabe, we'll investigate.

**Comment by rokob** [comment]
To me this is a bug in ckeditor because searching through the issues of there this comes up periodically as conflicts with other libraries. I have a fix though based on what angular did when they got blamed for this as well, so I will make that change.

**Comment by jessewgibbs** [comment]
I'm closing this due to old age.  If it's still a problem, please let us know.
