### ISSUE TITLE
Properly document captureUncaught* options

### ISSUE THREAD

**Issue by raffomania** [rollbar/rollbar.js#586]
I didn't find any comprehensive explanation of the config options `captureUncaught` and `captureUnhandledRejections` at [the configuration reference](https://rollbar.com/docs/notifier/rollbar.js/#configuration-reference) which should describe *every* option there is, right? 
All I found were usages in examples. I'd especially like to know the default values for these two options.

**Comment by rivkahstandig3636** [comment]
Great catch! We'll update.

**Comment by bladesling** [comment]
exitOnUncaughtException should also be documented too. Thanks!

**Comment by bbugh** [comment]
In the mean time, can you explain here? I've been looking around for an answer to this and finally came to Github to report the issue. Thanks!

**Comment by rivkahstandig3636** [comment]
@bbugh Sorry about that, it's actually been updated [here](https://docs.rollbar.com/docs/rollbarjs-configuration-reference) but I forgot to update this issue!
