### ISSUE TITLE
Wrapped console.log() raises error when logging Symbol

### ISSUE THREAD

**Issue by ronen** [rollbar/rollbar.js#592]
Hello,

When I installed the Rollbar browser snippet in an otherwise working app, I got the following exception:

```
rollbar.min.js:formatted:971 Uncaught TypeError: Cannot convert a Symbol value to a string
    at Array.join (:3000/native)
    at Object.L [as formatArgsAsString] (rollbar.min.js:formatted:971)
    at console.n.(:3000/anonymous function) [as log] (https://cdnjs.cloudflare.com/ajax/libs/rollbar.js/2.3.1/rollbar.min.js:2:19002)
   [...]
```

After a bit of digging, turns out this happened when my code called `console.log(x)` where `x` is a `Symbol`.   The simple workaround is to use `console.log(x.toString())` if I know that the thing being logged is a symbol.  But it'd be nice to not have to.

[The problem of course  is that unlike most Javascript objects, `Symbol` won't implicitly convert to a string]

Thanks

**Comment by rivkahstandig3636** [comment]
Thanks for the report! We'll fix this.
