### ISSUE TITLE
unhandled rejections in node doesn't work - crashes node server in ember fastboot

### ISSUE THREAD

**Issue by nolman** [rollbar/rollbar.js#596]
```
TypeError: e.addEventListener is not a function
at Object.captureUnhandledRejections (/app/dist/assets/vendor-130f10ba884355e62ee189a7ad2f946b.js:4589:37)
```

I don't think window has an addEventListener method in node?

**Comment by rivkahstandig3636** [comment]
We will take a look into this, sorry for the delay!

**Comment by rokob** [comment]
There isn't a window in node, no code that calls addEventListener should execute in a node context, it is only loaded in the browser specific parts of this library.

**Comment by jhonathas** [comment]
I have the same problem.

TypeError: e.addEventListener is not a function
    at Object.captureUnhandledRejections (/app/dist/assets/vendor-d5bd099cc177f2d3646bcafade756f38.js:9731:37)

**Comment by rokob** [comment]
How are you running your code so that you are using browser code in node? There is a specific entry point for server side code and a different one for the browser because of things like this.

**Comment by jessewgibbs** [comment]
Closing this issue since there's been no response from the last commenter.

**Comment by williamweckl** [comment]
Still happens...

Ember fastboot emulates ember code to run at nodejs to render the initial html from the server.

The problem happens because the client code tries to handle uncaught errors happened on the server.

Maybe it can be solved validating if window exists before calling addEventListener.

**Comment by waltjones** [comment]
@williamweckl There are multiple places the browser target for Rollbar.js will expect a valid window environment. For any server side rendering scenario, it's probably best to use the Rollbar.js snippet in the HTML.

If I'm misunderstanding, let me know.
