### ISSUE TITLE
Regression with AWS Lambda + Node 8.10

### ISSUE THREAD

**Issue by simlu** [rollbar/rollbar.js#597]
I've just fixed this for our wrapper [here](https://github.com/simlu/lambda-rollbar/pull/104), but you might want to consider no longer returning the result from the handler in node8.10 as it can hide the result when async operation happen. In particular this line should probably no longer return:

https://github.com/rollbar/rollbar.js/blob/ebe145cba949c9214fd660263e974da59010524d/src/server/rollbar.js#L269

Alternative would be to display a warning when something is returned from the lambda function (99.9% of the cases callback is used).

Let me know if you have questions. Best of luck ;)

**Comment by rivkahstandig3636** [comment]
We will take a look into this, sorry for the delay!

**Comment by rokob** [comment]
Hmm yeah I'm guessing this is what we want to do going forward for sure, but let me check this doesn't break anything for pre-8.10 or if that is even a concern.

**Comment by jamesdixon** [comment]
Hi, just to wanted to clarify something. The release notes say:

> As of this release, the lambdaHandler no longer supports the non-callback version of lambda functions which have been deprecated by AWS for a while (https://docs.aws.amazon.com/lambda/latest/dg/programming-model.html)

Does this mean that the `callback` version is the only return method supported? It's mentioned that the non-callback version is deprecated by AWS, but I'm not seeing this anywhere. If anything, I'm seeing more examples of using `async` functions with a straight up `return` with the ability to use Node 8.10.

**Comment by Ricardonacif** [comment]
Hey guys, I didn't understand. Does rollbar right now support async functions with AWS Lambda or not? How would I add rollbar to catch the exceptions in a case like this:

```
let AWS = require('aws-sdk');
let lambda = new AWS.Lambda();
exports.handler = async (event) => {
    return await lambda.getAccountSettings().promise() ;
};

```

**Comment by simlu** [comment]
@Ricardonacif I'd take a look at [lambda-rollbar](https://github.com/simlu/lambda-rollbar). We use it extensively in production. I'm assuming there is a way to get things to work only using rollbar, but I'm also not sure how. Maybe someone else can jump in.

**Comment by Ricardonacif** [comment]
@simlu that's great! I'm gonna give it a try!
