### ISSUE TITLE
How to set error specific context

### ISSUE THREAD

**Issue by colindresj** [rollbar/rollbar.js#598]
I'd like to send over error specific meta data, but it isn't clear to me how to do it. All data seems to be continually merged together.

Here's a contrived example:

```js
var rb = rollbar.init({ /* my config */ });

rb.error(new Error('Error A'), {meta: {keyA: 'A'}});
rb.error(new Error('Error B'), {meta: {keyB: 'B'}});
```

In the rollbar UI I see both errors. Error A has `meta.keyA = 'A'`, but error B has `meta.keyA = 'A'` and `meta.keyB = 'B'`. In the latter case I only want `meta.keyB`.

I've also tried initializing seperate rollbar instances, but not look. Is configuration global?

**Comment by rokob** [comment]
I used that exact code in both the browser and nodejs and I get two separate occurrences, one with meta.keyA == 'A' and one with meta.keyB == 'B'. The second one with keyB does not have a keyA. There must be something else going on. Are you perhaps doing something more like:

```js
var rb = rollbar.init({ /* my config */ });
var meta = {keyA: 'A'};
rb.error(new Error('Error A'), {meta: meta});

meta.keyB = 'B';
rb.error(new Error('Error B'), {meta: meta});
```
