### ISSUE TITLE
How to upload source maps for CDN scripts?

### ISSUE THREAD

**Issue by kolyabres** [rollbar/rollbar.js#602]
I'm using on my site script from CDN:
`<script src="https://enterprise.opentok.com/v2/js/opentok.min.js" crossorigin="anonymous"></script>`
In rollbar it is displayed as:
`//dynamichost/opentok.min.js`
So, I tried upload source map file via API:
```
curl https://api.rollbar.com/api/1/sourcemap \
  -F access_token=some_token_here \
  -F version=hf28t298g0298gh209gh2093gh2093gh209gh20 \
  -F minified_url=https://dynamichost/opentok.min.js     \
  -F source_map="@https://enterprise.opentok.com/v2/js/opentok.min.js.map"
```
But, I got error:
> curl: (26) couldn't open file "https://enterprise.opentok.com/v2/js/opentok.min.js.map"

It seems to curl works only with local files.

Does anyone know how to solve this issue or another way to upload source map file?

**Comment by rivkahstandig3636** [comment]
Hi there, You can upload your source map through our UI.

**Comment by brianr** [comment]
@kolyabres That's a curl issue: curl can only upload local files. If you don't have it locally and you want to use the upload method, you could download it first.
