### ISSUE TITLE
rollbar.errorHandler() not in typescript definitions

### ISSUE THREAD

**Issue by pburrows** [rollbar/rollbar.js#603]
typescript definitions were added in https://github.com/rollbar/rollbar.js/pull/334 as a result of  https://github.com/rollbar/rollbar.js/issues/302

The definition is missing rollbar.errorHandler() as documented here:
https://docs.rollbar.com/docs/javascript#section-server-configuration

(this is for a nodejs project using ts-node)

temporary workaround:

```
app.use(this.rollbar['errorHandler']());
```

**Comment by rivkahstandig3636** [comment]
Thanks for letting us know!

**Comment by rokob** [comment]
The problem I am having is getting the express type declarations without taking a dependency on express. I think it is possible to work around this but I don't know the typescript ecosystem well enough to do it off the top of my head. I will try to get something workable out.

**Comment by corps** [comment]
@rokob You don't have to consume express's own type.  If you simply declare a local interface that is compatible with express but describe's rollbar's own expected interface, the "compatibility" of the interfaces will be checked softly by typescript.
