### ISSUE TITLE
Telemetry response not showing the http code

### ISSUE THREAD

**Issue by NathanShi** [rollbar/rollbar.js#607]
I can not find any related docs and have to file this issue.

One of our telemetry response shows nothing even the http code. Wondering what does this indicates for the response. Thanks.

![screen shot 2018-05-01 at 2 56 29 pm](https://user-images.githubusercontent.com/22336965/39490864-e0bfa286-4d4f-11e8-85a7-738ea6e98098.png)

**Comment by jessewgibbs** [comment]
Hi Nathan,

Could you contact us via support@rollbar.com and share the URL for that specific exception so we can further investigate?  Not sure if this is an issue in the web app or the SDK until we get more info...

**Comment by rivkahstandig3636** [comment]
@jessewgibbs Is this still an SDK issue?

**Comment by jessewgibbs** [comment]
@rivkahstandig3636 let's go ahead and close this out.
