### ISSUE TITLE
Addressing the package size

### ISSUE THREAD

**Issue by luke-j** [rollbar/rollbar.js#615]
By my measurement, this package currently weighs in at around 17KB gzipped. That is quite a decent sized package by any account:
<img width="248" alt="screen shot 2018-05-18 at 10 49 50 am" src="https://user-images.githubusercontent.com/6657011/40210654-7f67dc8c-5a89-11e8-831f-918fc54c188e.png">

Are there any plans to look at slimming the size of this bundle down?

**Comment by rokob** [comment]
I can give things a once over to see about getting the size down a little bit, but it will be in the 12-17 KB range given the feature set and browser support. Pull requests would be welcome if there is some cross cutting concern that would get the size down that I am missing.

**Comment by luke-j** [comment]
>it will be in the 12-17 KB range given the feature set and browser support.

Perhaps consider a slim build or ES modules build for Webpack tree shaking? Also, it might be worth a separate build for more modern browsers that a consumer of this package could elect to import in place of the full package. For example, I'm only dealing with a couple of the functions with the `last 2 versions` of browser support.

**Comment by dangodev** [comment]
The pre/post-gzipped weight is the real measurement, and it’s `64 KB`. That’s almost as much as React! Running a thin React application, Rollbar nearly doubles my bundle size. There’s only so many JS packages that can be “critical” before some get loaded async, or not at all, and with Rollbar kinda being “critical” it’s a shame that it impacts the user experience negatively so much.

**Comment by newtack** [comment]
https://bundlephobia.com/result?p=rollbar@2.5.4

18.8 KB

If libraries such as material-ui can decrease their footprint by 15% (see here https://bundlephobia.com/result?p=@material-ui/core@4.0.0-alpha.4) while adding features, then I am sure that the great Rollbar engineers can do so too ...  :-)

**Comment by lightheaded** [comment]
I agree and this is not really tolerable for high-performance applications and we're currently looking to switch the provider in case this issue is a dead end. Is there any plans to address this issue in the future? Perhaps create a lite version for critical features?

**Comment by HMilbradt** [comment]
Is this still being looked into?  This is the largest package in one of our projects, and its size is contributing to a negative impact on pagespeed scores.

**Comment by waltjones** [comment]
I've assigned to myself. I don't have an ETA or a good idea about how much is possible in the short term but I'll look at it. Feel free to send any ideas or feedback.

**Comment by waltjones** [comment]
A conversation/question that came up offline: Would using the Rollbar snippet solve or mitigate the issue for anyone? The trade-offs are that you'd be adding Rollbar in a script tag instead of in your webpack build. But it's designed to have the smallest possible code size at page load while still capturing events during that time. The full CDN bundle loads after page load. This amounts to better page load performance than any trimmed down package, while keeping the full feature set.

I realize this isn't an option for some projects, but maybe is for others.

**Comment by HMilbradt** [comment]
Thanks for the response, I will try that out and let you know if it will work for us 🙏

**Comment by HMilbradt** [comment]
While adding the snippet worked, Ad blockers will block the rollbar script from loading (tested with Adblock plus).  So there's a trade-off to using it:  Either self host or proxy the rollbar script under a different name, or write code that checks if `window.rollbar` exists.  

We can work with this for now, but we would really like to have something smaller that could be bundled in our application.

Thanks for the great work by the way 👌

**Comment by waltjones** [comment]
@HMilbradt Thank you for the follow up report. 

We're definitely looking at size reduction for the webpack package.

**Comment by levenleven** [comment]
Meanwhile it keeps growing https://bundlephobia.com/result?p=rollbar

**Comment by lightheaded** [comment]
Meanwhile we've decided to drop Rollbar's JS SDK

**Comment by waltjones** [comment]
For those following this issue, any comments or feedback on this approach:
https://github.com/rollbar/rollbar.js/pull/817

This assumes you're using webpack or another builder that allows `require('rollbar/src/browser/core')` instead of `require('rollbar')`.

Could you use this, or not?

**Comment by dangodev** [comment]
@waltjones I think that’s a great approach! And one I’ve seen other libraries do (like [Vue](https://unpkg.com/browse/vue/dist/) that provides multiple distributions for different usecases).

I agree with your proposal to keep using the `"main"` entry (`rollbar`) to be the easiest experience that handles things for the developer at the cost of weight. And for the people that are capable/interested, provide an alternate distro with less weight but requires the dev to fill in the gaps (`rollbar/src/browser/core`). I think that’s fair, and shouldn’t impose any additional strain on Rollbar’s team.

**Comment by jackwkinsey** [comment]
> For those following this issue, any comments or feedback on this approach:
> #817
> 
> This assumes you're using webpack or another builder that allows `require('rollbar/src/browser/core')` instead of `require('rollbar')`.
> 
> Could you use this, or not?

I think our team could definitely benefit from this approach!

**Comment by agriffis** [comment]
> Could you use this, or not?

We're loading Rollbar by the snippet at the page level, then using the noconflict release in our build:

```
import rollbar from 'rollbar/dist/rollbar.noconflict.umd'
```

per the instructions at https://docs.rollbar.com/docs/using-rollbarjs-inside-an-embedded-component

We're doing it this way because it's a large CMS and we'd like to catch page-level errors in one project, and app-level errors in a separate project. (In fact this isn't quite working right yet, but it's the idea.)

My question: If we have the snippet at the page level, and we import rollbar/core in the app, does the page-level snippet lend its telemetry powers to the app-level instance?

**Comment by btmorex** [comment]
> Could you use this, or not?

Yes, it would be a big improvement.

**Comment by waltjones** [comment]
@agriffis

> My question: If we have the snippet at the page level, and we import rollbar/core in the app, does the page-level snippet lend its telemetry powers to the app-level instance?

They will be different instances of Rollbar objects, and will not be able to share the same telemetry functionality.
