### ISSUE TITLE
Payload sending without environment

### ISSUE THREAD

**Issue by kradical** [rollbar/rollbar.js#622]
Hello!

First of all Rollbar is a great product that has seriously improved our product. So good work :).

We recently updated to rollbar `2.4.0` and I think something may have happened with how options are merged. We started seeing errors reported with an "unknown" `environment`. Our usage is in a React SPA with the standard setup.

Our production config looks like:
```javascript
var _rollbarConfig = {
  accessToken: "SECRET_TOKEN",
  captureUncaught: true,
  captureUnhandledRejections: true,
  payload: {
    environment: "production",
    client: {
      javascript: {
        source_map_enabled: true,
        code_version: "production",
      },
    },
  },
};
```

If I load the page as a guest user and send a test error `window.onerror('Test error')` it goes through with the `environment` properly set and gets picked up by our dashboard, everything is good.

If I log in this code runs:
```javascript
function setUser(user) {
  if (typeof window === 'undefined' || !window.Rollbar) return;

  const person = user
    ? { id: user.id, email: user.email }
    : undefined;

  const payload = {
    person,
  };

  window.Rollbar.configure({ payload });
}
```

And then when I send a test error the `environment` will now be "unknown". I checked what was being sent over the network and the `environment` is now missing from the `POST`.

`window.Rollbar.options` still has the original configuration options and `window.Rollbar.impl.options` has the new configured payload (without `environment`).

I believe there may be some sort of bug around merging the options? I also believe this was introduced in our upgrade from `2.3.1` to `2.4.0`.

Our current workaround is to do this on login:
```javascript
function setUser(user) {
  if (typeof window === 'undefined' || !window.Rollbar) return;

  const person = user
    ? { id: user.id, email: user.email }
    : undefined;

  const startupPayload = window.Rollbar.options.payload;

  const payload = {
    ...startupPayload,
    person,
  };

  window.Rollbar.configure({ payload });
}
```

Which seems to work.. but I believe the initial startup options should be preserved anyways, correct?

Either way, let me know if this is a usage error or if there is anything I can do to assist!

**Comment by rokob** [comment]
Yes, sorry about that, this is a bug that I fixed recently. However, I hadn't put out a new release. v2.4.1 has the fix which I just released.

**Comment by kradical** [comment]
Awesome! thanks for the quick response :)
