### ISSUE TITLE
Security | scrubTelemetryInputs default off 

### ISSUE THREAD

**Issue by kimek** [rollbar/rollbar.js#625]
Hi guys,
We just notice that you not only introduce Telemetry with default settings on on our sites, also you turn off as default scrubTelemetryInputs.
We are sad :(

**Comment by rivkahstandig3636** [comment]
Hi there, You can always turn these off. I'm sorry it made you sad :(

**Comment by brianr** [comment]
Hey @kimek , we're revisiting the defaults here. Will reopen this issue to track it.

**Comment by kimek** [comment]
References to other issue are not related at all to this task @rokob 
Secondly maybe you could update your docs about that ?
scrubTelemetryInputs but where ? 
just put { scrubTelemetryInputs : true } and it will work like 
{
  level: "debug" | "info" | "warning" | "error" | "critical"
  type: string
  timestamp_ms: number
  body: object
  source: string
  uuid?: string
}
???
or it should go to :
_rollbarConfig = {
  autoInstrument: {
     { scrubTelemetryInputs : true } 
 }
}

or maybe somewhere else ??
Could you update your code example to be more consistent and add  { scrubTelemetryInputs : true } example too ? 

All of our devs have access to credit card. But who cares ?

**Comment by kimek** [comment]
Somebody update docs. Thank you. Still I think that you should inform all clients that this is turn on and all sensitive data is saved to rollbar.

**Comment by brianr** [comment]
@kimek The current default behavior (as a result of #627) is that rollbar.js will:

1. scrub values throughout the payload when the name matches one of the configured `scrubFields`
2. scrub telemetry values when the input name matches one of the configured `scrubFields`

If the sensitive fields you want to scrub are named in `scrubFields`, then they will not be collected.

If you do not want to collect *any* field values via telemetry, you can turn them off by setting `scrubTelemetryInputs: true`. But as long as the field names you want to scrub are listed in `scrubFields`, setting `scrubTelemetryInputs: true` shouldn't be necessary.

Hope this clears it up.
