### ISSUE TITLE
Doesn't log errors when the item data is too large (HTTP 413)

### ISSUE THREAD

**Issue by jaredp** [rollbar/rollbar.js#629]
**Behavior:** Unhandled exceptions in my prod not reaching Rollbar when the error data is more than 128KB

**Expectation:** 
- Minimum: Rollbar item reporting that an error couldn't be reported because the data was too large.
- Good: trimming error reports more than 128KB down under the limit, with a note that they were trimmed.
- Best: trimming individual long log items in the telemetry so the whole request is under the 128KB limit.

**Severity:** This is affecting real users on my site, because we rely on Rollbar to tell us if we have crashes.  

-----

Investigating, I found POSTs to https://api.rollbar.com/api/1/item/ returning a 413 error.  The docs say

Code | Type | Description
--- | --- | ---
413 | Request entity too large | The request exceeded the maximum size of 128KB.

(https://docs.rollbar.com/reference) 

This is consistent with the particular crash I was getting, which was from a different service (unrelated to Rollbar) rejecting a request for being too large.  I believe only a few bytes of the too-large data was put in the error's `.message`, but it was in our `console.log`s in full.   (We `console.log` data we send to that particular service for other reasons.) 

-----

In the console, I have an error

>  Failed to load https://api.rollbar.com/api/1/item/: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://example.com' is therefore not allowed access. The response had HTTP status code 413.

but I think the missing CORS header is just because the 413 response had an empty body/headers, where it otherwise always has `CORS: *`

**Comment by jaredp** [comment]
Further digging shows that in my particular case, I have a single `{type: 'log'}` entry in the error's `data.body.telemetry` with a multi-megabyte message that's making the whole `data.body` go over the size limit.

**Comment by jaredp** [comment]
Also I'm on version 2.2.7 of the library

**Comment by jessewgibbs** [comment]
Related conversations in Intercom:  https://app.intercom.io/a/apps/rlisg82q/inbox/inbox/487663/conversations/17059986597

**Comment by rokob** [comment]
Yeah I have a branch lying around where I was doing some truncation work but it wasn't prioritized. I have #630 which will take care of telemetry log messages being too long which is a good idea regardless. I will follow up with a more general truncation plan similar to what we do in the other SDKs.

**Comment by jaredp** [comment]
Thanks for responding quickly!  Some thoughts on #630:
- 128 chars seems really, really small.  If we're going to set a limit, I'd like at least 1024 or something.  Those logs are really useful!
- I'd like an indication if a log is truncated, something as simple as suffixing "... [snip]"
- Is there a reason we can't clone the data before we send it, and mutate the clone, rather than doing the truncation up front?    If we did it just prior to send, we could first see if the un-truncated whole item is over 128KB, and possibly not have to truncate at all.

More broadly:
- I'm concerned this doesn't fix #629 because even if there's no single log message that's too long, we're not checking that the overall item payload is under the 128KB limit.  What if the `Error.message` is a megabyte, for example?
- I'm concerned that it's possible in general to have the client know that an item submission failed, but not retry with a "submitting an item failed" as a last resort.  I'd be a lot more comfortable knowing that I'm not missing any errors, even if the reports themselves are empty.

**Comment by rokob** [comment]
* 128 is small, I can go 1024 by default and make it configurable
* I suffix `...` if we truncate
* Truncation more generally to get below the payload limit is the overall right approach here as you mention. I was just planning on getting around to it later, but I might as well just do it now because yeah this is only a partial fix.
* The alternative you mention is interesting. We could just send everything, then if we get a 413 send a minimal message saying something happened but the payload was too big. Truncating ahead of time rather than doing the roundtrip is better though and not too much effort so I'll just do that.

**Comment by jaredp** [comment]
Great, that all sounds awesome.  The only thing missing is I really need the retry on 413 (or really any non 2xx) as a failsafe.  Ideally it should never fire, but it would make me really happy to have more guarantees that I'm notified of all errors even if Rollbar itself has issues, especially because #630 is intentionally a partial fix.

I'm always very concerned about missing errors and we rely on Rollbar to make sure that doesn't happen.  A (degraded) retry on errors would give me much more faith in Rollbar, because it would mean you're more resilient to your own bugs.  Resilience techniques should protect against any unknown unknowns, not just this bug in particular.

**Comment by jaredp** [comment]
Now that #630 is merged in, how do I get it into my app in prod?  I didn't see a new version of this package published on npm
