### ISSUE TITLE
Support browserify from npm module

### ISSUE THREAD

**Issue by appden** [rollbar/rollbar.js#64]
Please add support for browserify by providing the `dist/rollbar.commonjs.js` file in the published module with the `browser` field in the `package.json` pointing to it (please see https://github.com/substack/browserify-handbook#browser-field). Thanks!

**Comment by mbrevda** [comment]
+1

**Comment by mbrevda** [comment]
dup of #51

**Comment by coryvirok** [comment]
https://www.npmjs.com/package/rollbar-browser
