### ISSUE TITLE
Update this repo's URL

### ISSUE THREAD

**Issue by dandv** [rollbar/rollbar.js#640]
It currently points to https://rollbar.com/docs/notifier/rollbar.js/, which redirects.
![image](https://user-images.githubusercontent.com/33569/42673766-bab32efe-8621-11e8-9b9d-807669e60548.png)

**Comment by jessewgibbs** [comment]
@rivkahstandig3636 @rokob we just need to update this to point to https://docs.rollbar.com/docs/javascript.  I don't seem to have sufficient permissions on the repo to do this.

**Comment by rokob** [comment]
I can’t edit that either, not sure who does have the permission.

**Comment by brianr** [comment]
done. thanks @dandv !
