### ISSUE TITLE
Rollbar.log() doesn't do anything on the server?

### ISSUE THREAD

**Issue by dandv** [rollbar/rollbar.js#641]
https://docs.rollbar.com/docs/custom-log-messages#section-javascript suggests there's a static `log` method in the Rollbar object that can be called with the log level as a parameter:

> // log methods exist for each level, or pass as a param
Rollbar.critical("Crash while processing payment");
Rollbar.log("error", "Crash while checking order status");

That doesn't seem to work in Node:

```js
import Rollbar from 'rollbar';
const rollbar = new Rollbar('...');

Rollbar.log('info', 'static method log() called with info as first param');  // noop
rollbar.info('instance method info()'); // only this call sends a log
```

**Comment by rokob** [comment]
Yeah those docs are just a bit outdated, sorry. Two things though. There actually is a static method, but it will log an error, if configured to actually output logging info, if you call one of the static methods before calling `Rollbar.init`. This is a backwards compatibility issue with the old nodejs library. Second, the method does not interpret the first string argument to `log` as the level. That is just wrong. The docs here: https://docs.rollbar.com/docs/nodejs are current, I'll fix the other ones sorry for the confusion.

**Comment by dandv** [comment]
Thanks! Another outdated bit might be "// It will appear as `custom.postId` in the Occurrences tab" at https://docs.rollbar.com/docs/javascript/#section-usage. I think the user will see just "postId".

**Comment by jessewgibbs** [comment]
@danddv thanks for catching the mistake in https://docs.rollbar.com/docs/javascript/#section-usage.  That extra property appears as `message.extra.postId` now so I've fixed the docs to reflect that.

**Comment by jessewgibbs** [comment]
Fixed the issue in https://docs.rollbar.com/docs/custom-log-messages#section-javascript by removing reference to `rollbar.info()`
