### ISSUE TITLE
Error handling fallback when Rollbar isn't loaded properly

### ISSUE THREAD

**Issue by uri** [rollbar/rollbar.js#644]
On the application I work on, when an unhandled error occurs it gets sent to Rollbar and a modal is displayed  indicating that an error occurred and forces the user to refresh the page.

I am seeing that for some unknown reasons *rollbar.min.js* is not being loaded in some situations. This causes the `onSendCallback` to never trigger.

It would be ideal if we can also override `window.onerror` with our own logic that gets triggered if Rollbar is not loaded correctly.

Something like the following.

```javascript
var rollbarOnerror = window.onerror
window.onerror = function() {
  rollbarOnerror(/* arguments? */);
  if (!window.handledByRollbar) {
    // Perform some kind of backup, i.e. as user to send an email and force to refresh
  }
}
```

```javascript
// rollbar configuration

{
  // ...
  onSendCallback: function(uncaught) {
    window.handledByRollbar = true
    // ...
  }
  // ...
}
```

This can be artificially reproduced by blocking the *rollbar.min.js* request (in devtools for example). In my specific example I'm blocking https://cdnjs.cloudflare.com/ajax/libs/rollbar.js/2.3.9/rollbar.min.js (to try an create a fix for this situation actually occurring).

**Comment by rokob** [comment]
Are you using the snippet to load Rollbar? I am not sure why "I am seeing that for some unknown reasons rollbar.min.js is not being loaded in some situations" that would happen so I'm curious if this is the snippet not loading it properly or if there is something else going on.

If you set your own `window.onerror` function before loading Rollbar, we will call your function after handling the error, in that case if Rollbar does not load then your function would get called directly.

**Comment by uri** [comment]
@rokob 

>If you set your own window.onerror function before loading Rollbar, we will call your function after handling the error

I'm not finding this to be the case?

**Comment by uri** [comment]
Actually I see 

```javascript
  if (old) {
    old.apply(window, args);
  }
```

Will investigate further..

**Comment by rokob** [comment]
I am seeing it not working how I would expect so I am trying to figure out why as well

**Comment by rokob** [comment]
Ah I figured out why it isn't calling the original function, working out a fix now.
