### ISSUE TITLE
Angular 5: Performance cost with Rollbar HTTP calls

### ISSUE THREAD

**Issue by devakone** [rollbar/rollbar.js#646]
Hello!
I used the Angular integration to setup Rollbar for my application, and i use the `this.rollbar.info` call to log some state related calls in my application, nothing too crazy. I noticed that it affects the performance of my application at it seems the `POST` HTTP calls that Rollbar does to send the data back to the API are slowing down the general performance of my application, especially on route changes.

 Investigating it I think it comes down to the change detecting being triggered by every HTTP call that Rollbar makes that have to be processed by Angular. I tried getting around it by wrapping my Rollbar calls in the ngZone's `runOutsideAngular` function but it seems Angular still takes in account the potential change introduced by the rollbar HTTP calls. I was wondering if anybody has run into this issue and found a way around it.

 My goal would be to have the Rollbar calls run without being taken in account by Angular.

Thanks

**Comment by rokob** [comment]
I haven't heard of this being an issue. Angular makes route changes wait on POST requests?

**Comment by waltjones** [comment]
Angular 2+ invokes change detection on all XHR requests. Just watching the behavior in the browser console, a single XHR request can generate as many as 4 - 6 change detection cycles. So, route changes don't wait on POST requests, but XHR activity can cause significant change detection activity. Apps that are more sensitive to this will of course be more affected.

This isn't Rollbar specific. It's a general behavior with Angular and XHR. There's a way around it, as @devakone attempted, by using `runOutsideAngular`. However, this must be applied to the async XHR response, not the request. This will make it difficult to control from the request side if requests aren't synchronous, especially if there's any queuing of requests.

**Comment by waltjones** [comment]
The referenced PR fixes the issue by changing the zone context in rollbar.js after any queuing and at the time of the http post. I thought async xhr reponses might be an issue, but they inherit the current zone with no issue.
