### ISSUE TITLE
{"extraArgs":[{}]} messages in Firefox

### ISSUE THREAD

**Issue by dottodot** [rollbar/rollbar.js#654]
Seem to be getting quite a few log entries with a message of `{"extraArgs":[{}]}`

It's not really clear what the cause of this would be. Can you advise?

**Comment by jessewgibbs** [comment]
https://app.intercom.io/a/apps/rlisg82q/conversations/17864028162?redirectTo=feed

**Comment by dottodot** [comment]
Not sure if it's related but I also get a few errors that don't have any info such as 

```
Unknown error. There was no error message to display.
1
File "(unknown)" line (unknown) in [anonymous]
```

**Comment by jessewgibbs** [comment]
Hi @dottodot - I don't think the last issue is related.  It's probably due to your CORS configuration.  You can read more about this at https://docs.rollbar.com/docs/unknown-script-error.

**Comment by dottodot** [comment]
Don't think in can be a CORS issue as that's setup correctly and if it wasn't all requests to that rest endpoint would fail.

**Comment by dottodot** [comment]
One thing I've noticed is the `{"extraArgs":[{}]}` issue only seems to be on firefox

**Comment by jessewgibbs** [comment]
Hey @dottodot - We encountered a similar issue in https://github.com/rollbar/rollbar.js/issues/560.  Are you guys using zone.js by any chance?  Here's the issue in that library that was causing problems for Rollbar: https://github.com/angular/zone.js/issues/1108.

**Comment by dottodot** [comment]
@jessewgibbs I am yes, thanks for the heads up.

**Comment by jessewgibbs** [comment]
Thanks for the follow-up.  I'm going to go ahead and close this issue since we're already tracking it in https://github.com/rollbar/rollbar.js/issues/560.
