### ISSUE TITLE
The change log does not specify what version 1.1.15 changes/fixes

### ISSUE THREAD

**Issue by nodesocket** [rollbar/rollbar.js#66]
The `CHANGELOG.md` does not specify what version `1.1.15` changes/fixes.

**Comment by coryvirok** [comment]
Sorry about that. Updated with this commit: https://github.com/rollbar/rollbar.js/commit/d10119f2695f42a27f804f540fc032a9297998d1#diff-4ac32a78649ca5bdd8e0ba38b7006a1e
