### ISSUE TITLE
Node v8.11.3 does not Catch Uncaught Errors

### ISSUE THREAD

**Issue by ajtran** [rollbar/rollbar.js#662]
internal: https://app.intercom.io/a/apps/rlisg82q/inbox/inbox/849049/conversations/18134613089

I just tested with this configuration in node v.8.11.3
```
const express = require('express');
const app = express();
var Rollbar = require('rollbar');

var rollbar = new Rollbar({
  "accessToken": "",
  "captureUncaught": true,
});

app.use(rollbar.errorHandler());

app.get('/', function (req, res) {
  res.send('Hello World!');
  throw new Error(`test error`) // this is not caught
  rollbar.log("on hello world page");  // and this is not reported, most likely due to the error in the line above
});

app.listen(3000, function () {
  console.log('app listening on port 3000!')
  rollbar.log("starting app")
});
```
and the thrown is not being caught. However, this works fine in v9.11.1

**Comment by jessewgibbs** [comment]
The customer was able to work around this by defining the error handler after `app.get` and before `app.listen`.  I'm going to close this issue for now, as we're not likely to spend more time on it soon.
