### ISSUE TITLE
v2.4.5 errors on IE 11

### ISSUE THREAD

**Issue by ajtran** [rollbar/rollbar.js#663]
internal: https://app.intercom.io/a/apps/rlisg82q/inbox/inbox/488687/conversations/18260020429

User reported that `OPTIONS` request fails on IE 11. This is preventing the data from being sent to Rollbar.

**Comment by rivkahstandig3636** [comment]
@shakiba Please take a look into this ASAP

**Comment by jessewgibbs** [comment]
I'm going to close this issue until we get confirmation from the customer that they have their CORS settings properly configured.
