### ISSUE TITLE
Can't set source map file location in the config transform function in the ionic app

### ISSUE THREAD

**Issue by ryaa** [rollbar/rollbar.js#664]
I'm trying to set the source map file location in the ionic application using transform function in the rollbar config object using the below sample.

https://docs.rollbar.com/docs/source-maps/#section-using-source-maps-on-many-domains

```
                transform: (payload: any) => {
                    if (payload && payload.body && payload.body.trace && payload.body.trace.frames) {
                        const frames = payload.body.trace.frames;
                        for (let i = 0; i < frames.length; i++) {
                            if (frames[i].filename.indexOf('main.js') > -1) {
                                payload.body.trace.frames[i].filename = 'file://main.js';
                            }
                        }
                    }
                },
```

However  the problem is that payload.body does not have trace property.

The rollbar version is 2.4.5.
ionic info output
`
cli packages: (/Users/alexryltsov/.nvm/versions/node/v6.9.2/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.11
    Cordova Platforms  : android 7.1.1 ios 4.5.5
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2
    ios-sim           : 6.1.2
    Node              : v6.9.2
    npm               : 3.10.9
    OS                : macOS High Sierra
    Xcode             : Xcode 9.4.1 Build version 9F2000

Environment Variables:

    ANDROID_HOME : /Users/alexryltsov/Library/Android/sdk/

Misc:

    backend : pro
`

rollbar configuration object is as below
```
            const rollbarConfig: Rollbar.Configuration = {
                accessToken: this.appSettings.ROLLER_TOKEN,
                verbose: true,
                captureUncaught: true,
                captureUnhandledRejections: true,
                autoInstrument: false,
                transform: (payload: any) => {
                    if (payload && payload.body && payload.body.trace && payload.body.trace.frames) {
                        const frames = payload.body.trace.frames;
                        for (let i = 0; i < frames.length; i++) {
                            if (frames[i].filename.indexOf('main.js') > -1) {
                                payload.body.trace.frames[i].filename = 'file://main.js';
                            }
                        }
                    }
                },
                payload: {
                    async: false,
                    environment: this.appSettings.ENV,
                    version: this.appSettings.VERSION,
                    client: {
                        javascript: {
                            source_map_enabled: true,
                            code_version: this.appSettings.VERSION,
                            guess_uncaught_frames: true
                        }
                    }
                }
            };
```

I also set additional props to the payload after the user logs in
```
            this.rollbar.configure({
                payload: {
                    person: {
                        id,
                        email
                    },
                    domain
                }
            });
```

**Comment by ryaa** [comment]
Please note that there is payload.request.url property which seems having a file location (for example under Android this is file:///android_asset/www/index.html)

**Comment by jessewgibbs** [comment]
Hey there,

Sorry for the slow response to this issue.  We're going to need some additional information to troubleshoot this, so we'll email you to get the additional information in a private conversation.

**Comment by dinitri-ragoo** [comment]
Hi, facing the same issue with iOS ! Any update ?
