### ISSUE TITLE
captureIp false doesn't prevent my IP Address from being captured

### ISSUE THREAD

**Issue by scottdickerson** [rollbar/rollbar.js#669]
No matter what I pass to captureIp, my browser's IP Address is still captured by rollbar in my event log.

I've tried:
```
 rollbar.global({
    enabled: true,
    verbose: true,
    captureIp: false,
    payload: {
      person: {
        id: '12345',
      },
    },
  });
```
captureIP: false, and captureIP: 'anonymize' and captureIp: 'anonymize'

**Comment by scottdickerson** [comment]
The global configuration is not overriding the individual rollbar instance configuration for captureIp I believe.  When I explicitly call configure I got it to work. Also there's a bug in the example documentation for javascript calling the field 'captureIP'

**Comment by jessewgibbs** [comment]
Hey Scott - Which version of Rollbar.js are you using?  This looks similar to an issue that we fixed for the 2.4.5 release.

**Comment by scottdickerson** [comment]
hi thanks, I'm using this version:
2.4.5

Here's the bug in the example, https://docs.rollbar.com/docs/javascript
**captureIP** should be **captureIp** and **anonymize** should be **'anonymize'**
under the GDPR section here:

```
Rollbar.configure(
  {
    enabled: true, 
    captureIP: anonymize, 
    payload: {
      person: {
      id: 12345
      }
    }
);
```

**Comment by rivkahstandig3636** [comment]
Thanks for letting us know, I updated the docs.

**Comment by rivkahstandig3636** [comment]
@shakiba Can you please investigate this issue?

**Comment by jessewgibbs** [comment]
Hi Scott,

Thanks for the additional information.  Now that you have the correct configuration, is this still not working as expected?

**Comment by jessewgibbs** [comment]
Hi Scott,

`rollbar.global` currently only accepts two configuration options, `maxItems` and `itemsPerMinute`.

This is detailed in https://docs.rollbar.com/docs/rollbarjs-configuration-reference#section-global.

It looks like the `configure` option is working correctly but we have a documentation issue, so I'm going to go ahead and close this issue.
