### ISSUE TITLE
Distribute named-amd (in addition to amd)

### ISSUE THREAD

**Issue by sandstrom** [rollbar/rollbar.js#67]
Thanks for 1.1.16,  much appreciated! :boat:  It's easier to plug Rollbar into larger applications now, where one need control over initialization. 

This suggestion (named AMD) makes it possible to import the rollbar library into e.g. Ember.js, and a few other frameworks where named modules are used. Plays well with ES6 modules too.

I've got it working by making two manual adjustments to your current amd dist:

1. Change the top line to `define('rollbar', ['exports'], function(exports) {`
2. Change the bottom line to `exports.init = wrapper.init;` [alt. you could replace `wrapper` with `exports` directly]

Your adjustment may be slightly different, these two points are only to highlight that this should be a relatively easy change.

Here is an example of a library that exports a *plain amd* and a *named-amd* (for reference):
https://github.com/instructure/ic-ajax/tree/master/dist

More on AMD:
http://requirejs.org/docs/whyamd.html

**Comment by coryvirok** [comment]
The new release v1.3.0 implements this via Webpack. Thanks!

**Comment by sandstrom** [comment]
@coryvirok Awesome, thanks!

**Comment by sandstrom** [comment]
@coryvirok tried this out, can't get it to work. I still think it's a *plain amd*, not a *named-amd*.

***
Here is an example of a library that exports both variants (for reference):
https://github.com/instructure/ic-ajax/tree/master/dist

More on AMD:
http://requirejs.org/docs/whyamd.html

**Comment by coryvirok** [comment]
I was playing around with a fix for this in my webpack fork a while back. Looks like someone implemented the same fix and got it merged into webpack mainline - https://github.com/webpack/webpack/pull/1387

Re-opening.

**Comment by coryvirok** [comment]
Please try this build and let me know if it works for you: https://github.com/rollbar/rollbar.js/pull/151

I'll get it merged and published.

**Comment by sandstrom** [comment]
@coryvirok It does, thanks! Great if this could be published to bower.

This is very useful ES6 modules (e.g. via ember-cli). A named AMD makes it really easy to import.

**Comment by coryvirok** [comment]
I'm pretty unfamiliar with Bower so please bear with me. Can you provide an example of how you are using Rollbar with and without a named AMD module? Also, what are the implications for changing the entry point in bower.json from rollbar.umd.js to rollbar.named-amd.js? Will it require people using the library to update their code/configuration at all?

Thanks!

**Comment by sandstrom** [comment]
@coryvirok No need to change anything in bower, i.e. you don't need to change the entry point (`main`). 

As long as the named amd build is available within the `dist` directory we can use it (I don't think you need to do anything more for this to be the case).

**Comment by coryvirok** [comment]
Cool. I've merged and published to v1.7.3. Thanks!
