### ISSUE TITLE
v2.4.6 valid?

### ISSUE THREAD

**Issue by victoriafrench** [rollbar/rollbar.js#672]
NPM informed us that 2.4.6 was released. However, I am seeing no information in the `changelog`, no `tag`, and no `release` here in github. It is also missing from the CDN. Is this a mistaken publish?

[404 Not Found - Cloudflare](https://cdnjs.cloudflare.com/ajax/libs/rollbar.js/2.4.6/rollbar.min.js)

**Comment by jessewgibbs** [comment]
@victoriafrench we'll investigate this today.  Sorry for the inconvenience.  In the meantime, you might want to use 2.4.5 instead.

**Comment by shakiba** [comment]
@victoriafrench Thanks! I update docs and github tags for new version.

**Comment by ericnkatz** [comment]
@shakiba Just wanted to give a heads up. 

Looks like the 2.4.7 release on npm has compiled code that says version is 2.4.6 still


https://unpkg.com/rollbar@2.4.7/dist/rollbar.umd.min.js
![image](https://user-images.githubusercontent.com/91019/46788176-9b5f9d80-cd07-11e8-85a1-556a0c8ad7f6.png)

**Comment by ericnkatz** [comment]
Heres a better link within the repository:
https://github.com/rollbar/rollbar.js/blob/master/dist/rollbar.umd.js#L501
