### ISSUE TITLE
Expose options in TS (e.g. via `getOptions()` method)

### ISSUE THREAD

**Issue by astorije** [rollbar/rollbar.js#673]
Would you be open to expose `options` in the TypeScript type definition (as `options: Configuration`?
It is, after all, available in JS, (`new Rollbar().options`).
We are creating a layer above to turn on and configure things on our end (so that all consumers do not have to configure everything by hand) and when testing, it would be nice to assert the content of the `options` object.

**Comment by jessewgibbs** [comment]
Thanks for the suggestion.   We'll add this to our backlog.

**Comment by rokob** [comment]
`options` is not exposed because if you change it directly you will almost certainly break something. The `configure` method handles transitive dependencies on the options object. So exposing it seems less than ideal.

**Comment by jessewgibbs** [comment]
I updated the title to reflect that we may expose a copy of `options` via a method so they can be used for assertions and such.

**Comment by rokob** [comment]
This is done in 2.5.0
