### ISSUE TITLE
Run filterTelemetry Outside of Pipeline to Avoid Race Condition with Network Telemetry Events

### ISSUE THREAD

**Issue by alexfoxgill** [rollbar/rollbar.js#678]
my app does a lot of polling and it drowns out other relevant telemetry. i want to filter out `GET` requests with a 2xx status code, so i added

```
filterTelemetry: function(evt) {
  return evt.type === 'network'
    && evt.body.method === 'GET'
    && evt.body.status.toString().startsWith('2');
}
```

to my rollbar config. however it seems to have no effect. i can see that my config has loaded successfully in the browser by testing in the console:

```
>>> Rollbar.options.filterTelemetry({ type: 'network', body: { method: "GET", status: 200 } })
true
>>> Rollbar.options.filterTelemetry({ type: 'network', body: { method: "POST", status: 200 } })
false
```

yet the requests still appear in the telemetry for my app

**Comment by alexfoxgill** [comment]
sure, i'm on `2.4.4` of Rollbar, using Chrome 68.0.3440.106

**Comment by jessewgibbs** [comment]
@ajtran can you try to reproduce this?

**Comment by ajtran** [comment]
@alexfoxgill I got around to do some testing on this issue and if you add a `console.log` into your `filterTelemetry` method, so it looks like this:
```
filterTelemetry: function(evt) {
  if (evt.type === 'network') {
    console.log(evt.body);
  }
  return evt.type === 'network'
    && evt.body.method === 'GET'
    && evt.body.status.toString().startsWith('2');
}
```
you can see that the `status_code` at the time the function is called is `0`. The actual body looks something like this
```
{
  "method": "GET",
  "url": "http://localhost:3000/sockjs-node/info?t=1539129186898",
  "status_code": 0,
  "start_time_ms": 1539129186898,
  "end_time_ms": null,
  "subtype": "xhr"
}
```
I believe this is the desired implementation as we begin to track and decide whether to filter telemetry events at the start of the event rather than the end, thus the `status_code` and `end_time_ms` are unknown.

**Comment by alexfoxgill** [comment]
thanks for looking into it. that's a shame, is there any chance the filter decision could be postponed until the response has returned?

**Comment by ajtran** [comment]
@alexfoxgill so, I got a chance to discuss further with the SDK engineer and I was slightly mistaken with my explanation above. Network telemetry has a race condition, thus sometimes there will be a response at the time of filtering and sometimes there won't.

The SDK engineer is looking to run the telemetry filter later in the pipeline to get outside that race condition.

**Comment by alexfoxgill** [comment]
That's great, thank you for checking
