### ISSUE TITLE
maxTelemetryEvents missing from index.d.ts

### ISSUE THREAD

**Issue by nephiw** [rollbar/rollbar.js#683]
1) The field `maxTelemetryEvents` is missing from `Configuration` in index.d.ts 
2) The comment at the top of this file indicates that it is for an older version of rollbar.js

It is defined in the API here: https://docs.rollbar.com/docs/rollbarjs-configuration-reference

I would expect all of the valid fields in the reference to exist in the type file. As is, I work around it by casting to `any` before I set it.

**Comment by jessewgibbs** [comment]
Hi there,

Can you send a URL to the version of index.d.ts that you are referring to?

**Comment by rokob** [comment]
That comment just hasn't been updated as things have changed, I will just remove it as the types should be in sync with the version they are included with. I can add `maxTelemetryEvents` and I think one other thing that might be missing.

**Comment by nephiw** [comment]
I believe that @rokob has spotted the problem, but to answer the question, @jessewgibbs , [the file is on master in index.d.ts](https://github.com/rollbar/rollbar.js/blob/master/index.d.ts)
