### ISSUE TITLE
custom error class is ignored

### ISSUE THREAD

**Issue by agriffis** [rollbar/rollbar.js#686]
Rollbar 2.4.6

```
class MyError extends Error {}
Rollbar.error(new MyError("my message"))
```

Payload has `exception.class` set to `Error` instead of `MyError`

![image](https://user-images.githubusercontent.com/50637/47459863-2bdbba80-d7ab-11e8-9883-040a67a9577c.png)

**Comment by agriffis** [comment]
For now I'm working around this with:

```
    transform: (payload, item) => {
        try {
            const exc = payload.body.trace.exception
            const name = item.err.constructor.name
            if (exc['class'] === 'Error' && typeof name === 'string') {
                exc['class'] = name
            }
        }
        catch (e) {}
    },
```

**Comment by jessewgibbs** [comment]
@agriffis thanks for informing us of this issue and posting your workaround.

@rokob can you take a look at this when you get a chance?

**Comment by agriffis** [comment]
By the way, once babel converts es6 to es5, then constructors can't be distinguished from normal functions, so uglifyjs renames them from (for example) "MyError" to "e"

You can configure uglifyjs to save some names explicitly with [`mangle.reserved`](https://github.com/mishoo/UglifyJS2#mangle-properties-options), for example I have in `vue.config.js`:

```
module.exports = {
    chainWebpack: config => {
        // Preserve custom error class names
        config.when(process.env.NODE_ENV === 'production', config => {
            config.optimization.get(
                'minimizer',
            )[0].options.uglifyOptions.mangle.reserved = [
                'ApiError',
                'ImageError',
            ]
        })
    },
}
```

Another way to work around this problem might be to recommend providing the class name as a getter, then rollbar.js could look there automatically, like this:

```
class MyError extends Error {
    get name() {
        return 'MyError'
    }
}
```

Maybe rollbar.js is already looking for something like this, and I'm just not aware of it...
