### ISSUE TITLE
Are definitions outdated?

### ISSUE THREAD

**Issue by imsergiobernal** [rollbar/rollbar.js#695]
```typescript
declare class Rollbar {
    constructor(options?: Rollbar.Configuration);
```

meanwhile

```javascript
/*
 * Rollbar - the interface to Rollbar
 *
 * @param options
 * @param api
 * @param logger
 */
function Rollbar(options, api, logger, platform) {
  this.options = _.merge(options);
  this.logger = logger;
  Rollbar.rateLimiter.configureGlobal(this.options);
  Rollbar.rateLimiter.setPlatformOptions(platform, this.options);
  this.queue = new Queue(Rollbar.rateLimiter, api, logger, this.options);
  this.notifier = new Notifier(this.queue, this.options);
  this.telemeter = new Telemeter(this.options);
  this.lastError = null;
}
```

**Comment by rokob** [comment]
That is an internal Rollbar class, the platform specific ones (e.g. https://github.com/rollbar/rollbar.js/blob/master/src/server/rollbar.js#L18 and https://github.com/rollbar/rollbar.js/blob/master/src/browser/rollbar.js#L17) are the ones referenced in the type definitions, and even there we have some extra parameters which are not mentioned which are used for testing.

**Comment by jessewgibbs** [comment]
@imsergiobernal I'm going to close this issue but if you have any further questions, please go ahead and reopen it.
