### ISSUE TITLE
Provide a more comprehensive Angular example

### ISSUE THREAD

**Issue by DoruLaz** [rollbar/rollbar.js#697]
Hi, 

I am using Rollbar with Angular 7 with captureUncaught = true. I am also setting some context info with the help of:

```javascript
rollbar.configure({
     payload: {
          context: 'SomeContext'
     }
});
```

When using the ```rollbar.error(message, error, data);``` the context is shown on the portal:

![ErrorLog](https://user-images.githubusercontent.com/42145651/51845339-0d440d00-2320-11e9-93ab-3200af16f8c1.png)

But when I send an uncaught error ```throw 'Test error';``` the context is not shown in the portal, even though both errors are issued after setting the context.

![Uncaught](https://user-images.githubusercontent.com/42145651/51845421-319fe980-2320-11e9-8d3c-54e6e146e7bd.png)

BTW, I am using Rollbar version 2.5.2

**Comment by DoruLaz** [comment]
Hi, 

It's in the app. I have two test methods. One for the ```rollbar.error()``` and one for ```throw 'Test error';```. Here are their definitions:

```javascript
sendError() {
     this.rollbar.error('Ahaaaaaaa!', null, { customId: 1, someString: 'some string', someObj: { id: 'asdasd', newValue: 12 } });
}

sendUnhandled() {
     throw 'Test error';
}
```

I have also added 2 buttons that call these 2 methods.

**Comment by DoruLaz** [comment]
Thank you for asking that question. It was my fault. I was creating 2 instances of Rollbar because I was using lazy loaded modules. I apologize for the trouble caused. I am a newbie in Angular.

Only one question before I close this issue. Can you please provide a small example component that uses  the rollbar.error('Some text', error, object) method to manually signal an error? I am having trouble understanding how to import and use the RollbarService from you example from the [official docs](https://docs.rollbar.com/docs/angular). Maybe this will help other newbies as well.

Thank you.

**Comment by rokob** [comment]
I changed the title of this to be more actionable to what would solve the problem here.

**Comment by waltjones** [comment]
The doc has been updated to include configuration of Angular components that need to access the Rollbar object. https://docs.rollbar.com/docs/angular

The referenced PR also demonstrates this in an updated and working Angular 2+ example.
