### ISSUE TITLE
Rollbar not catching error thrown in promises?

### ISSUE THREAD

**Issue by lexax666** [rollbar/rollbar.js#699]
Hi Consider the following code:
```javascript
var condition = false;
var promise = new Promise(function(resolve, reject) {
  if (condition) {
    resolve();
  }
  else {
    reject();
  }
});

promise.then(function() {
  throw new Error("thrown from resolve");
}).catch(function() {
  throw new Error("thrown from reject");
});
```

If I have captureUnhandledRejections set to false, then the error thrown in reject won't make it to rollbar. Any idea why? Agologies ahead if it is a stuipd question. I have just started javascript:(

**Comment by waltjones** [comment]
@lexax666 Javascript swallows the error thrown in the catch handler of a promise. Not a stupid question; this is a pretty non-obvious behavior of promises.

**Comment by jessewgibbs** [comment]
@lexa666 I'm going to close this issue.  If anything else comes up, feel free to open another issue or contact us via support@rollbar.com.
