### ISSUE TITLE
Rollbar with ExpressJS on Lambda/serverless-http

### ISSUE THREAD

**Issue by alexkb** [rollbar/rollbar.js#700]
I'm trying to work out how to use Rollbar with [serverless-http](https://github.com/dougmoscrop/serverless-http) on lambda as [per your lambda docs](https://docs.rollbar.com/docs/aws-lambda).

Whilst the application works, if an error gets thrown in one of the routes, rollbar never gets notified. I also see the full stack trace in the response:

    const serverless = require('serverless-http');
    const express = require('express');
   
    const Rollbar = require("rollbar");
    const rollbar = new Rollbar('your-token');
    
    exports.handler = rollbar.lambdaHandler(async (event, context, callback) => {
        const app = express();
        // Other app route code here
        const handler = serverless(app);
        const response = await handler(event, context);
        callback(null, response);
    });

I should point out that I don't have any connectivity issues with rollbar, as I've been able to send rollbar errors with my token using the Rollbar test snippet of JS outside of serverless and lambda. I' should also mention that the lambda function has an NAT gateway, so it should be able to access Rollbar's servers via the internet. My point is, I think it's the code that's wrong, not any network issue.

**Comment by rokob** [comment]
You can’t use async and a callback. I am surprised the lambda response happens correctly with this pattern. Either use the callback and then don’t mark your function as async or just return the response directly.

**Comment by alexkb** [comment]
Thanks for the reply back @rokob. When you say _"Either use the callback and then don’t mark your function as async or just return the response directly."_. I don't think the first option is possible, as I won't have the response to pass to the callback if I don't wait for the handler to return?

With the second option - if I return the response directly, do you mean send the response (`res.send()`) in the express controllers rather than in this block?

Do you actually mean this combination of components isn't compatible? I might be able to take out serverless-http if I rewrite the express middlewares, I'm guessing.

**Comment by rokob** [comment]
An async function is equivalent to a regular function that returns a Promise, whatever you return from the async function is what the Promise gets fulfilled with, so `return response;` inside the async function should be good enough.

This should do what you want (I think):

```
exports.handler = rollbar.lambdaHandler(async (event, context) => {
    const app = express();
    // Other app route code here
    const handler = serverless(app);
    return await handler(event, context);
});
```

**Comment by alexkb** [comment]
With this approach, I seem to get false positives for "Function timed out" even though the request was valid and the response was passed back to the client successfully.

Additionally, another route that is setup to throw an Error for testing Rollbar, didn't log the error until I told express to use Rollbar as the error handler too `app.use(rollbar.errorHandler());`, and like the successful request above, a "Function timed out" is received by rollbar too.

It wasn't until I initialized the Rollbar service with `captureLambdaTimeouts: false,` that it stopped reporting the false positives. If I do have lambda timeouts though, it would be nice if these could be captured, without the false positives. Any suggestions @rokob?

For clarity this is the code:

	const app = express();
	// setup middlewares, routes, etc for app ...

	const Rollbar = require("rollbar");
	const rollbar = new Rollbar({
	  accessToken: process.env.ROLLBAR_TOKEN,
	  environment: process.env.ENVIRONMENT_NAME,
	  captureLambdaTimeouts: false,
	});

	app.use(rollbar.errorHandler());

	exports.handler = rollbar.lambdaHandler(async (event, context) => {
	  const handler = serverless(app);
	  return await handler(event, context);
	});

**Comment by sahilchopra** [comment]
Any update on this? 
I am also trying to find correct way to use rollbar with AWS lambda
