### ISSUE TITLE
throw new TypeError('Expected a string, got "${typeof value}"');

### ISSUE THREAD

**Issue by narada85** [rollbar/rollbar.js#702]
I'm using node 0.12.18
rollbar version 2.5.2

/app/node_modules/rollbar/node_modules/request-ip/index.js:15

require('dotenv').config({silent: true});

var express = require('express');

var Rollbar = require('rollbar');
var rollbar = new Rollbar({
  accessToken: process.env.ROLLBAR_ACCESS_TOKEN,
  captureUncaught: true,
  captureUnhandledRejections: true
});

var app = express();

app.use(rollbar.errorHandler());

tx!

**Comment by narada85** [comment]
i do not get this issue in local machine. only comes on server environment.

**Comment by jessewgibbs** [comment]
@waltjones could you take a look into this?

**Comment by waltjones** [comment]
Hi @narada85, it looks like there is an invalid value for the `x-forwarded-for` request header. Can you reply with the value of this header on a request that fails? Also, is there a load balancer or proxy in the request path that would be adding this header?

**Comment by jessewgibbs** [comment]
@narada85 I'm going to close this issue since there's been no response.  If it's still a problem, please reopen and reply to the previous question.
