### ISSUE TITLE
Update Segment.io integration

### ISSUE THREAD

**Issue by coryvirok** [rollbar/rollbar.js#707]
Looks like we have a pretty old version being used in our Segment integration. We need to upgrade [this](https://github.com/segment-integrations/analytics.js-integration-rollbar/blob/master/lib/index.js) to use our latest version + any changes necessary to get the Segment integration working with our latest release. 

Finally, we need to make updating the Segment integration part of our release plan for new versions of rollbar.js. I'd say we really only need to do it for minor version and higher changes unless there's a security vulnerability that gets fixed.

**Comment by rokob** [comment]
I didn't even know we had a Segment integration. I will add it to the release doc as a first step.

**Comment by brianr** [comment]
This is being tracked over at https://github.com/segment-integrations/analytics.js-integration-rollbar/pull/23

**Comment by waltjones** [comment]
Looks like Segment has now moved integrations to a monorepo, and Rollbar isn't there at all.
https://github.com/segment-integrations/analytics.js-integration-rollbar/pull/23
https://github.com/segmentio/analytics.js-integrations

**Comment by coryvirok** [comment]
Great catch, Walt.

Artur, can you follow up with the Segment team and make sure that our
integration is added to their new repo, (assuming this is the right place
for it?)

Cory Virok, @coryvirok <http://twitter.com/coryvirok>
Co-founder and CTO, Rollbar <http://rollbar.com/>

**Comment by ArturMoczulski** [comment]
Looks like we should submit a PR to the integrations repo. @waltjones can you move https://github.com/segment-integrations/analytics.js-integration-rollbar/ into their new monorepo?

**Comment by waltjones** [comment]
The Segment team did eventually move this to the mono-repo, and updated the Rollbar.js snippet.

https://github.com/segmentio/analytics.js-integrations/tree/master/integrations/rollbar
