### ISSUE TITLE
Firefox NS_ERROR_* logged with less info than possible.

### ISSUE THREAD

**Issue by Matrosskin** [rollbar/rollbar.js#712]
It is possible to have a couple of spatial errors in Firefox which have unexpected type and they logged by Rollbar with a small piece of info. For such errors logged on their "toString" value because they have not "Error" type, but they have structure very similar to usual Errors (for example they have property "stack"). So it would be great to improve catching of such errors.
Here is an example to reproduce error: http://fiddle.tinymce.com/Xofaab/3
Here is a full list of possible errors: https://developer.mozilla.org/en-US/docs/Mozilla/Errors

Also, I think, it would be awesome to pass the origin error object into Rollbar "transform" callback as argument to be able to write own logic base on origin error, not only base on generated payload.

**Comment by waltjones** [comment]
@Matrosskin I can see the relevant NS exception object when I load the entire http://fiddle.tinymce.com/Xofaab/3, but not when I paste just your code (plus tinymce library of course) into an HTML file. In fact it runs without any error.

I have looked for a way to be able to generate these in Firefox, but the `Components` class, which seems to be required, isn't available. Do you have a more self-contained way to generate this error type?

**Comment by Matrosskin** [comment]
@waltjones here is I prepared repo for reproducing https://github.com/Matrosskin/firefox-ns-error-example (or as a page https://matrosskin.github.io/firefox-ns-error-example/ - just open it in Firefox). It is the only one way to reproduce error which I was able to found in the internet.

**Comment by waltjones** [comment]
@Matrosskin Yes, that worked for me. Thank you, and I'll let you know what I find out.

**Comment by Matrosskin** [comment]
@waltjones do you have any info about date of next release?

**Comment by waltjones** [comment]
@Matrosskin Likely today. I'll reply here.

**Comment by waltjones** [comment]
@Matrosskin v2.5.5 is published now.
