### ISSUE TITLE
Feature Request: De-minify stack trace before sending payload to Rollbar

### ISSUE THREAD

**Issue by jessicahsieh** [rollbar/rollbar.js#714]
For customers who perhaps have too many source maps/deploy too often to upload all source maps to Rollbar, but cannot make their source maps public (to use the automatic download method).

internal - https://app.intercom.io/a/apps/rlisg82q/inbox/inbox/813334/conversations/21363181745

**Comment by jessicahsieh** [comment]
similar to something like this: https://github.com/evanw/node-source-map-support

**Comment by brianr** [comment]
For a little clarity - this request is most relevant for *server side* uses of rollbar.js, where you already have the source map around, and the source mapping step is necessary because of using a language that compiles to Javascript e.g. TypeScript.
