### ISSUE TITLE
Add public interface to serialize payloads and send serialized payloads

### ISSUE THREAD

**Issue by brianr** [rollbar/rollbar.js#723]
Motivation is this use case from React Native / Expo: there is a need to write the payload (in javascript) to a disk, then send it later on restart

To accomplish this, rollbar.js can provide:

- a way to generate the final payload and return it as a string (i.e. the serialized json payload) - i.e. `rollbar.serializePayload(payload)`
- a way to take a serialized string payload and send it over the network to api.rollbar.com - i.e. `rollbar.sendPayloadStr(payloadStr)`

**Comment by jjabba** [comment]
Here is the related expo documentation, explaining how [expo deals with errors in production](https://docs.expo.io/versions/latest/guides/errors/). 

Basically, when an error occurs you can intercept it, and quickly store relevant data using `ErrorRecovery.setRecoveryProps(yourRelevantData)`. As explained [here](https://docs.expo.io/versions/latest/sdk/error-recovery/).

Once expo has killed and restarted your app, it will be able to access the data again via a prop `exp.errorRecovery` which is passed to your app. This is where it would make sense to pass the data on to rollbar via an asynchronies call to the rollbar.error() function.

**Comment by waltjones** [comment]
The referenced PR enables this for rollbar.js and any use case that uses rollbar.js directly.

For users of rollbar-react-native, an update is needed in that repo because it wraps both the config and the public endpoints for rollbar.js.

@jjabba I'm not familiar enough with Expo to know which way you might be including Rollbar.

**Comment by jjabba** [comment]
Thanks @waltjones! While I am using `rollbar-react-native`, I'm not actually using the wrapped Client, as I'm unable to link the native rollbar client while still using expo. I get around the initialization by importing and using `import Client from 'rollbar/src/react-native/rollbar'`

I've already prepared the `checkIgnore` hook in my configuration, looking forward to the PR making it into an actual release. 

What is the release cadence?

**Comment by jjabba** [comment]
While I am using rollbar-react-native, I'm not actually using the wrapped Client, as I'm unable to link the native rollbar client while still using expo. I get around the initialization by importing and using import Client from 'rollbar/src/react-native/rollbar'

**Comment by waltjones** [comment]
@jjabba good to know. Thank you!

I'll work on getting a release out for you asap.

**Comment by waltjones** [comment]
@jjabba this is now published in v2.6.0.

**Comment by brianr** [comment]
Reopening this based on the needs described in this comment on the PR: https://github.com/rollbar/rollbar.js/pull/724#issuecomment-485600261
