### ISSUE TITLE
Webworker Support Broken in 2.7.0

### ISSUE THREAD

**Issue by axrs** [rollbar/rollbar.js#732]
Since upgrading Rollbar.js to `2.7.0` (from `2.6.1`), our Browser based WebWorkers now throw errors as Rollbar tries to access undefined `window` references.

We believe that it's related to the Webpack 4 update passing a direct window into the initialisation.

https://github.com/rollbar/rollbar.js/blob/fa0843d8f316e256a386b819a394118d52dbf36c/dist/rollbar.noconflict.umd.js#L10

**Comment by rokob** [comment]
Pretty sure it was https://github.com/rollbar/rollbar.js/commit/41dba6249b5e9583228a648bb55b1d943060010e

**Comment by waltjones** [comment]
Will get a fix out asap.

**Comment by waltjones** [comment]
Fix is in 2.7.1.
