### ISSUE TITLE
uncaughtException: Callback was already called

### ISSUE THREAD

**Issue by Adiii717** [rollbar/rollbar.js#734]
` /home/user/app/node_modules/winston-rollbar/lib/winston-rollbar.js:90:31","  
    at /home/user/app/node_modules/winston-rollbar/node_modules/rollbar/lib/notifier.js:303:11","    
    at ClientRequest.<anonymous> (/home/user/app/node_modules/winston-rollbar/node_modules/rollbar/lib/api.js:112:5)","
        at emitOne (events.js:116:13)","    at ClientRequest.emit (events.js:211:7)","  
          at TLSSocket.socketErrorListener (_http_client.js:387:9)"," 
             at emitOne (events.js:116:13)","    at TLSSocket.emit (events.js:211:7)"," 
                at onwriteError (_stream_writable.js:408:12)","  
                  at onwrite (_stream_writable.js:430:5)","   
 at _destroy (internal/streams/destroy.js:39:7)","   
  at TLSSocket.Socket._destroy (net.js:561:3)","   
   at TLSSocket.destroy (internal/streams/destroy.js:32:8)"," 
      at WriteWrap.afterWrite [as oncomplete] (net.js:869:10)"],
      "level":"error","message":"uncaughtException: Callback was already called.","timestamp":"2019-05-22T22:48:55.383Z"}`

**Comment by waltjones** [comment]
@Adiii717 Can you offer some context for this?

**Comment by Adiii717** [comment]
@waltjones we are using a winston-rollbar module which is dependency is rollbar and we are also using rollbar, but the problem is that I am not sure from which logs it throws this exception as we are logging each and every request so above is the trace that  I got an exception.
Here is another complete trace that might help you 
`{"date":"Wed May 22 2019 18:48:55 GMT-0400 (EDT)","process":{"pid":832,"uid":1000,"gid":1000,"cwd":"/home/user/app","execPath":"/usr/bin/node","version":"v8.9.4","argv":["/usr/bin/node","/home/user/app/server-xmpp.js"],"memoryUsage":{"rss":346558464,"heapTotal":297840640,"heapUsed":187711256,"external":3888891}},"os":{"loadavg":[0.7578125,0.7041015625,0.6728515625],"uptime":6191690},"trace":[{"column":31,"file":"/home/user/app/node_modules/winston/node_modules/async/lib/async.js","function":null,"line":38,"method":null,"native":false},{"column":16,"file":"/home/user/app/node_modules/winston/lib/winston/logger.js","function":null,"line":238,"method":null,"native":false},{"column":31,"file":"/home/user/app/node_modules/winston-rollbar/lib/winston-rollbar.js","function":null,"line":90,"method":null,"native":false},{"column":11,"file":"/home/user/app/node_modules/winston-rollbar/node_modules/rollbar/lib/notifier.js","function":null,"line":303,"method":null,"native":false},{"column":5,"file":"/home/user/app/node_modules/winston-rollbar/node_modules/rollbar/lib/api.js","function":null,"line":112,"method":null,"native":false},{"column":13,"file":"events.js","function":"emitOne","line":116,"method":null,"native":false},{"column":7,"file":"events.js","function":"ClientRequest.emit","line":211,"method":"emit","native":false},{"column":9,"file":"_http_client.js","function":"TLSSocket.socketErrorListener","line":387,"method":"socketErrorListener","native":false},{"column":13,"file":"events.js","function":"emitOne","line":116,"method":null,"native":false},{"column":7,"file":"events.js","function":"TLSSocket.emit","line":211,"method":"emit","native":false},{"column":12,"file":"_stream_writable.js","function":"onwriteError","line":408,"method":null,"native":false},{"column":5,"file":"_stream_writable.js","function":"onwrite","line":430,"method":null,"native":false},{"column":7,"file":"internal/streams/destroy.js","function":"_destroy","line":39,"method":null,"native":false},{"column":3,"file":"net.js","function":"TLSSocket.Socket._destroy","line":561,"method":"_destroy","native":false},{"column":8,"file":"internal/streams/destroy.js","function":"TLSSocket.destroy","line":32,"method":"destroy","native":false},{"column":10,"file":"net.js","function":"WriteWrap.afterWrite [as oncomplete]","line":869,"method":"afterWrite [as oncomplete]","native":false}],"stack":["Error: Callback was already called.","    at /home/user/app/node_modules/winston/node_modules/async/lib/async.js:38:31","    at /home/user/app/node_modules/winston/lib/winston/logger.js:238:16","    at /home/user/app/node_modules/winston-rollbar/lib/winston-rollbar.js:90:31","    at /home/user/app/node_modules/winston-rollbar/node_modules/rollbar/lib/notifier.js:303:11","    at ClientRequest.<anonymous> (/home/user/app/node_modules/winston-rollbar/node_modules/rollbar/lib/api.js:112:5)","    at emitOne (events.js:116:13)","    at ClientRequest.emit (events.js:211:7)","    at TLSSocket.socketErrorListener (_http_client.js:387:9)","    at emitOne (events.js:116:13)","    at TLSSocket.emit (events.js:211:7)","    at onwriteError (_stream_writable.js:408:12)","    at onwrite (_stream_writable.js:430:5)","    at _destroy (internal/streams/destroy.js:39:7)","    at TLSSocket.Socket._destroy (net.js:561:3)","    at TLSSocket.destroy (internal/streams/destroy.js:32:8)","    at WriteWrap.afterWrite [as oncomplete] (net.js:869:10)"],"level":"error","message":"uncaughtException: Callback was already called.","timestamp":"2019-05-22T22:48:55.383Z"}`

**Comment by waltjones** [comment]
@Adiii717 winston-rollbar is using https://github.com/rollbar/node_rollbar which has been deprecated for several years in favor of https://github.com/rollbar/rollbar.js. Actually, winston-rollbar was last updated 4 years ago and is pinned to a version of node_rollbar (0.5.6) also 4 years old.

What rollbar version are you using outside of winston-rollbar?

By the way, the stack traces appear to be all winston-rollbar.

**Comment by Adiii717** [comment]
we are using `rollbar 0.6.3` outside. and also we are using this winston-rollbar for a long time, but the issue starts last week and experience exception many times so I thought something updated on your side as Winston-rollbar not updated.

**Comment by Adiii717** [comment]
@waltjones you can check Winston-rollbar package.json I think their readme is not updated.
they mentioned `rollbar 0.5.6`
https://github.com/Ideame/winston-rollbar/blob/master/package.json

**Comment by waltjones** [comment]
Because neither node_rollbar nor winston-rollbar has been maintained in so long, there are an unknown number of compatibility issues with other packages that have changed in the intervening years.

People have forked and updated versions of winston-rollbar that use rollbar.js, and are not locked to an older version. Perhaps one of these can work for you in your situation.
https://www.npmjs.com/package/winston-rollbar2
https://www.npmjs.com/package/winston-transport-rollbar-3

Also, for your standalone Rollbar, you should be able to switch to Rollbar.js though you'd have some code changes. The interface is slightly different.

**Comment by Adiii717** [comment]
Thanks, @waltjones I will check out the above if they can solve our problem.

**Comment by Adiii717** [comment]
For now, going to handling this exception at our end. Will check later with rollbar2 and 3.
