### ISSUE TITLE
Angular SourceMaps configuration:

### ISSUE THREAD

**Issue by AFDevMike** [rollbar/rollbar.js#737]
Hello, I sunk some time in getting source maps to work for our Angular project:

Following this link: https://docs.rollbar.com/docs/source-maps#section-enabling-source-map-translation-in-rollbar  in correlation with: https://docs.rollbar.com/docs/angular#section-angular-2-and-later.

I was attempting to edit the const rollbarConfig in the latter to configure `code_version`.
The typeDef file for the configuration has `code_version` as well as `codeVersion`.  It does not have `guess_uncaught_frames` nor `source_map_enabled`;

I ended up configuring like so:
```
import { BrowserModule } from '@angular/platform-browser';
import {   Injectable,  InjectionToken,  NgModule,  ErrorHandler,  Inject } from '@angular/core';
import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import * as Rollbar from 'rollbar';

const rollbarConfig: Rollbar.Configuration = {
  accessToken: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  captureUncaught: true,
  captureUnhandledRejections: true,
  // code_version: '0004',
  // codeVersion: '0004'
};

@Injectable()
export class RollbarErrorHandler implements ErrorHandler {
  constructor(@Inject(RollbarService) private rollbar: Rollbar) {
    this.rollbar.configure({ payload: {
      client: {
        javascript: {
          source_map_enabled: true, //this is now true by default
          code_version: '0004',
          // Optionally have Rollbar guess which frames the error was thrown from
          // when the browser does not provide line and column numbers.
          guess_uncaught_frames: true
        }
      }
    }});
  }

  handleError(err:any) : void {
    this.rollbar.error(err.originalError || err);
  }
}

export function rollbarFactory() {
    return new Rollbar(rollbarConfig);        
}

export const RollbarService = new InjectionToken<Rollbar>('rollbar');

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule
  ],
  providers: [
    { provide: ErrorHandler, useClass: RollbarErrorHandler },
    { provide: RollbarService, useFactory: rollbarFactory }
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

Can the call to `this.rollbar.configure` with the `{}` object be configured before the library has been initialized in a strongly typed way?  I am not sure if its an over sight, or I missed something but the commented out attempts for const `rollbarConfig: Rollbar.Configuration` did not seem to work.

Thank you

**Comment by waltjones** [comment]
@AFDevMike I think you're asking for TypeScript definitions for `guess_uncaught_frames` and `source_map_enabled`. I think those can be added for the next release. I can also test with `code_version` and `codeVersion` and see if there are issues there.

`this.rollbar.configure` can be called only after `new Rollbar()`. I don't expect that to help in your situation.

If the issue is not related to TypeScript definitions, and there's a source maps configuration problem, this comment (https://github.com/rollbar/rollbar.js/issues/728#issuecomment-495409109) isn't specific to Create React App, and has general advice about using source maps with Rollbar.

**Comment by AFDevMike** [comment]
Ultimately I was unable to get `code_version` and `codeVersion` to work.  

I was able to make it work by using `this.rollbar.configure()`.  This is on pause for me but I am under impression I could move that to the TypeDef'd property of `Configure.payload: object`.

Hope this helps.

**Comment by waltjones** [comment]
@AFDevMike Yes, that helps. Thank you!

**Comment by waltjones** [comment]
@AFDevMike Your example:
```
const rollbarConfig: Rollbar.Configuration = {
  accessToken: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  captureUncaught: true,
  captureUnhandledRejections: true,
  code_version: '0004',
};
```
fails because `code_version` is in the root of the configuration object. It should succeed when in the correct location:
```
const rollbarConfig: Rollbar.Configuration = {
  payload: {
    client: {
      javascript: {
        code_version: '0004',
```
Same for `guess_uncaught_frames` and `source_map_enabled`. These should all go in `payload: { client: { javascript: {}}}`, which your `this.rollbar.configure` example does correctly.

**Comment by AFDevMike** [comment]
Thank you,

I ultimately have it working with the following as expected:

```
  const rollbarConfig = {
    accessToken: 'abcd123',
    captureUncaught: true,
    captureUnhandledRejections: true,
    payload: {
      client: {
        javascript: {
          source_map_enabled: true,
          code_version: myCodeVersionVar,
          guess_uncaught_frames: true
        }
      }
    } 
  };

  return new Rollbar(rollbarConfig);
```

What was not clear to me was:

The configuration interface defined in the Angular type def file index.d.ts looks like the following:
```
    export interface Configuration {
        accessToken?: string;
        version?: string;
        environment?: string;
        codeVersion?: string;
        code_version?: string;
        scrubFields?: string[];
        overwriteScrubFields?: boolean;
        scrubHeaders?: string[];
        logLevel?: Level;
        reportLevel?: Level;
        uncaughtErrorLevel?: Level;
        endpoint?: string;
        verbose?: boolean;
        enabled?: boolean;
        captureUncaught?: boolean;
        captureUnhandledRejections?: boolean;
        payload?: object;
        maxItems?: number;
        itemsPerMinute?: number;
        ignoredMessages?: string[];
        hostWhiteList?: string[];
        hostBlackList?: string[];
        filterTelemetry?: (e: TelemetryEvent) => boolean;
        autoInstrument?: AutoInstrumentOptions;
        maxTelemetryEvents?: number;
        telemetryScrubber?: TelemetryScrubber;
        includeItemsInTelemetry?: boolean;
        scrubTelemetryInputs?: boolean;
        sendConfig?: boolean;
        captureEmail?: boolean;
        captureUsername?: boolean;
        captureIp?: boolean | "anonymize";
        captureLambdaTimeouts?: boolean;
        transform?: (data: object) => void;
        checkIgnore?: (isUncaught: boolean, args: LogArgument[], item: object) => boolean;
        onSendCallback?: (isUncaught: boolean, args: LogArgument[], item: object) => void;
    }
```

I failed to realize I need to pass the code_version inside the `payload` of type `object` with the shape you described as opposed to one of the 2 interface properties:
```
codeVersion?: string;
code_version?: string;
```
I made an assumption the configuration of code_version was strongly typed as it happens to exist as a property of the  `Rollbar.Configuration` object.

Again, I am configured and up a running.  Feel free to close.
