### ISSUE TITLE
Feature request: Provide a way to upload minified files through the source map upload API

### ISSUE THREAD

**Issue by IgorCRD** [rollbar/rollbar.js#739]
Hello there,

Thank you for all the work you all have put into this library. It has been a great help to our team.

In our current project, we are using NextJs to help us with our react application and I noticed that stacks that use SSR commonly have some kind of transpiling going on at their server side as well as on client side javascript code. I think rollbar currently does not support source maps for server-side code.

We have been using the upload pre-deploy method for our client-side code and it works amazing. It would be very handy to have the same kind of support for server-side code.

The current source map upload API supports the following fields:

1. **access_token**: Your rollbar access token. Should be a post_server_item token (the same one that you use for sending deploy notifications)
2. **version**: A string identifying what version of your code this source map package is for. We recommend using the version number/string from your version control system, e.g. a full Git SHA. Note that you will need to pass this same string in the on-page JS snippet, as documented above.
3. **minified_url **: The URL or filename of the minified file. Can start with http: or https:, which we'll strip off.
4. **source_map**: The contents of the source map, as a multipart file upload.

Maybe adding an optional field like minified_source and when present this field would make minified_url be used only for matching, today I think it is used for retrieving the minified files and for matching.

Everything I am discussing here is my understanding of how rollbar works based only on my reading of the rollbar documentation. So if I said anything wrong forgive me and feel free to point me the correct direction 😄.

**Comment by waltjones** [comment]
@IgorCRD Thank for the suggestions! One thing I can clarify is, `minified_url` in the current API is just sending the filename string, not the contents of the file. It is only used to map the stack location to the correct map file. For example, if testing locally and the URL is in the format "file:///", source mapping will still work fine even though the Rollbar dashboard can't download anything from that URL.  (There is also the option to send original source files for code snippets, but that is separate from the required `minified_url`.)  

The current API should work for server side JS, as long as the minified_url string accurately matches what shows up in the stack trace. However, there are people who would like to not transmit source maps of their server-side code, and would like to do the mapping on the server before sending the stack trace to Rollbar. This is something we are currently working on, and expect to have available in the near future for Node.js.

**Comment by IgorCRD** [comment]
Hey, @waltjones,

Thank you very much for your response =)

I saw that you have tagged #738 as a fix for this issue, but I didn't get how can I act upon that on my project. I tried reading the typescript example project, but it didn't help my understanding on how to fix my problem. Could you please link some reference or docs so I can wrap my head around the changes merged on #738 ?

Thank you in advance.

**Comment by waltjones** [comment]
@IgorCRD Sorry for the very late reply. 

When you set `config.nodeSourceMaps = true` and your min js has sourceMappingURL comments included, Rollbar.js will automatically perform source mapping of stack traces on the server side. There is no need to upload anything to Rollbar, as all the mapping is performed in your server side environment. This is only for Node JS.

**Comment by IgorCRD** [comment]
@waltjones,
No problem, I am glad you replied and that the solution is so simple.

I guess that solves my issue. I will give it a try.

Thank you!
