### ISSUE TITLE
Rollbar 1.2.1 not sending out requests (broken)

### ISSUE THREAD

**Issue by xLegoz** [rollbar/rollbar.js#74]
I'm not sure what the exact issue is, but I've noticed that after upgrading an application from 1.1.15 to 1.2.1 there were no outbound requests from Rollbar. Both the options and the error pushing. Because of this I've downgraded back to 1.1.15, which works without a problem.

If there is anything I can do to help debug this please let me know, I'd be happy to help.

**Comment by brianr** [comment]
Thanks for the report... can you tell us more about how you're using/loading Rollbar? Are you using the standard snippet from our docs? The AMD or commonjs version? Something else?

If this is on the web somewhere that we can see it in action, that'd be super helpful as well.

**Comment by xLegoz** [comment]
I'm using the standard snippet from the docs.

Located before any JS on our page is the following
```html
  <script type="text/javascript">
  var _rollbarConfig = {
      accessToken: ACCESS_TOKEN,
      captureUncaught: true,
      verbose: false,
      payload: {
          environment: (window.location.host === DOMAIN) ? "production" : "development",
          person: {
            id: ID,
            username: USERNAME,
            organization_name: ORGANIZATION_NAME,
            organization_id: ORGANIZATION_ID
          }
      },
      enabled: true
  }
  </script>
  <script src="/libraries/rollbar/rollbar.js"></script>
```

Some more information of what's on the page is:
- angularjs
- jquery
- google jsapi
- bootstrap (with JS)
- leafletjs (mapping library)
- d3

Over the weekend I'll look into creating a page I can share where this problem is reproduced.

**Comment by evanliomain** [comment]
I've get the same kind of error. I use the AMD version. And I figure out that the Rollbar AMD object just exposes the `.init` method.
So, when we try a `Rollbar.configure`, `Rollbar.error`, or whatever... we get a nice 
```
undefined is not a function.
```

Hope is't helpfull.

**Comment by coryvirok** [comment]
@evanliomain You will want to use the instance created via `init()` for `.configure()` and `.error()`.

https://github.com/rollbar/rollbar.js/tree/master/examples/requirejs#using-rollbar-with-requirejs

**Comment by coryvirok** [comment]
If this is still an issue, please re-open. Thanks!
