### ISSUE TITLE
Allow Rollbar to detect and parse embedded JSON that appears as values in the payload

### ISSUE THREAD

**Issue by letaniaferreira** [rollbar/rollbar.js#742]
As background, note that the whole Rollbar payload itself is a JSON object. The Rollbar API is designed to send and receive JSON. Customer suggests that where strings appear in the payload, we detect that it is JSON (which isn't generally going to be true, but is in his case), and parse it. So we would find and parse JSON within the JSON payload itself.

Here's why we'd proceed carefully if we added this feature:

• JSON detection isn't perfect when you don't already know the string is supposed to be JSON. The examples he gives are HTTP response bodies that appear in the telemetry data. Some of this data will be JSON, but a lot of it won't. It will vary for every situation where rollbar.js is installed. (There would be a content type at the time the response is received. I don't know off hand how accessible that would be at the point where we would parse it, but there would be other situations where we wouldn't have the content type.)
• JSON decoding may or may not work depending on whether the JSON is well formed. The whole reason people use Rollbar is because they have bugs. If there's a bug in the customer's JSON (or 3rd party API calls, etc.) we won't be able to parse the JSON. At that point, it's not going to get scrubbed anyway even though we have at least implied that it will be reliably scrubbed. You don't want a HIPAA or PCI customer to suddenly leak a lot of data because of an undiscovered bug in their own JSON. It would have been better to scrub the entire HTTP response, which rollbar.js currently does just fine.
• There's a performance penalty for the extra detection and decoding.

All of the above things may be acceptable, or may be mitigated. For example, have the feature disabled by default and customers can decide for themselves whether they should enable it. It's potentially a good improvement to the SDK.

It gives customers the opportunity to weigh in with both pros and cons, allows our product team to consider it, and so on.

**Comment by letaniaferreira** [comment]
Related ticket https://app.intercom.io/a/apps/rlisg82q/inbox/inbox/813334/conversations/22591664577

**Comment by waltjones** [comment]
Current rollbar.js now handles this for JSON request bodies, as well as JSON request/response bodies in telemetry.
