### ISSUE TITLE
rollbar@2.8.0 is broken -- missing dependency on `buffer-from`

### ISSUE THREAD

**Issue by feross** [rollbar/rollbar.js#746]
You didn't add `buffer-from` to `package.json` and as a result you broke production for me.

The line where you started using `buffer-from` is here: https://github.com/rollbar/rollbar.js/commit/e6bce32676c771b76d54ff6a5c9cf7e4d8e06cf1#diff-0238d0dd36c5a895587fa91836178b73R4

But it was never added to `package.json`. If it incidentally works some of the time, it's because some other dependency has brought in `buffer-from` for you and you got lucky. Please fix.

![](https://media.giphy.com/media/nrXif9YExO9EI/giphy.gif)

**Comment by feross** [comment]
<img width="367" alt="Screen Shot 2019-07-05 at 5 40 58 PM" src="https://user-images.githubusercontent.com/121766/60749254-1464ec00-9f4c-11e9-8336-d54bed95890a.png">

**Comment by brianr** [comment]
Hi @feross - are you able to pin to the prior release? That is probably the fastest way to resolve your issue, if your production services are impacted by this. The previous release is `2.7.1`

**Comment by brianr** [comment]
@feross can you provide more details about your environment and the error(s) you see when trying to install rollbar 2.8.0? I just tried installing in a fresh project and it worked:

```
brian@MacBook-Pro-3:~/Development/test-rollbar$ npm install rollbar
test-rollbar@1.0.0 /Users/brian/Development/test-rollbar
└── rollbar@2.8.0 

npm WARN test-rollbar@1.0.0 No description
npm WARN test-rollbar@1.0.0 No repository field.
```

**Comment by feross** [comment]
> are you able to pin to the prior release?

Yeah, no worries. I resolved the issue on my end. But you might be breaking a whole bunch of other people's CI, etc.

> can you provide more details about your environment

The error doesn't happen at install time. If happens when you actually include rollbar and it attempts to require a package which does not exist

**Comment by feross** [comment]
Try `require('rollbar')`

**Comment by waltjones** [comment]
@feross Try 2.8.1 and let me know if you have any problem?

**Comment by feross** [comment]
2.8.1 works for me. Thanks for the quick fix.

**Comment by feross** [comment]
![](https://media.giphy.com/media/QAsBwSjx9zVKoGp9nr/giphy.gif)
