### ISSUE TITLE
Vue.js docs misleading, possibly out of date

### ISSUE THREAD

**Issue by pcrglennon** [rollbar/rollbar.js#750]
Hi, I'm setting up Source Maps right now, and was having issues getting set up by following the docs. Technically I'm using the [vue-rollbar package](https://github.com/Zevran/vue-rollbar), but since that's really just a very shallow wrapper around this package, which is why I'm posting the Issue here and not on that repo. Also, the docs in question ([Vue.js](https://docs.rollbar.com/docs/vue-js)) are hosted by Rollbar itself.

Following the example in the docs, my Rollbar configuration looks like this:

```js
Vue.use(Rollbar, {
  accessToken: REPLACE_WITH_ROLLBAR_CLIENT_ACCESS_TOKEN,
  captureUncaught: true,
  captureUnhandledRejections: true,
  enabled: true,
  source_map_enabled: true,
  environment: 'production',
  payload: {
    client: {
      javascript: {
        code_version: REPLACE_WITH_SOURCE_MAP_VERSION,
      },
    },
  },
});
```

And I've uploaded the Source Map files to Rollbar, and have confirmed that the `code_version` is correct. But when I trigger an errror to force an Item to be reported Rollbar, the Item says source maps were not available for the files in question ("Source maps were not available for some minified Javascript files in this traceback...").

After looking into other pages in the docs, I tried setting `source_map_enabled` within `payload.client.javascript`, i.e.:

```js
payload: {
  client: {
    javascript: {
      source_map_enabled: true, // THIS is the addition which seems to fix it
      code_version: REPLACE_WITH_SOURCE_MAP_VERSION,
    },
  },
},
```

And that does work as expected! So my problem is solved, but I just want to call this out in case the Vue.js docs need to be updated.

**Comment by waltjones** [comment]
@pcrglennon Thank you for the report. Doc is updated.

**Comment by pcrglennon** [comment]
Thank you!
