### ISSUE TITLE
TypeError: setting getter-only property "debug"

### ISSUE THREAD

**Issue by georgewitteman** [rollbar/rollbar.js#751]
We're occasionally getting the error in the title when Rollbar is trying to override `console.debug` for telemetry in [telemetry.js line 380](https://github.com/rollbar/rollbar.js/blob/5d0a160b29a2252ee71e085655b569a6191e8dba/src/browser/telemetry.js#L380). So far I have not been able to reproduce this, and it only seems to be happening occasionally. I'm wondering if anyone else has seen this issue before or might have any ideas on a way to debug it?

**Comment by waltjones** [comment]
@georgewitteman Do you know from past occurrences whether this might be related to a specific browser?  And, do these show up in your Rollbar dashboard?

**Comment by katcoutts** [comment]
Hi. I'm seeing this same issue as described above. It's showing up in our dashboard as 'TypeError: setting getter-only property "debug"'. It appears to happen on various browsers and OS and we haven't been able to replicate it.

**Comment by ggborcean** [comment]
Internal - https://app.intercom.io/a/apps/rlisg82q/inbox/inbox/813334/conversations/23401534925

**Comment by katcoutts** [comment]
Hi. I got some feedback to say this issue should be fixed in the next release. Is that right and do you know when that'll be available?

**Comment by waltjones** [comment]
Hi @katcoutts Yes, the fix is linked above, and release 2.12.3 looks on track for this afternoon. I'll leave a note here, and you'll also be notified through your support ticket.

**Comment by waltjones** [comment]
v2.12.3 is released.

**Comment by katcoutts** [comment]
Thank you for sorting this so promptly @waltjones
