### ISSUE TITLE
TypeError: e is undefined 

### ISSUE THREAD

**Issue by vishal021** [rollbar/rollbar.js#76]
TypeError: e is undefined
...wrapped){b._wrapped=function(){try{return b.apply(this,arguments)}catch(c){throw...

I have integrated rollbar API for javascript. In my firexfox -> console -> All tab I am getting above error message. I have rollbar config script immediately after body tag.  I tried to debug the cause of this error and it seems error is in below line:

var a=b.createElement("script"), e=b.getElementsByTagName("script")[0];

I don't know what is causing e as undefined.

**Comment by brianr** [comment]
Hi @vishal021 - did you figure out what was causing this for you?
