### ISSUE TITLE
Bring back strict mode

### ISSUE THREAD

**Issue by XavCamp** [rollbar/rollbar.js#797]
We have a build that include Rollbar dist in one of our files, that gets minified in strict mode. Since v2.7.0, it complains about function declaration:

```
ddEventListener;o._rollbarOldAdd&&o.belongsToShim;)o=o._rollbarOldAdd;function n
                                                                      ^
ERROR: In strict mode code, functions can only be declared at top level or immediately within another function.
```

I noticed that `/dist/rollbar.js` stopped having `use strict;` since v2.7.0, probably linked to this commit: https://github.com/rollbar/rollbar.js/commit/41dba6249b5e9583228a648bb55b1d943060010e
See the diff here https://github.com/rollbar/rollbar.js/compare/v2.6.0...v2.7.0#diff-fd4333e372b5f9575015bd04525870c6L47
Do you think you could bring back strict mode in the output, so the error would be fixed? We're stuck with v2.6.0 because of that.
Thanks!

**Comment by waltjones** [comment]
@XavCamp Thank you for the report. I'll take a look.

**Comment by tedwash** [comment]
Just some suggestions, I believe all of the strict mode offenders are in `globalSetup.js`

`fn` declaration is wrapped with if statement for `window` (when minified): https://github.com/rollbar/rollbar.js/blob/master/src/browser/globalSetup.js#L17
`rejectionHandler` declaration is wrapped with if statement for `window` (when minified): https://github.com/rollbar/rollbar.js/blob/master/src/browser/globalSetup.js#L52
`addFn` and `removeFn` function declarations are wrapped in if statement for `addEventListener`: https://github.com/rollbar/rollbar.js/blob/master/src/browser/globalSetup.js#L108

**Comment by waltjones** [comment]
@XavCamp The linked PR temporarily includes dist files built with the strict-loader changes. If you are able to test with this dist, and if you see any issues, let me know.

@tedwash I reviewed the `addEventListener` example in rollbar.min.js both before and after this change, and also in the dist built for 2.6.0 before the Webpack 4 commit. In all cases, it looked to me like the functions are wrapped in the if statement in the min.js file. If I'm missing something, let me know.

**Comment by XavCamp** [comment]
@waltjones thanks for the very quick fix! We are still testing it, we run into unrelated issues and today is holiday in the USA, but we should be able to confirm soon if it worked.
