### ISSUE TITLE
2.14.0 missing from CDN

### ISSUE THREAD

**Issue by victoriafrench** [rollbar/rollbar.js#798]
https://cdnjs.cloudflare.com/ajax/libs/rollbar.js/2.14.0/rollbar.min.js results in a 404

**Comment by waltjones** [comment]
@victoriafrench Thank you for the report. Rollbar is aware of the issue, and published JS snippets such as at https://docs.rollbar.com/docs/browser-js have been updated to use 2.13.0 for now.

**Comment by victoriafrench** [comment]
Cool, we do not use the snippet though. We pull from npm and have the module loader point to the cdn in production, so the version it attempts to pull is the same that comes from npm. We rolled back to .13, but just so that you are aware... there are use cases where the deployments need to sync.

**Comment by waltjones** [comment]
Makes sense, Thank you for pointing that out.

**Comment by waltjones** [comment]
Starting in v2.15.0 (https://github.com/rollbar/rollbar.js/releases/tag/v2.15.0), rollbar.js uses a new CDN, with URLs in the format: https://cdn.rollbar.com/rollbarjs/refs/tags/v2.15.0/rollbar.min.js

Older releases that were stored by cdnjs at Cloudflare can still be found at their original Cloudflare URL.
