### ISSUE TITLE
Can't run linter or tests following instructions in Developing

### ISSUE THREAD

**Issue by kevinrobinson** [rollbar/rollbar.js#801]
hello!  I found some scrubbing behavior that didn't work the way I expected.  I forked and make the change, then tried to run the linter and tests, but have been stymied so far :)

### tests
From the contributing docs:
```
git submodule update --init
npm install -D
make
make test
````
Running `make test` fails with:

```
make test
...
Running "vows:all" (vows) task

  ♢ predicates

  checkLevel an item without a level settings with a critical reportLevel
    ✓ should not send
  checkLevel an item with an unknown level settings with an error reportLevel
    ✓ should not send
  checkLevel an item with an unknown level settings with an unknown reportLevel
    ✓ should send
  checkLevel an item with an unknown level settings without a reportLevel
    ✓ should send
  checkLevel an item with a warning level settings with an error reportLevel
    ✓ should not send
  checkLevel an item with a warning level settings with an info reportLevel
    ✓ should send
  checkLevel an item with a warning level settings with a warning reportLevel
    ✓ should send
/path/rollbar/node_modules/vows/lib/vows/reporters/spec.js:41
    util.print(str);
         ^

TypeError: util.print is not a function
    at Object.print (/path/rollbar/node_modules/vows/lib/vows/reporters/spec.js:41:10)
    at Object.reporter.report (/path/rollbar/node_modules/vows/bin/vows:251:31)
    at Suite.report (/path/rollbar/node_modules/vows/lib/vows/suite.js:257:37)
    at run (/path/rollbar/node_modules/vows/lib/vows/suite.js:299:22)
    at EventEmitter.<anonymous> (/path/rollbar/node_modules/vows/lib/vows/suite.js:294:25)
    at EventEmitter.emit (events.js:210:5)
    at EventEmitter.options.Emitter.emit (/path/rollbar/node_modules/vows/lib/vows.js:237:24)
    at finish (/path/rollbar/node_modules/vows/lib/vows/suite.js:384:27)
    at maybeFinish (/path/rollbar/node_modules/vows/lib/vows/suite.js:377:17)
    at Object.tryEnd (/path/rollbar/node_modules/vows/lib/vows/suite.js:351:13)
```

### linter
Seeing the linter in the `package.json`, I ran `npm run lint` but this only printed out the command line arguments for eslint (ie, not picking up the config).  If I point to the config and run on `src`, I see:

```
npm run lint -c .eslintrc src
...
/path/rollbar/.eslintrc
  0:0  warning  File ignored by default.  Use a negated ignore pattern (like "--ignore-pattern '!<relative/path/to/filename>'") to override

/path/rollbar/src/browser/rollbar.js
  18:34  warning  'defaultOptions' was used before it was defined  no-use-before-define

/path/rollbar/src/server/rollbar.js
  303:16  error  'Promise' is not defined        no-undef
  326:50  error  'cb' is defined but never used  no-unused-vars

✖ 4 problems (2 errors, 2 warnings)
```

This in on OSX fwiw.  Is there something that I'm missing here, or perhaps some other configuration that's needed to run the linter and tests?  Thanks!

**Comment by waltjones** [comment]
@kevinrobinson I've just tried this with both `npm install` and with `npm install -D` in case it might make a difference. Both allowed `make test` to work fine. I'd suggest deleting node_modules and try again.

If you have built any of the examples (./examples/*), delete any of the /node_modules/ that were generated there.

To run eslint, try something like:
`npm run lint -c ./.eslintrc ./src`

This won't lint the exact files that are linted for production, but both `make test` or `make build` will.

**Comment by kevinrobinson** [comment]
@waltjones Thanks!  👍 I think I've already tried those steps and described what happens above.  I tried destroying `node_modules`, and running those same commands you suggested again now, but get the same results that I pasted above.

**Comment by waltjones** [comment]
@kevinrobinson  Do you mind trying the branch in the linked PR, delete node_modules, and see if it fixes your issue?

**Comment by kevinrobinson** [comment]
@waltjones Awesome, thanks!  👍  Yes, that gets us farther, I'll comment on that over there.

fwiw the test run still doesn't pass, but with a different error from Karma now (`primordials is not defined` seems most relevant maybe?):
```
Running "karma:api" (karma) task
22 11 2019 16:38:34.247:ERROR [plugin]: Error during loading "/path/rollbar/node_modules/karma-browserstack-launcher" plugin:
  primordials is not defined
(node:51806) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
⚠ ｢wdm｣: Hash: 6b5f6c65b761c3f08a95
Version: webpack 4.30.0
Time: 11109ms
Built at: 11/22/2019 4:38:35 PM

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/concepts/mode/
ℹ ｢wdm｣: Compiled with warnings.
ℹ ｢wdm｣: Compiling...
⚠ ｢wdm｣: Hash: 8faadd5be7708915e1d9
Version: webpack 4.30.0
Time: 14495ms
Built at: 11/22/2019 4:38:38 PM
           Asset     Size  Chunks             Chunk Names
test/api.test.js  236 KiB       0  [emitted]  test/api.test
Entrypoint test/api.test = test/api.test.js
[0] ./src/utility.js 75.5 KiB {0} [built]
[1] ./test/api.test.js 4.1 KiB {0} [built]
[2] ./src/api.js 6.72 KiB {0} [built]
[3] ./src/merge.js 7.73 KiB {0} [built]
[4] ./vendor/JSON-js/json3.js 24.5 KiB {0} [built]
[5] ./src/apiUtility.js 11 KiB {0} [built]
[6] ./src/truncation.js 12.6 KiB {0} [built]

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/concepts/mode/
ℹ ｢wdm｣: Compiled with warnings.
22 11 2019 16:38:38.886:INFO [karma-server]: Karma v4.0.1 server started at http://0.0.0.0:9876/
22 11 2019 16:38:38.886:INFO [launcher]: Launching browsers ChromeNoSandbox with concurrency unlimited
22 11 2019 16:38:38.887:ERROR [karma-server]: [Error: Found 1 load error
  at Server.<anonymous> (/path/rollbar/node_modules/karma/lib/server.js:182:27)
  at Object.onceWrapper (events.js:299:28)
  at Server.emit (events.js:215:7)
  at emitListeningNT (net.js:1334:10)
  at processTicksAndRejections (internal/process/task_queues.js:79:21)
]

```

And linting still fails the same as above.

**Comment by waltjones** [comment]
@kevinrobinson The "primordials is not defined" error is associated with Node 12. I don't know the root cause, but am able to see the same thing as you when using Node 12. (Node 8 and Node 10 work fine for me.)

On the eslint issue, we are also seeing the same thing. A few observations:
* `make test` and `make build` both skip the /src/server dir.
* The CI lint is done by Codacy, which goes green if lint errors aren't close to the changed code.
* When looking at the file view in Codacy, the /src/server/rollbar.js errors are there as expected.
* My mistake about the -c ./.eslintrc param. eslint doesn't like dot filenames, and will pick up the local .eslintrc anyway.

I've added to the linked PR to clean up the eslint issues. 

For the Node 12 issue, I've opened a new Issue: https://github.com/rollbar/rollbar.js/issues/805

**Comment by kevinrobinson** [comment]
@waltjones Got it, thanks for your help!  Yep, I'm running node 12 so seems like that separate issue covers that.

For linting, maybe it's worth updating the `lint` task in `package.json` so folks can just run that?  Or if that's not super important and you don't mind people pushing pull requests to run in CI then you could add that in the notes for contributing.

Thanks for your help!

**Comment by waltjones** [comment]
@kevinrobinson See PR #809 for an updated `npm run lint`. Let me know if you have any issue with it.

**Comment by kevinrobinson** [comment]
@waltjones `make test` on master runs great and is all green for me now, and the individual `npm run lint` is as well.  thanks! 👍
