### ISSUE TITLE
Setting person in a Node backend

### ISSUE THREAD

**Issue by johnlop** [rollbar/rollbar.js#803]
In a Node server, the logger context will be shared so we can't set the person the same way we would do it on the frontend.
The documentation very briefly mentions NodeJS in it's People Tracking section ([https://docs.rollbar.com/docs/person-tracking#section-node-js](here)) but doesn't give an example on how to use it. My logger can have access to the user info attached to the HTTP request but I don't see a way to set it for a specific log.
Would anyone know how to implement this?

**Comment by brianr** [comment]
Hi @johnlop - have a look at the person tracking docs in the node.js section: https://docs.rollbar.com/docs/nodejs#section-person-tracking 

Hope those make sense, let us know how it goes!

**Comment by johnlop** [comment]
Thanks @brianr, that worked for me!
The Typescript definitions don't mention the Request parameter but it's there.
