### ISSUE TITLE
ERROR in Debug failure: no local name provided for NamespaceImport

### ISSUE THREAD

**Issue by jumamfa** [rollbar/rollbar.js#806]
We have followed the instructions, word for word, and are getting an error during build of the application "ERROR in Debug failure: no local name provided for NamespaceImport". We are using an updated version of typescript which could potentially be causing the issue?

Typescript - ~3.6.4.

Let me know if I can provide any additional information.

**Comment by waltjones** [comment]
@jumamfa Can you confirm the location of the instructions you're using. I want to make sure we're looking at the same thing.

**Comment by jumamfa** [comment]
https://docs.rollbar.com/docs/angular

Angular 2 and later section

On 25 Nov 2019, at 22:10, Walt Jones <notifications@github.com<mailto:notifications@github.com>> wrote:


@jumamfa<https://github.com/jumamfa> Can you confirm the location of the instructions you're using. I want to make sure we're looking at the same thing.

**Comment by waltjones** [comment]
@jumamfa This took me a while to track down.

Typescript 3.6.x appears to no longer allow this import syntax:
`import * as Rollbar from 'rollbar';`

`import Rollbar from 'rollbar';` is the required syntax for 3.6.x. However, it will only work when setting either `allowSyntheticDefaultImports` or `esModuleInterop` in your Typescript options.

While the former syntax was the default for earlier Typescript, and there may be a way to still use it, it seems at least to no longer work by default.

**Comment by jumamfa** [comment]
Great thank you!
