### ISSUE TITLE
TypeError: a.loadFull is not a function when rollbar loaded multiple times

### ISSUE THREAD

**Issue by activescott** [rollbar/rollbar.js#818]
This appears to be similar to #98. After reading that issue, I was able to determine that I am loading rollbar twice (once via snippet/shim and once explicitly via module) but the `TypeError` message could be communicated better.

**Expected behavior** is to to report this as an error and instead handle it more gracefully.

In fact I stumbled across the fact that [better error reporting for this scenario is used to be in the source](https://github.com/rollbar/rollbar.js/commit/ef1c72c27b34efab2cfde2ab5d109aad19b1e951#diff-fd4333e372b5f9575015bd04525870c6R1001) (introduced shortly after #98), but was removed in v2.0 (presumably inadvertently).

**Comment by waltjones** [comment]
Thank you for the report and the analysis. I'll look at getting this in the next release.
