### ISSUE TITLE
Disabled with console logging

### ISSUE THREAD

**Issue by stubar** [rollbar/rollbar.js#821]
Is it possible to disable sending to rollbar but still log to console (via verbose flag).  If I set enabled false and verbose true I don't get any console activity.  I'd like to disable in most environments other than prod but still be able to see .info calls in the console.

**Comment by waltjones** [comment]
@stubar I think you're looking for the `transmit` flag (default `true`). Set `transmit: false` in the config, and the event should be discarded after verbose logging.
