### ISSUE TITLE
Calling Rollbar.configure() during transform doesn't update the payload for current report

### ISSUE THREAD

**Issue by jag1989** [rollbar/rollbar.js#844]
I've noticed an issue whereby if the configuration is updated during the transform method, the updated configuration isn't used in the current payload. It will however be updated for the next payload. 

Example

```
options () {
  return {
      accessToken: 'xxx',
      captureUncaught: true,
      captureUnhandledRejections: true,
      captureIp: false,
      enabled: true,
      logLevel: 'debug',
      payload: {
        environment: 'dev'
        person: {
          id: 'empty'
        }
      },
      transform: payload => this.transformPayload(payload)
    }
}

transformPayload (payload) {
   Vue.rollbar.configure({
      payload: {
        id: 'cookie value'
      }
    })
   this.otherTransformsEtc()
}
```

Expected: 
payload contains:
```
{ 
  notifier: {
    configured_options: {
      payload: {
        person: {
          id: 'cookie value'
       }
     }
   }
}
```

Actual
payload contains:
```
{ 
  notifier: {
    configured_options: {
      payload: {
        person: {
          id: 'empty'
       }
     }
   }
}
```

this is until the next payload is sent, and then the expected payload is used with the correct person.id

Rollbar 2.15.1

**Comment by waltjones** [comment]
That's correct. The purpose of the transform function is to allow adding, removing or overwriting any part of the payload. This requires the payload to already be fully formed at that time. 

The expected use is to add the data, in this case the person id, directly to the payload that is passed in.

**Comment by jag1989** [comment]
Ah okay no problem. So just this looks to suffice?

```
transformPayload (payload) {
  payload.person = {
    id: 'cookie value'
  }
   this.otherTransformsEtc()
}
```

**Comment by waltjones** [comment]
Yes, that should do it.
