### ISSUE TITLE
Specifying telemetry response header yields "Refused to get unsafe header"

### ISSUE THREAD

**Issue by luax** [rollbar/rollbar.js#848]
Hello!

I configured `autoInstrument` to include the response header `Request-Id` only:

```
    autoInstrument: {
      network: true,
      log: true,
      dom: true,
      navigation: true,
      connectivity: true,
      networkResponseHeaders: ['Request-Id'],
      networkResponseBody: false,
      networkRequestBody: false,
    }
```

But got this error message in Chrome (`Refused to get unsafe header "Request-Id"`):

![image](https://user-images.githubusercontent.com/1325939/81295980-81b44280-9071-11ea-8f1a-af8bccceed81.png)

Setting `networkResponseHeaders` to `true` does not include `Request-Id` either. [Potentially related blog post](https://trackjs.com/blog/refused-unsafe-header/
) about this error.

Is this indented?

Thank you,
Ludvig

**Comment by waltjones** [comment]
Under CORS security, the HTTP response must include the `Access-Control-Expose-Headers` header in its response, and whitelist the specific headers the client is allowed to access. This is implemented and enforced by the browser. 

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers

**Comment by luax** [comment]
Thanks @waltjones!
