### ISSUE TITLE
Rollbar.info sent as debug on development

### ISSUE THREAD

**Issue by cesarvarela** [rollbar/rollbar.js#855]
This is driving me crazy,, on my CRA project, if I call `window.Rollbar.info('whatever')` from the React code it appears as `debug` message on the dashboard, but if call `Rollbar.info` from the console it appear as `info` on the dashboard (as it should), Is this because the Rollbar env is set to `development`?

**Comment by cesarvarela** [comment]
This is happening with `Rollbar.warning` too, and the payload clearly sets the level to warning:

![image](https://user-images.githubusercontent.com/1172479/81860644-69469b00-953d-11ea-839e-92dc0e59dbd7.png)

**Comment by waltjones** [comment]
Hi @cesarvarela, if the items are grouped into the same item in the dashboard, the dashboard item will be assigned the level of the first item received. For simple messages, this grouping is usually based on similarity of the message text.

```
Rollbar.debug('test');
Rollbar.info('test');
```
will appear as two occurrences of the item 'test', with level debug.

You can override this by changing the level in the dashboard UI.

Let me know if this doesn't match what you're seeing.

**Comment by cesarvarela** [comment]
Oh I see, that's a bit unintuitive if you ask me, I would never expect different levels to be merged.

So at first a had them set to `Rollbar.log` which I guess it uses the `debug` level, but those wont show on the dashboard because the default filter is only `critical`, so I changed to `Rollbar.warning` and that didn't appear as warning either because it was being merged to `debug`.

**Comment by waltjones** [comment]
@cesarvarela I agree. This topic is being tracked internally at Rollbar, and I'll forward your comments there.
