### ISSUE TITLE
express.js nested routers - full url is not preserved

### ISSUE THREAD

**Issue by agoldis** [rollbar/rollbar.js#865]
Having nested expressjs routes is not reflected in rollbar errors:

```js
// app.js
app.use('/pay`, payRouter)

// payRouter.js
const router = express.Router();
router.use('/i/:id', (req, res) => {
  rollbar.warn('oh!', req);
})
```

Results in Rollbar entry with wrong data:

| Field        | Actual           | Expected  |
| ------------- |:-------------:| -----:|
| `request.url` | `https://<domain>/i/someid` | `https://<domain>/pay/i/someid` |
| `context` | `i/someid` | `pay/i/someid` |

rollbar.js version `2.15.0`

**Comment by austenLacy** [comment]
@agoldis This should be fixed in an upcoming release with these changes https://github.com/rollbar/rollbar.js/pull/872.

Thanks for reporting the issue!
