### ISSUE TITLE
Rollbar 1.3.0-alpha.5 breaks IE8 at `setupCustomJSON` call.

### ISSUE THREAD

**Issue by ryan-roemer** [rollbar/rollbar.js#90]
## Environment

* Rollbar.js `v1.3.0-alpha.5`
* In IE8 (for me on a VirtualBox VM)
* Built off `rollbar.umd.js` (not the minified version)
* Loaded via AMD (requirejs)

## Reproduction

* Open up a page that includes the `rollbar.umd.js` script. (No other actions needed).
* *Expected Behavior*: No errors.
* *Actual Behavior*: Bombs out with the following error

```
Object expected 
line 69 character 6
```

This corresponds to: https://github.com/rollbar/rollbar.js/blob/master/dist/rollbar.umd.js#L69

```js
	    setupCustomJSON(customJSON);
```

## Diagnosis

Poking around a bit further, if I try and introspect `setupCustomJSON` right before L69, it is `undefined`.

```js
	    console.log("setupCustomJSON --> " + (typeof setupCustomJSON));
	    setupCustomJSON(customJSON);
```

produces:

```
LOG: setupCustomJSON --> undefined
```

**Comment by brianr** [comment]
Thanks @ryan-roemer ! We're on it.

**Comment by ryan-roemer** [comment]
@brianr -- I'm also skimming the file more, and another potential issue:

https://github.com/rollbar/rollbar.js/blob/master/dist/rollbar.umd.js#L1626

specifically the `ARRAY.prototype.map` in:

```js
return error.stack.split('\n').slice(1).map(function (line) {
```

for `ErrorStackParser$$parseV8OrIE` is not IE8 compatible -- See http://kangax.github.io/compat-table/es5/#Array.prototype.map and click on "Show obsolete browsers?"

**Comment by coryvirok** [comment]
Hey @ryan-roemer I've done some basic testing in IE8 on XP using this branch - https://github.com/rollbar/rollbar.js/pull/91

I'm hoping to get a release build out tonight.

**Comment by coryvirok** [comment]
The new release is out. https://github.com/rollbar/rollbar.js/releases/tag/v1.3.0-rc.1

I was able to repro the 3 issues you found:
- Array.prototype.map
- Array.prototype.filter
- setupCustomJSON() was undefined

I fixed the above plus a few more and tested IE 8 on Windows XP. Please let me know if this is still happening for you.

**Comment by ryan-roemer** [comment]
@coryvirok @brianr -- Thanks for the hard work to get this out!

The good news:

* It doesn't appear to break IE8 any more on quick inspection.

The bad news:

* We really disfavor true polyfills that mutate our JS environment in _libraries_. Now, by merely including this library `Array.prototype` can be mutated. Generally speaking, _apps_ are fine for polyfills because they are the "end" so to speak and control everything that they are composed of. This is not the same for libraries -- they are used downstream and shouldn't make opinions like this.
    * Ideally, what should happen is you create an internal `map` or `filter` function that short-circuits to native functionality if available and use that. (Think of it like `_.map` or `_.filter`).
    * OR, say `es5-shims` required in IE8. (E.g., this is what React does)

Ideally today, maybe you could switch to non-polyfills -- and looking over the code, I don't think you _need_ `map` and `filter`. Simple `for` loops might suffice and keep the overall size of the JS lib much tighter...

Thanks!

**Comment by coryvirok** [comment]
Thanks for the detailed feedback. That all makes total sense. I'll have something ready ASAP.

**Comment by coryvirok** [comment]
I just released v1.3.0-rc.4 that addresses your feedback - https://github.com/rollbar/rollbar.js/releases/tag/v1.3.0-rc.4

- Removed polyfills from one of our included libraries
  - Replaced with one-off `map()` and `filter()` fallbacks.
- Tested in IE8

**Comment by coryvirok** [comment]
cc @ryan-roemer for above.

**Comment by ryan-roemer** [comment]
@coryvirok @brianr -- Thanks. Changes look good on a quick inspection. We're trying it out.

**Comment by coryvirok** [comment]
Please re-open if this is still an issue.
