### ISSUE TITLE
Improve type definitions for payload property in rollbar configuration options

### ISSUE THREAD

**Issue by MatthewAry** [rollbar/rollbar.js#904]
Right now, it looks like the TS definition for the payload property is incomplete. See: https://github.com/rollbar/rollbar.js/blob/bcf58a6f26f26b9e64b7033a102d960a50ad5319/index.d.ts#L76 

Your own docs have the object definition already in place to some extent https://docs.rollbar.com/docs/rollbarjs-configuration-reference#payload-1 so I think it shouldn't be a problem to make the TS definitions better here as well.

**Comment by waltjones** [comment]
The list in the doc isn't comprehensive. The user can add custom keys of any name and type. I expect there's a way to define this, but just noting the requirement.
