### ISSUE TITLE
Scrubing parameters in request.url and request.query_string

### ISSUE THREAD

**Issue by skh-** [rollbar/rollbar.js#909]
For example, say the URL is `https://example.com/?key=abc`, and we want to scrub `abc`.

Setting `['key']` for `scrubFields` or `scrubPaths` does not seem to have any effect.  I can still see the key in the list of occurrences, in `request.url`, and in `request.query_string`.

In fact, even setting `scrubPaths: ['request.query_string']` as per the [documentation](https://docs.rollbar.com/docs/javascript#scrubbing-items) does not seem to have any effect either.  I still see the key in the query string.

I am not sure if this is a bug, feature, or user error.  Regardless, how would I go about scrubbing specific GET parameters?

**Comment by waltjones** [comment]
Each of these is working for me. I tried `https://example.com/?foo=bar` with `scrubFields: ['foo']` and got this in the occurrence:
```
"request": {
    "url": "http://localhost:8080/?foo=********", 
    "query_string": "?foo=********",
```

I tried `scrubPaths: ['request.query_string']` and got:
```
"request": {
    "url": "http://localhost:8080/", 
    "query_string": "********",
```

If you're still having this issue, maybe verify the config is getting applied?

**Comment by skh-** [comment]
Thanks, @waltjones.  Turns out I was using the [componentized feature](https://github.com/rollbar/rollbar.js/pull/817) and forgot to include `scrub` in `Rollbar.setComponents`.  Works as expected now!

**Comment by waltjones** [comment]
@skh- Good to hear! Thank you for the update.
