### ISSUE TITLE
new locals feature depends on an unsupported module

### ISSUE THREAD

**Issue by seangarner** [rollbar/rollbar.js#924]
Hi.  Loving the idea of the new locals feature.  However, whilst investigating the cause of #923 I noticed that it depends on a module that's not been touched in 6 years.  The maintainer has even commented that it's no longer supported:

https://github.com/admazely/inspector/issues/5#issuecomment-629674778

I wouldn't consider myself an expert in webkit or the inspector api, but I'd have thought that in 6 years it's likely to have broken that API somehow.  Maybe not to the point that it breaks for the rollbars usecase, but how long is that likely to last?  We're backing off using this as the benefit of it doesn't outweigh the risk of a future break during a node/v8 update.

**Comment by waltjones** [comment]
If you npm install that package, it will get picked up. But the intent was to NOT install that package and the require in Rollbar.js will use Node's built in Inspector API. https://nodejs.org/api/inspector.html

Rollbar.js itself doesn't add any inspector package as a dependency, but if the host application does it could override Node's API. This feature and other uses of Node's Inspector API won't work correctly in that case.

**Comment by seangarner** [comment]
Apologies for the delay.  I missed your response. Of course you're right, I
had forgotten about that API being exposed programmatically.

It could be argued that you should be aware of how your dependencies are
working behind the curtains, however in the case of paid services, such as
rollbars I believe the bar should be set a little higher.  The
documentation should state that it depends on an experimental node API.
Personally I'm very cautious about turning on something like that in
production.

Warm regards
Sean
