### ISSUE TITLE
Rollbar isn't reporting on CSP errors?

### ISSUE THREAD

**Issue by karam94** [rollbar/rollbar.js#928]
Hi,

I'm using the standard Rollbar.js library within the base template of a Django application.
My script looks as follows as per the documentation:

```
<script>
  var _rollbarConfig = {
    accessToken: "...",
    captureUncaught: true,
    captureUnhandledRejections: true,
    payload: {
      environment: '{{ options['ENVIRONMENT'] }}',
    },
    autoInstrument: {
      contentSecurityPolicy: true,
      errorOnContentSecurityPolicy: true
    }
  };

  // Rollbar Snippet
...
  // End Rollbar Snipper
```

However unfortunately despite forcing CSP errors that are visible within the browser console, the errors are not appearing within the Rollbar dashboard.

When I force a non-CSP type of error such as by doing:
window.onerror("TestError: Hello world", window.location.href)
then the error appears fine.

Any ideas as to why Rollbar is not reporting on CSP errors?

Thanks

**Comment by waltjones** [comment]
Hi @karam94, 

This depends on the browser's support for the `securitypolicyviolation` event. The Rollbar handler should process any events received there, assuming you are on Rollbar.js v2.20.0 or higher. 

If you let me know the CSP directives used for testing, the specific violation generated, and the browser, I can try to reproduce here.

**Comment by karam94** [comment]
> Hi @karam94,
> 
> This depends on the browser's support for the `securitypolicyviolation` event. The Rollbar handler should process any events received there, assuming you are on Rollbar.js v2.20.0 or higher.
> 
> If you let me know the CSP directives used for testing, the specific violation generated, and the browser, I can try to reproduce here.

Hi @waltjones 

The browser certainly supports `securitypolicyviolation` because as a fallback we've added:
```
  document.addEventListener("securitypolicyviolation", (e) => {
    window.onerror(`CSP ERROR: ${e.violatedDirective}: ${e.blockedURI}`);
  });
```
and Rollbar picks up these fine.
My browser is the latest version of Chrome & the CSP directives in this case were script-src.

I copied the Rollbar snippet yesterday from what appeared when first logging in to the account and it looks like it's using 2.19.2 within the network tab:
https://cdn.rollbar.com/rollbarjs/refs/tags/v2.19.2/rollbar.min.js

How can I ensure I'm on the latest version? Does the script that appears for users to copy need updating?

Thanks

**Comment by karam94** [comment]
I've just noticed that the Quick Start script to copy here:
https://docs.rollbar.com/docs/browser-js

Points to v2.21 etc.

It seems that what was copied upon first logging in to the dashboard contained an outdated (v2.19.2) reference to rollbar.
I'm upgrading the script now and will report back :)

**Comment by waltjones** [comment]
Was just about to point you there. :+1:

**Comment by karam94** [comment]
Upgrading to v2.21 has worked.
Just please double check the script on the new account/first page after login to avoid people accidentally copying an older version of the script and running in to similar issues in the future.

Thanks for your help @waltjones!
