### ISSUE TITLE
TypeError: t.headers.get is not a function. (In 't.headers.get("Content-Type")', 't.headers.get' is undefined)

### ISSUE THREAD

**Issue by dseeker** [rollbar/rollbar.js#930]
We're using an unusual setup with a hybrid iOS application running a compiled js file inside a native iOS app.
Seeing the user's report a lot of them are having an issue with the rollbar lib and I can't quite pinpoint why that's the case. 
There's is probably some errors trying to get notified but it's failing after this line.

Would it be possible to add a check before executing headers.get()? I'm not sure how important setting the json type is, we could have some default value in case getting that header fails

on this line
https://github.com/rollbar/rollbar.js/blob/2cf9c2b85668d1f00314468a6dbbd84dd2583f13/src/browser/telemetry.js#L388

maybe something like this?
```js
metadata.response_content_type = (resp.headers && typeof resp.headers.get === 'function') ? resp.headers.get('Content-Type') : '';
``` 

please let me know if there is a better way to debug this. I can't really reproduce it locally, I'm just seeing this in user's rollbar report

**Comment by waltjones** [comment]
Yes, I think we can do something here.

**Comment by waltjones** [comment]
@dseeker I hoped this could be accommodated while leaving network telemetry enabled. Instead I think it will be necessary to disable in your Rollbar config:

```javascript
config.autoInstrument = { network: false }
```
This should solve the xhr/fetch related errors.

See https://docs.rollbar.com/docs/rollbarjs-telemetry for more details on telemetry support.
