### ISSUE TITLE
Is there any example for Angular Source Maps Implementation?

### ISSUE THREAD

**Issue by hotequil** [rollbar/rollbar.js#940]

**Comment by waltjones** [comment]
This Angular example builds source maps:
https://github.com/rollbar/rollbar.js/tree/master/examples/angular2

And this PR description includes two Angular examples for uploading with rollbar-cli. 
https://github.com/rollbar/rollbar-cli/pull/1

If you're using curl, the same basic idea applies. The rollbar-cli just makes it easier to upload all at once. The doc for using curl is here: https://docs.rollbar.com/docs/source-maps

**Comment by hotequil** [comment]
Thank you!!! But i tried this command `rollbar-cli upload-sourcemaps dist/my-repo --access-token MY_ACCESS_TOKEN --url-prefix 'http://localhost:4200/' --code-version angular11v1 -s`, then results in some files this error: `[Error ] insufficient privileges: post_server_item scope is required but the access token only has post_client_item.`

**Comment by waltjones** [comment]
Rollbar's source maps API requires a different token than the browser token. In you Rollbar dashboard under /settings/access_tokens/ look for a `post_server_item` token.

**Comment by hotequil** [comment]
Ohhh, okay!!! thank you! works for me

**Comment by waltjones** [comment]
:+1: Great to hear!
