### ISSUE TITLE
Can`t get real stack message from window.onerror

### ISSUE THREAD

**Issue by GMCoder** [rollbar/rollbar.js#944]
Here are some error stack from window.onerror function I`ve got 
{"message":"Cannot read property 'trigger' of undefined","stack":["TypeError"," Cannot read property 'trigger' of undefined\n    at <anonymous>","1","12"]}
Why anonymous?Not file url.

**Comment by waltjones** [comment]
I don't recognize the format of this JSON, and it doesn't look like an `onerror` argument. Is it JSON from a Rollbar occurrence? If so, what is in the key `notifier.diagnostic.raw_error.stack`?

**Comment by GMCoder** [comment]
> I don't recognize the format of this JSON, and it doesn't look like an `onerror` argument. Is it JSON from a Rollbar occurrence? If so, what is in the key `notifier.diagnostic.raw_error.stack`?

This json didn`t come from Rollbar.Just an error that i got with window.onerror.

**Comment by waltjones** [comment]
@GMCoder I'm closing this as not addressable in rollbar.js. If I've misunderstood, and you can provide more context, feel free to reopen.
