### ISSUE TITLE
Does not support sourcesContent in sourcemaps and require sources to be available for backend code snippets to work

### ISSUE THREAD

**Issue by stalniy** [rollbar/rollbar.js#957]
The latest version of rollbar doesn't support inlined source maps with `nodeSourceMaps: true` option. 

I did some debugging and it appears that [this line](https://github.com/rollbar/rollbar.js/blob/master/src/server/parser.js#L256) checks file paths from all frames in spite of the existence of `sourcesContent` property in source map.

This requires me to distribute sources together with compiled code and sourcemaps what is a bit inconvenient in my case.

**Comment by waltjones** [comment]
ch87007

**Comment by stalniy** [comment]
@waltjones can you provide any approximate ETA when this will be fixed?

**Comment by waltjones** [comment]
Next release, ~ 2 weeks.

**Comment by waltjones** [comment]
Released in v2.24.0. https://github.com/rollbar/rollbar.js/releases/tag/v2.24.0

**Comment by stalniy** [comment]
Nice! works thank you!
