### ISSUE TITLE
Links in UMD section return 404

### ISSUE THREAD

**Issue by piotrd** [rollbar/rollbar.js#96]
Hi,

Just wanted to use the UMD version of Rollbar, but none of the links on https://github.com/rollbar/rollbar.js#umd work. Can you please update them?

**Comment by piotrd** [comment]
I found all the needed resources in 1.3.0's zip, but still, UMD section should be fixed ;)

**Comment by jondeandres** [comment]
Thanks @piotrd, it's now fixed :-).
