### ISSUE TITLE
Request object is not sent in NodeJS express server

### ISSUE THREAD

**Issue by nielsbauman** [rollbar/rollbar.js#962]
We have the following setup for Rollbar:

```js
const rollbar = new Rollbar({
	accessToken: 'xxx',
	captureUncaught: true,
	captureUnhandledRejections: true,
	verbose: true,
	nodeSourceMaps: true,
	autoInstrument: true,
});

function app() {
	const server = express();
	server.use(rollbar.errorHandler());
}
```

While we do receive the errors, we don't get any `request` info and we thus don't know the request URL (which we need to investigate some errors).
We recently upgraded to version 2.24.0 as an attempt to fix this problem, but it unfortunately did not add the request information (however, we do receive the `telemetry` object in the errors).

Is there something else we should be doing to make this work?

**Comment by waltjones** [comment]
This requires passing the request object as described here: https://docs.rollbar.com/docs/nodejs#the-request-object

Currently, the Express request object isn't detected or added automatically.

**Comment by nielsbauman** [comment]
@waltjones I'm calling `rollbar.errorHandler()`, which is defined [here](https://github.com/rollbar/rollbar.js/blob/master/src/server/rollbar.js#L296). The `this.error()` calls at the bottom of that function pass the request object right?

**Comment by waltjones** [comment]
Oops, yes.

I'll take a closer look.

**Comment by waltjones** [comment]
@nielsbauman I've tested this on Express 4.16.1 and the request does get attached correctly when an error is handled by `app.use(rollbar.errorHandler());`. 

My test route where the error is thrown looks like this:
```
router.get('/', async function(req, res, next) {
  try {
    throw new Error('express test error');
    res.render('index', { title: 'Express' });
  } catch (e) {
    next(e);
  }
});
```
If I do not call `next()` with the error:
```
router.get('/', async function(req, res, next) {
    throw new Error('express uncaught error');
    res.render('index', { title: 'Express' });
});
```
This will not get sent to the Express error handler. It will bubble up to a Node `uncaughtException` event and Rollbar will handle there. In that case, the request object isn't available. As far as I know, the route must call `next()` for Express error middleware to be called.

**Comment by nielsbauman** [comment]
@waltjones thank you for taking the time to investigate and explain 👍🏻. I've done some investigation myself and it turned out the errors weren't passing through Rollbar's `errorHandler`. Instead, they were logged as uncaught errors. We were able to implement a fix for that and now everything is working as expected.
