### ISSUE TITLE
captureIp has no effect for Electron apps

### ISSUE THREAD

**Issue by shadow-light** [rollbar/rollbar.js#963]
The `captureIp` config param appears to be ignored when there is no `window`, i.e. Node. Which makes sense when you are capturing errors on a node server. But it also stops capturing IP for Electron apps, where it can be useful to be able to know how many users are affected by an issue.

A workaround is to manually set `payload.request.user_ip` to `$remote_ip` or `$remote_ip_anonymize`.

**Comment by waltjones** [comment]
Released in v2.25.2, https://github.com/rollbar/rollbar.js/releases/tag/v2.25.2
