### ISSUE TITLE
UUID dependency is outdated

### ISSUE THREAD

**Issue by philipboeken** [rollbar/rollbar.js#966]
This package currently requires `uuid@3.0.x`, whereas the current version of uuid is `8.3.2`.

It also gives a warning after running yarn:

```
warning rollbar > uuid@3.0.1: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
```

They have made an [upgrade guide](https://www.npmjs.com/package/uuid#upgrading-from-uuid3x), however I'm not familiar with the rollbar.js source code so I'd rather not make a PR for this upgrade.

**Comment by Akallabet** [comment]
I hate to that guy, but is there an update?
