### ISSUE TITLE
Automatic Download doesn't work because of wrong url for source maps

### ISSUE THREAD

**Issue by bondom** [rollbar/rollbar.js#974]
When rollbar tries to download my minified bundles automatically, for some reason it uses url with 2 slashes at the beginning.
When I open Source Maps tab I see rows with
Minified url is like: `//custom-url.com/my-custom-bundle.js`
Version is `unknown`.
And when I open a detailed view of the row, I see: `Failed to download source map. HTTP unknown for minified JS file at ...`
When I add my source map manually, everything works fine.

I guess that rollbar takes full url with protocol and fails because of it. I think so because when I try to add source map manually and I specify my minified url with protocol at the beginning, I get the same Minified url and error message as above.

**Comment by waltjones** [comment]
This is handled in the Rollbar back end, and not in the Rollbar.js SDK. The request needs to go to Rollbar support (support@rollbar.com or via chat).
