### ISSUE TITLE
nextjs example

### ISSUE THREAD

**Issue by chrillep** [rollbar/rollbar.js#979]
like sentry could you please add examples of usage client and serverside for

- nextjs
- nextjs with custom server

ref:
- https://github.com/vercel/next.js/tree/canary/examples/with-sentry

- https://github.com/getsentry/sentry-javascript/tree/master/packages/nextjs

**Comment by cyrusradfar** [comment]
Thank you @ijsnow. Thanks @chrillep for the nudge!
