### ISSUE TITLE
Error: SyntaxError: Unexpected end of JSON input when server response has no body but JSON content type

### ISSUE THREAD

**Issue by yjukaku** [rollbar/rollbar.js#999]
Our server responds to a certain endpoint [with headers but no body](https://api.rubyonrails.org/classes/ActionController/Head.html).

Expected result:
No error is thrown by rollbar.js

Actual result:
The rollbar.js method `scrubJson` fails on these responses because it tries to parse the empty body as JSON.

https://github.com/rollbar/rollbar.js/blob/a9c567cd1886f177fa4719a0054bff8280928fce/src/browser/telemetry.js#L438

**Comment by yjukaku** [comment]
Please reopen as this is now an issue again 😄

**Comment by ijsnow** [comment]
I’ll look into it! I too couldn’t get your test to fail, but could you spin up a minimal repo that shows the issue?

**Comment by yjukaku** [comment]
Yep, here's one written in the Fastify JS framework: https://glitch.com/edit/#!/boundless-separated-antimony

The POST to `/` responds with nothing but the header `Content-Type` set to `application/json`. That makes Rollbar's scrubJson function error out, as you can see in the console on that page.

**Comment by ijsnow** [comment]
Sorry, but I'm unable to recreate the issue. I saw an error pop up before I changed to token to my personal projects token in the rollbar config. I recreated the same endpoint in a rust server as well for the nextjs example in the rollbar-react project and can't get what you're describing. The only time I saw a JSON error was when I tried parsing the response body explicitly in the promise response.

**Comment by yjukaku** [comment]
I'm not sure why it's not reproducible for you using the glitch link, but here's a screencast from right now:

Using Chrome 99
Mac OS 12.2.1
https://user-images.githubusercontent.com/908365/158882611-5909ae77-8304-4ce5-bf4b-6476fb80c244.mov

**Comment by yjukaku** [comment]
Here's a fork of the react-rollbar Github repo with changes necessary to the nextjs server to trigger the error.

**Comment by ijsnow** [comment]
Ah, I wasn't specifying the request's headers as application/json, just the response! Thanks for being responsive and helping me reproduce!

**Comment by ijsnow** [comment]
I went ahead and opened another PR with the same change. I couldn't cause a test to fail either. I'll talk with another community member about merging it since it shouldn't be throwing an error, but I'll also note that the problem goes away when I prevented the server from incorrectly broadcasting that it is responding with JSON.

**Comment by waltjones** [comment]
This is released in 2.25.0. https://github.com/rollbar/rollbar.js/releases/tag/v2.25.0
